### ISSUE TITLE
highspy unnecessarily requires pyomo

### ISSUE THREAD

**Issue by nrontsis** [ERGO-Code/HiGHS#1022]
`highspy` [lists `pyomo` as a dependency](https://github.com/ERGO-Code/HiGHS/blob/master/src/interfaces/highspy/pyproject.toml#L6), just to use [a single small function from `pyomo` in it's setup.py](https://github.com/ERGO-Code/HiGHS/blob/master/src/interfaces/highspy/setup.py#L5).

I think it's best that requirements are kept as light as possible.

Towards this, I can open a PR to remove the `pyomo` dependency by simply copying [`find_library`](https://github.com/Pyomo/pyomo/blob/main/pyomo/common/fileutils.py#L293) in setup.py.

**Comment by jajhall** [comment]
Thanks, I've flagged this up to @galabovaa and she'll remove the dependency

**Comment by jajhall** [comment]
I had a quick look at stripping out the need for `pyomo` , and `highspy` also uses `capture_output` for its logging call-back. 

I tried including `find_library` in [setup.py](https://github.com/ERGO-Code/HiGHS/blob/master/src/interfaces/highspy/setup.py)   but got complaints about `envvar` not being defined. I guess that something needs to be "imported", but I'm not a Python developer.

Can we take you up on your offer to open a PR to remove the `pyomo` dependency by simply copying `find_library` (and `capture_output`) in setup.py.

**Comment by jajhall** [comment]
Closed by #1343
