### ISSUE TITLE
Mixed integer programming calls the dual simplex algorithm. When I ran the MIPLIB2017 benchmark with HiGHS, I found it impossible to test whether parallel dual simplex algorithms improve their performance. How can I test the efficiency of the parallel dual simplex algorithm on mixed-integer problems?   

### ISSUE THREAD

**Issue by tu3256076** [ERGO-Code/HiGHS#1030]
Looking forward to your reply.

**Comment by jajhall** [comment]
For many reasons, the MIP solver uses the serial dual simplex solver. This cannot be over-ridden, so what you want to do cannot be done

**Comment by Leoncoci** [comment]
yep，HiGHS MIP solver is just a serial program

**Comment by tu3256076** [comment]
> yep，HiGHS MIP solver is just a serial program

bro,I am also in Hefei, can I know your wechat

**Comment by tu3256076** [comment]
> For many reasons, the MIP solver uses the serial dual simplex solver. This cannot be over-ridden, so what you want to do cannot be done

Thanks for your reply

**Comment by tu3256076** [comment]
> For many reasons, the MIP solver uses the serial dual simplex solver. This cannot be over-ridden, so what you want to do cannot be done
If I want to know the principle of MIP problem solving in HIGS, is there any related public papers or documents? Thank you for your answer

**Comment by jajhall** [comment]
There are no papers or documents describing the techniques used in the HiGHS MIP solver. It just uses well-chosen and well-implemented standard techniques

**Comment by tu3256076** [comment]
> 



> There are no papers or documents describing the techniques used in the HiGHS MIP solver. It just uses well-chosen and well-implemented standard techniques

Thank you for your help, professor Hall. 
Another question. When I test the parallel mode”PAMI algorithm“ and the SERIAL mode” SERIAL algorithm“ of the dual simplex, I find that the improvement efficiency cannot reach the results of huang's doctoral paper. At present, I cannot determine whether there is a problem with my machine Settings. I hope you can help me determine the possible factors for the lack of efficiency improvement. 
Thanks again！

**Comment by jajhall** [comment]
We've no time to write papers!

**Comment by tu3256076** [comment]
> 
Thank you for your patience in answering my doubts!
It saves me a lot of time.

**Comment by tu3256076** [comment]
The price phase (row_ep×A) in the serial simplex algorithm uses: priceByColumn and priceByRowWithSwitch algorithms. I have two doubts about this:

1. Why choose the priceByColumn() method based on "row_ep_density"? Both row_ep and A are stored in compressed sparse row format, so shouldn't priceByRowWithSwitch() be the fastest way to use price? In my actual tests,however, when I just used priceByRowWithSwitch(), it was slower. I'm confused about： when priceByColumn() is faster than priceByRowWithSwitch().

2. In priceByRowWithSwitch(), the function implementing standard row-wise price is priceByRowDenseResule(), which is only delate "if(multiplier)"  from the implemented in sparse price. While row_ep is compressed and stored, multiplier must be a nonzero element, this judgment seems useless.
