### ISSUE TITLE
Does Highs invoke the underlying parallel dual simplex algorithm for mixed-integer problems

### ISSUE THREAD

**Issue by tu3256076** [ERGO-Code/HiGHS#1033]

**Comment by odow** [comment]
No. This is a duplicate of your question: https://github.com/ERGO-Code/HiGHS/issues/1030.

If you have further questions, you should open a discussion instead: https://github.com/ERGO-Code/HiGHS/discussions. The GitHub issues are for bug reports and feature requests.

**Comment by tu3256076** [comment]
> No. This is a duplicate of your question: #1030.
> 
> If you have further questions, you should open a discussion instead: https://github.com/ERGO-Code/HiGHS/discussions. The GitHub issues are for bug reports and feature requests.

If I want to know the principle of MIP problem solving in HIGS, is there any related public papers or documents? I did not find author Leona Gottwald's rationale paper for this part of the implementation.Thanks again.

**Comment by odow** [comment]
As far as I know, this is not documented anywhere. The source code is public and MIT licensed, which should be sufficient.

**Comment by jajhall** [comment]
> Do you know if HIGHS uses multithreading in solving MIP problems（not simplex）

Not yet
