### ISSUE TITLE
HiGHS misinterpretation of equivalent models

### ISSUE THREAD

**Issue by maramos874** [ERGO-Code/HiGHS#1037]
Both attached models optimal solution should be equal (proven by solving with CBC and Copt). The only difference between them is that the optimal solution value of a binary variable is forced in modelWforce.lp

The optimal solution correspond to the model.lp one, however HiGHS presolve solves the fixed version to optimality, but not to the optimal value of model.lp

When solving with presolve=off, both models are solved to optimality, so the presolve is mistakenly removing all rows and columns.

[model.lp](https://drive.google.com/file/d/1d7qKX4JN8Svkf0gKHJaEx2JRCFts7HgL/view?usp=share_link)
[modelWForce.lp](https://drive.google.com/file/d/1IyClxk8t33vACrvEA_cQ-zk46JF3vjo9/view?usp=share_link)

**Comment by jajhall** [comment]
That's very odd. I wouldn't say that it's necessarily an error to reduce the problem to empty, though. It could also be an error in primal postsolve. Investigating

**Comment by jajhall** [comment]
So, @lgottwald , the issue is that with `presolve=off`, `modelWForce.lp` is solved correctly. However, with `presolve=on`, `modelWForce.lp` is not solved correctly. Note that HiGHS reduces the MIP to empty, whereas Gurobi reduces it to `Presolved: 2 rows, 4 columns, 8 nonzeros`

**Comment by maramos874** [comment]
Any updates on this issue? Thanks in advance

**Comment by jajhall** [comment]
Sorry, no

**Comment by jajhall** [comment]
Unfortunately it's hard to support the MIP solver now that we've lost our developer. I aim to improve this situation by studying it (more) myself, or by hiring someone who knows MIP better than me, but that's hard!

**Comment by fwesselm** [comment]
I am experimenting with switching off certain presolve techniques. There is a very minor bug in the outputs, i.e. the code complains that I am trying to disallow presolve techniques that are actually switched on.

[output.txt](https://github.com/ERGO-Code/HiGHS/files/12698874/output.txt)

**Comment by fwesselm** [comment]
When I disable the removal of doubleton equations then modelWForce.lp is solved correctly:

`highs->setOptionValue("presolve_rule_off", 512);`

**Comment by jajhall** [comment]
> I am experimenting with switching off certain presolve techniques. There is a very minor bug in the outputs, i.e. the code complains that I am trying to disallow presolve techniques that are actually switched on.

Thanks, I've made this change and added some commenting in [fix-1037](https://github.com/ERGO-Code/HiGHS/tree/fix-1037)

**Comment by jajhall** [comment]
> When I disable the removal of doubleton equations then modelWForce.lp is solved correctly:
> 
> `setOptionValue("presolve_rule_off", 512);`

That's great, thanks

I've tried solving the relaxation with/without removal of doubleton equations, but it makes no difference: the correct solution is always obtained. Hence I don't think that there's an error in the removal of doubleton equations, but an error applying a MIP presolve rule as a consequence of the doubleton equation(s).

We have a mechanism for identifying which presolve rule is causing an error by limiting the number of reductions that can be applied - and performing a binary search. Using 
[franz.cpp.txt](https://github.com/ERGO-Code/HiGHS/files/12699557/franz.cpp.txt) unfettered presolve performs 115 reductions, and it's reduction 110 that causes the error. I can't look into this now, but will do in due course.


>

**Comment by fwesselm** [comment]
Thank you. I will try to debug some more. It looks like a variable is incorrectly identified as dominated (in reduction 110).

**Comment by jajhall** [comment]
This issue also affects
* ~/Models/Kelly/JFSC-IMF-QL.mps 
* ~/Models/Notebaert/notebaert2.mps

**Comment by jajhall** [comment]
This issue has been tracked down to implied column bounds being incorrect after the aggregator is applied. 

The fix will take a little time,

If you're still interested in using HiGHS, I'll let you know when it's available

**Comment by maramos874** [comment]
I surely am, thank you!
