### ISSUE TITLE
applyScalingToLpCol/Row seem to apply scaling factor twice

### ISSUE THREAD

**Issue by ambros-gleixner** [ERGO-Code/HiGHS#1038]
In
```
  for (HighsInt el = lp.a_matrix_.start_[col];
       el < lp.a_matrix_.start_[col + 1]; el++)
    lp.a_matrix_.value_[el] *= colScale;
  lp.a_matrix_.scaleCol(col, colScale);
```
and
```
  for (HighsInt col = 0; col < lp.num_col_; col++) {
    for (HighsInt el = lp.a_matrix_.start_[col];
         el < lp.a_matrix_.start_[col + 1]; el++) {
      if (lp.a_matrix_.index_[el] == row) lp.a_matrix_.value_[el] *= rowScale;
    }
  }
  lp.a_matrix_.scaleRow(row, rowScale);
```
the last lines seem too repeat the effect of the for loops.

**Comment by jajhall** [comment]
Indeed, very odd. I'll investigate

**Comment by ambros-gleixner** [comment]
Thanks!

**Comment by ambros-gleixner** [comment]
I see the fix has been reverted? Should this be reopened?

**Comment by jajhall** [comment]
That's because the fix was originally pushed to `master`, and @galabovaa (correctly) wants such modifications to be pushed to `latest`, leaving `master` to be updated once `latest` is properly tested. She's also working on a fix to our CI testing (due to a change on GitHub) that was causing a CI fail - and we can't have `master` showing such a thing.

**Comment by ambros-gleixner** [comment]
Understood, thanks! One question then: Which is the appropriate branch for us to test with, what do you recommend?

**Comment by jajhall** [comment]
If you're wanting to pick up fixes for issues like this immediately, then `latest` is the best branch to use. 

More generally, there's a chance that something is pushed to `latest` that changes the behaviour of HiGHS for you - but that's the risk of using something that's not a defined version.

On the timing issue, I now see that what (eg) Gurobi gives as `Runtime` is the time for the last optimization, and not the cumulative runtime. I'll modify HiGHS accordingly, but this will only appear in v2.0. Until then I'll include a "reset" method in the HiGHS class

**Comment by ambros-gleixner** [comment]
:+1:
