### ISSUE TITLE
Publish highspy Python 3.11 wheels

### ISSUE THREAD

**Issue by EwoutH** [ERGO-Code/HiGHS#1042]
Currently there are not Python 3.11 wheels available for [highspy](https://pypi.org/project/highspy/) on PyPI. It would be great if those could be build and uploaded!

**Comment by jajhall** [comment]
Has this been done @galabovaa?

**Comment by AdeelK93** [comment]
This would be great to have! Seems the lack of 3.11 on PyPi is blocking quite a few downstream packages

**Comment by melanopsis** [comment]
Just to chime in, the wheel seems to build properly without any modifications. I see that Python 3.11 is listed explicitly in `setup,py` so the support is already there.

**Comment by jajhall** [comment]
Thanks for all this. @galabovaa is away and then busy until the middle of next week, but I'm sure she'll address this without undue delay.

**Comment by galabovaa** [comment]
Hi all, python 11 has now been added to highspy on PyPI. Would you please give this another go?

**Comment by melanopsis** [comment]
Hi @galabovaa, it installs and runs fine on Linux. Thank you!
