### ISSUE TITLE
Termination status when hitting a solution number limit

### ISSUE THREAD

**Issue by ccoffrin** [ERGO-Code/HiGHS#1069]
When using the option, `mip_max_improving_sols` the `termination_status` is `ITERATION_LIMIT` but based on the [status code documentation](https://jump.dev/JuMP.jl/stable/moi/reference/models/#MathOptInterface.TerminationStatusCode) I think `SOLUTION_LIMIT` would be more suitable.

MWE 
```
using JuMP, HiGHS

model = Model(HiGHS.Optimizer)
set_optimizer_attribute(model, "mip_max_improving_sols", 1)

n = 10

v = rand(n)
w = rand(n)

@variable(model, 0 <= x[1:n] <= 10, Int)

@objective(model, Max, sum(v[i]*x[i] for i=1:n))

@constraint(model, sum(w[i]*x[i] for i=1:n) <= 10)

optimize!(model)

println(termination_status(model))
println(primal_status(model))
println(objective_value(model))
println(value.(x))
```

CC @odow @robbybp

**Comment by ccoffrin** [comment]
Moving to correct repo, https://github.com/jump-dev/HiGHS.jl/issues/143

**Comment by odow** [comment]
Re-opening because HiGHS.jl reports the status as reported by HiGHS.

In this case, HiGHS returns `kIterationLimit`:

https://github.com/ERGO-Code/HiGHS/blob/46f6ceb269ed44934c79fc9e488487fcb6313b6a/src/mip/HighsMipSolverData.cpp#L1599-L1607

**Comment by ccoffrin** [comment]
Lucky guess then!

**Comment by jajhall** [comment]
I guess that @lgottwald didn't want to introduce a new `HighsModelStatus`. I'll do this

**Comment by jajhall** [comment]
Inserting `HighsModelStatus::kSolutionLimit` in its proper place (ie before `HighsModelStatus::kUnknown`) will break the C API. This will be done when V2.0 is created and, for now, `HighsModelStatus::kSolutionLimit` comes after `HighsModelStatus::kUnknown`.

**Comment by jajhall** [comment]
There are three other places in the MIP solver where `HighsModelStatus::kIterationLimit` was returned rather than `HighsModelStatus::kSolutionLimit`
