### ISSUE TITLE
Report time cost on different parts of solving

### ISSUE THREAD

**Issue by wang123zhao551451** [ERGO-Code/HiGHS#1108]
Hi, I am a developer of simplex LP solvers in my group, and I am interested in the time cost of different parts in the LP solving process in HiGHS. I've found the function "report(......)" in HighsTimer.h, but I don't know where to call it and what are the parameters. Both an example in C++ or the instruction to temporarily modify the source code are fine.
Thanks

**Comment by jajhall** [comment]
Sorry, this is not functionality that we support for users, so not an issue

**Comment by wang123zhao551451** [comment]
Thanks for your quick reply
