### ISSUE TITLE
C API `Highs_version`, `Highs_githash` and `Highs_compilation_date` functions don't work

### ISSUE THREAD

**Issue by cyderize** [ERGO-Code/HiGHS#1113]
The `Highs_version`, `Highs_githash` and `Highs_compilation_date` C API functions return invalid pointers because they create a `std::string` on the stack and then return the `c_str()`, which becomes invalid once the function returns and the string goes away.

Changing the definition of `Highs_version` to
```c++
const char* Highs_version(void) {
  static std::string version = highsVersion();
  return version.c_str();
}
```
fixed the issue for me - if this looks like the correct way to fix this, I'm happy to open a pull request to make the changes.

**Comment by mingodad** [comment]
Ideally the `highsVersion` should be :
```
#define QUOTEINT(str) #str
const char *highsVersion() {
  return  "v"  QUOTEINT(HIGHS_VERSION_MAJOR)  "." QUOTEINT(HIGHS_VERSION_MINOR)  "."
      QUOTEINT(HIGHS_VERSION_PATCH);
}
```

**Comment by jajhall** [comment]
Thanks. I'll make these modifications

**Comment by jajhall** [comment]
> Ideally the `highsVersion` should be :
> 
> ```
> #define QUOTEINT(str) #str
> const char *highsVersion() {
>   return  "v"  QUOTEINT(HIGHS_VERSION_MAJOR)  "." QUOTEINT(HIGHS_VERSION_MINOR)  "."
>       QUOTEINT(HIGHS_VERSION_PATCH);
> }
> ```

Doesn't work, so I'll keep what's there

**Comment by jajhall** [comment]
Just spotted that the C API method names for version* and compilation date are inconsistent with the naming convention. Not in any release yet, so I'll correct these

**Comment by mingodad** [comment]
Sorry it was my fault !
Here is a working version that `stringfy` properly:
```
#include <stdio.h>
#define HIGHS_GITHASH "b3381829e"
#define HIGHS_COMPILATION_DATE "2023-01-27"
#define HIGHS_VERSION_MAJOR 1
#define HIGHS_VERSION_MINOR 5
#define HIGHS_VERSION_PATCH 0


#define STRINGFY(s) STRINGFY0(s)
#define STRINGFY0(s) #s
const char *highsVersion() {
  return  "v"  STRINGFY(HIGHS_VERSION_MAJOR)  "." STRINGFY(HIGHS_VERSION_MINOR)  "."
      STRINGFY(HIGHS_VERSION_PATCH);
}

int main() {
	printf("highsVersion = %s\n", highsVersion());
	return 0;
}
```
Ouptput:
```
./test-stringfy
highsVersion = v1.5.0
```

**Comment by jajhall** [comment]
Thanks, but why is this preferable to what was written originally?

**Comment by mingodad** [comment]
Because it doesn't make any copy (the actual make several copies) and it's simpler.

**Comment by jajhall** [comment]
Fair enough on the copy, but I don't have a clue as to how it works, so it's not simpler to me. I know `#define` creates a macro that's then applied, but what is actually happening with

#define STRINGFY(s) STRINGFY0(s)
#define STRINGFY0(s) #s

when `STRINGFY(s)` is passed an `int` argument?

**Comment by mingodad** [comment]
It's all done by the preprocessor and it needs two indirections to work see here https://gcc.gnu.org/onlinedocs/gcc-3.4.3/cpp/Stringification.html .

**Comment by mingodad** [comment]
Yes it's portable it's the normal preprocessor machinery every C/C++ compiler does the same.

**Comment by jajhall** [comment]
So, when highsVersion returns a const char *, is there no need for the interim

static std::string version = highsVersion();
  return version.c_str();

In other words, Highs_version() can just be

const char* Highs_version(void) { return highsVersion(); }

**Comment by mingodad** [comment]
Exactly !

**Comment by jajhall** [comment]
Fix has been pushed to `latest`, and will be in `v1.5.0`
