### ISSUE TITLE
Enumerating `OptionRecord`s using C API

### ISSUE THREAD

**Issue by cyderize** [ERGO-Code/HiGHS#1114]
Hi, I'm in the process of converting MiniZinc's new HiGHS interface to use the C API rather than the C++ API (this way we can turn it into a plugin which dynamically loads the HiGHS library at runtime).

However, there are a few C++ APIs which are not available using the C interface. Most of these I've been able to easily add in my fork (I'll open a pull request soon).

We need to be able to get all of the available options, so that we can generate a GUI for setting the options from the MiniZinc IDE. Currently in C++, we loop through the `records` field of `HighsOptions`, but I'm not entirely sure what an API for accessing these records in C should look like (we need access to the default values and bounds of the options).

Gurobi provides `GRBgetnumparams` and `GRBgetparamname` to get the number of parameters, and then get the name from the index. Perhaps something similar could be done here, with additional functions to access the descriptions, default values, and bounds of options.

**Comment by jajhall** [comment]
By "number of parameters", do you mean the number of options? I've searched for `GRBgetnumparams` in the Gurobi documentation, but nothing comes up.

Creating a method in the C API to achieve what you want won't be difficult. I'll get on with it this weekend

Note that there are some methods in the C++ API that are for internal use only, so shouldn't be in the C API. I'll see what you've put in your PR - please make this to `latest`, not `master` - and delete as appropriate.

**Comment by cyderize** [comment]
Indeed those Gurobi functions seem to appear in the headers but apparently aren't documented anywhere. The functions we use for Gurobi have these signatures:

```c
int GRBgetnumparams(GRBenv *env);
int GRBgetparamname(GRBenv *env, int i, char **paramnameP);
int GRBgetparamtype(GRBenv *env, const char *paramname);
int GRBgetintparaminfo(GRBenv *env, const char *paramname, int *valueP, int *minP, int *maxP, int *defP);
int GRBgetdblparaminfo(GRBenv *env, const char *paramname, double *valueP, double *minP, double *maxP, double *defP);
int GRBgetstrparaminfo(GRBenv *env, const char *paramname, char *valueP, char *defP);
```

Thanks, I'll make sure I target the `latest` branch.

**Comment by jajhall** [comment]
Thanks, I'll match these methods

**Comment by jajhall** [comment]
The methods are written and sitting in the `option-info` branch. I've written some testing code that's failing in `TestCAPPI.c` for some CI tests with Windows, but I think that's due to my dodgy C programming rather than any errors in the C API or C++ methods that I've added to the Highs class.

It would be good if you could let me know how they are to work with.

**Comment by jajhall** [comment]
The bug exposed on Windows has been fixed, and the `option-info` branch has been merged in to `latest`

**Comment by cyderize** [comment]
Great, I tried the new functions in the `latest` branch and it all works perfectly 👍 

Thanks!

**Comment by jajhall** [comment]
Thanks. We've tried to mimic Gurobi when we needed inspiration - so we could always quote Gurobi if anyone demurred. We picked up on their string-named options (parameters) years ago - but missed the details of the methods you've brought to out attention, so thanks. 🙂
