### ISSUE TITLE
Linker issues after cmake update

### ISSUE THREAD

**Issue by ambros-gleixner** [ERGO-Code/HiGHS#1123]
After 0bf733a73 I cannot link HiGHS to SCIP anymore. In https://github.com/scipopt/scip/blob/lpi-highs/CMakeLists.txt I used to specify my HiGHS build directory (containing highs-config.cmake) as HIGHS_DIR and everything went well.

With this commit I get
```
[  0%] Building CXX object src/CMakeFiles/scip.dir/lpi/lpi_highs.cpp.o
[  0%] Linking CXX executable ../bin/scip
/usr/bin/ld: cannot find -lhighs
collect2: error: ld returned 1 exit status
make[2]: *** [src/CMakeFiles/scip.dir/build.make:5855: bin/scip] Error 1
make[1]: *** [CMakeFiles/Makefile2:2052: src/CMakeFiles/scip.dir/all] Error 2
make: *** [Makefile:163: all] Error 2
```

@galabovaa If I manually change my highs-config.cmake to
```
...
if (NOT FAST_BUILD)
  if(NOT TARGET highs)
    include("${CMAKE_CURRENT_LIST_DIR}/highs-targets.cmake")
  endif()

  set(HIGHS_LIBRARIES libhighs)  <--- changed, was set(HIGHS_LIBRARIES highs)
else()
...
```
then it works.

Can you help to make this work out-of-the-box again?

**Comment by jajhall** [comment]
@galabovaa This sounds as if it's related to changes you made recently.

**Comment by galabovaa** [comment]
@ambros-gleixner this should be fixed in branch latest already and will be merged in master soon.

**Comment by ambros-gleixner** [comment]
I can confirm it works again now, thanks!
