### ISSUE TITLE
assert(numericalTrouble < 1e-3) in HEkkPrimal.cpp:updateVerify()

### ISSUE THREAD

**Issue by ambros-gleixner** [ERGO-Code/HiGHS#1128]
I encountered the above assert in a test with SCIP. In the attached log [lotsize.txt](https://github.com/ERGO-Code/HiGHS/files/10574087/lotsize.txt) I printed some of the values involved:
- numericalTrouble is about 2.9e3 
- alpha_col is about +7e-7
- alpha_row is about -2e-10 (so both have different sign).

I read the code and from what I understand this means something went wrong numerically. At the same time, the situation seems to be taken care of by forcing a rebuild after the assert.

Question: Should this assert really hold strictly, or should it rather be a warning message? In other words, is there a bug and some code beforehand should have prevented HiGHS from reaching this state, or is this a situation that can happen in numerically troublesome cases.

PS: How to reproduce it is basically in the log, but it flies only after about 4000 seconds on my laptop. I have tried to reproduce it with a plain mps file on the command line, but there everything is fine. (Not surprisingly; inside SCIP this is a warm/hot start after removing basic rows from the LP, so even when providing the same starting basis and options, the numerics can be very different.)

**Comment by jajhall** [comment]
This "developer's assert" is now removed in `latest`

**Comment by ambros-gleixner** [comment]
Thanks!
