### ISSUE TITLE
Assertion `!num_primal_correction_skipped' failed in HEkkPrimal.cpp:2103: bool HEkkPrimal::correctPrimal(const bool)

### ISSUE THREAD

**Issue by ambros-gleixner** [ERGO-Code/HiGHS#1130]
Running SCIP with HiGHS in debug mode on https://miplib.zib.de/instance_details_neos-3754480-nidda.html runs into the above assert.

The attached log 
[neos-3754480-nidda.txt](https://github.com/ERGO-Code/HiGHS/files/10608198/neos-3754480-nidda.txt) shows that SCIP initially calls the dual simplex, but then HiGHS seems to use the primal to clean up dual infeasibilities.  It is primal feasible at this point and forbids further bound perturbations.  But somehow after a few pivots some basic variables seem to be outside of the bounds and hence the assert in correctPrimal() must fail.

However, the code after HEkkPrimal.cpp:747 seems to handle this case correctly by switching back to phase 1.  If I remove the asserts
```
diff --git a/src/simplex/HEkkPrimal.cpp b/src/simplex/HEkkPrimal.cpp
index a9ca62492..c9c3f6d99 100644
--- a/src/simplex/HEkkPrimal.cpp
+++ b/src/simplex/HEkkPrimal.cpp
@@ -745,7 +745,6 @@ void HEkkPrimal::rebuild() {
   ekk_instance_.computePrimal();
   if (solve_phase == kSolvePhase2) {
     bool correct_primal_ok = correctPrimal();
-    assert(correct_primal_ok);
   }
   getBasicPrimalInfeasibility();
   if (info.num_primal_infeasibilities > 0) {
@@ -2100,7 +2099,6 @@ bool HEkkPrimal::correctPrimal(const bool initialise) {
     highsLogDev(ekk_instance_.options_->log_options, HighsLogType::kError,
                 "correctPrimal: Missed %d bound shifts\n",
                 num_primal_correction_skipped);
-    assert(!num_primal_correction_skipped);
     return false;
   }
   if (max_primal_correction > 2 * max_max_primal_correction) {
```
then HiGHS continues to conclude infeasibility:
```
HEkkDual:: Using primal simplex to try to clean up num / max / sum = 1 / 1.09346e-07 / 1.09346e-07 dual infeasibilities
Primal feasible and num / max / sum dual infeasibilities of 1 / 1.09346e-07 / 1.09346e-07, so near-optimal
Near-optimal, so don't use bound perturbation
primal-phase2-start
       Iteration        Objective     Infeasibilities num(sum)
PrPh2         53     1.5044662062e+04 Pr: 0(0); Du: 1(1.09346e-07) No reason
       Iteration        Objective
PrPh2         54     1.5044661662e+04
PrPh2         55     1.5044661600e+04
correctPrimal: Missed 2 bound shifts
HEkkPrimal::rebuild switching back to phase 1 from phase 2
       Iteration        Objective     Infeasibilities num(sum)
PrPh1         55     1.5044662774e+04 Ph1: 2(1.04123e-05); Du: 1(9.94938e-07) Possibly optimal
primal-return-phase1
primal-phase1-start
       Iteration        Objective     Infeasibilities num(sum)
PrPh1         55     1.5044662774e+04 Ph1: 2(1.04123e-05); Du: 1(9.94938e-07) No reason
       Iteration        Objective
PrPh1         56     1.5044662774e+04
PrPh1         57     1.5044662774e+04
       Iteration        Objective     Infeasibilities num(sum)
PrPh1         57     1.5047417967e+04 Ph1: 2(4.94011e-06); Du: 0(1.94479e-07) Possibly optimal
Simplex iterations: DuPh2 21; PrPh1 2; PrPh2 2; Total 25
EKK primal simplex solver returns 2 primal and 2 dual infeasibilities: Status Infeasible
```
(But Highs::getDualRay() then returns false and so SCIP cannot check the claim, disregards the result and goes into rescue branching. This is somewhat unfortunate, but okay.)

Any ideas how to avoid this assert?

I am guessing the reason why primal infeasibilities come back: correctPrimal() is called from rebuild() and gdb tells me rebuild_reason = kRebuildReasonForceRefactor.  So maybe the basis just seemed primal feasible before, but primal infeasibilities were hidden and just become visible after a fresh factorization.  This seems like a series of events that generally cannot be avoided.

**Comment by jajhall** [comment]
Again, these are "developer's asserts" to capture instances where the behaviour occurs. I'm loathed to remove them - and there are others - as we don't expect users to compile HiGHS in dubug. Unfortunately SciPy used `RelWithDebInfo` when building HiGHS for release, so ordinary users are tripping one particular developer's assert (in the MIP solver)!

I'll protect them from being triggered by using a const bool - that will add to code clarity

**Comment by jajhall** [comment]
Fixed by #1133 when pushed to `latest`

**Comment by ambros-gleixner** [comment]
I think it's great that you have many of these asserts, this makes the code much more trustworthy! The solution to make them optional with kAllowDeveloperAssert is a good one, also for the future. (You could even consider making it a real runtime parameter?)

I am afraid I may run into more of these as I keep testing with SCIP. I think testing HiGHS directly in optimized mode would rather lead to issues that are actually harder to understand, and so I think this is still the smoothest way to go. Thanks for reacting so fast, I will try to make my reports as helpful as possible.

I have one follow-up question here, though: Why is it that HiGHS does not provide a dual ray to prove the infeasibility claimed?

**Comment by jajhall** [comment]
> I have one follow-up question here, though: Why is it that HiGHS does not provide a dual ray to prove the infeasibility claimed?

Identifying infeasibility in primal simplex is very rare. As you can imagine, it's normally done by identifying dual unboundedness in dual simplex. In dual simplex we have sophisticated code to validate the proof of infeasibility and generate the dual ray. It's just not worth developing the same for primal simplex.

**Comment by ambros-gleixner** [comment]
Okay, so dual rays are never available if infeasibility is found in primal simplex phase. Thanks for the clarification!
