### ISSUE TITLE
On MSVC 15, some headers are missing

### ISSUE THREAD

**Issue by hedtke** [ERGO-Code/HiGHS#1151]
The headers `cctype` and `algorithm` are missing to use `std::tolower` and `std::max`. See the build logs for MSVC 15 here: https://c3i.jfrog.io/c3i/misc/logs/pr/15814/6-configs/windows-visual_studio/highs/1.4.2//606fdb601e335c2001bdf31d478826b644747077-build.txt

**Comment by jajhall** [comment]
Thanks. I've no problem adding the includes, as per your PR. I'm puzzled that this issue hasn't been exposed before. I'm aware that omitting `<algorithm>` when developing code using `std::max` on Linux can lead to problems when compiling on Windows, so maybe your issue is localised.

**Comment by jajhall** [comment]
Merged into `latest`
