### ISSUE TITLE
HiGHS with presolve declares false infeasibility

### ISSUE THREAD

**Issue by jajhall** [ERGO-Code/HiGHS#1164]
HiGHS 1.4 with presolve quickly concludes that [infeasible_2.lp.txt](https://github.com/ERGO-Code/HiGHS/files/10750522/infeasible_2.lp.txt) is infeasible, but Gurobi and CPLEX find a solution in a sec.  

Without presolve, HiGHS easily solves it correctly

**Comment by fwesselm** [comment]
Hello!

I have two observations that I would like to share (see attached diff):

1. There seems to be a typo in HighsMipSolverData::transformNewIncumbent. I think the first call to calculateRowValuesQuad should pass the presolved model, because the presolved solution is passed. But, maybe I am missing something here.

2. calculateRowValuesQuad seems to fail silently quite often (without the change in (1)) because of a size mismatch. I think there should be an assertion for this.

Regards,
Franz



[size_mismatch.txt](https://github.com/ERGO-Code/HiGHS/files/10791917/size_mismatch.txt)

**Comment by jajhall** [comment]
Thanks for this @fwesselm! I'm tempted to have a look, but we're working intensively on documentation this week.

**Comment by tobiass-sdl** [comment]
I have a set of MIP where the HiGHS (MIP) presolver declares infeasibility although I pass in a feasible solution. SCIP also thinks that the problems are feasible.
The problems are rather large (but with many fixed variables). Would it help to have them as additional testing data? If so I would strip all confidential information from the variable/row names and upload the mps here.

**Comment by jajhall** [comment]
Yes, please. It would be useful to have the feasible solution, too. That said, if your problems have non-unique solutions, a particular feasible solution (when reduced) is not necessarily feasible for the presolved model (due to symmetry based reductions)

**Comment by tobiass-sdl** [comment]
Unfortunately I did not write the problem into a file immediately and improved the code that generated the problem in several ways first - at the end I have a optimization problem to solve. Now I can't reproduce the 'infeasible' problem...

**Comment by jajhall** [comment]
> I have two observations that I would like to share (see attached diff):
> 
>     1. There seems to be a typo in HighsMipSolverData::transformNewIncumbent. I think the first call to calculateRowValuesQuad should pass the presolved model, because the presolved solution is passed. But, maybe I am missing something here.
> 
>     2. calculateRowValuesQuad seems to fail silently quite often (without the change in (1)) because of a size mismatch. I think there should be an assertion for this.

I've finally got around to looking at this - as part of investigating some other erroneous behaviour. Yes, you're right the first call to calculateRowValuesQuad should pass the presolved model. However, the error doesn't matter, as the row values that are used are computed in the second call to calculateRowValuesQuad, by which point (as a consequence of postSolveStack.undoPrimal) the size of `solution.col_value` is the same as `mipsolver.orig_model_.num_col_`. What I suspect is that there was an intention to maintain the row values in postSolveStack.undoPrimal. However, very few methods in the postsolve change row values, so I don't believe that the row values are maintained. And (other than for debugging purposes such as the one that's brought me to your comment!) they don't need to be, since they can be computed after postSolveStack.undoPrimal.

That said, you're correct about the silent failure, so I'll incorporate your changes

**Comment by jajhall** [comment]
Closed by #1513, with issue relating to `model_198.lp` being transferred to #1517
