### ISSUE TITLE
writeModel -> readModel -> writeModel leads to different names in LP files

### ISSUE THREAD

**Issue by ambros-gleixner** [ERGO-Code/HiGHS#1186]
If one reads and writes the following file
```
\ File written by HiGHS .lp file handler
max
 obj: +1 x1 +1 x2
st
 con1up: +1 x1 <= +1
 con2up: +1 x2 <= +1
bounds
end
```
using `readModel("example.lp")` and `writeModel("example.lp")` the constraint names change and one gets
```
\ File written by HiGHS .lp file handler
max
 obj: +1 x1 +1 x2
st
 con1upup: +1 x1 <= +1
 con2upup: +1 x2 <= +1
bounds
end
```
We have a unit test that assumes that the result of write and write-read-write is the same.  It is not a big deal if you say this is intended or you do not want to fix it, but I wanted to report it nevertheless.

**Comment by jajhall** [comment]
Interesting observation. I think that we can (and should) make this happen. adding "up" and "dn" to the constraint name is only necessary when splitting a boxed constraint.

**Comment by jajhall** [comment]
I've made the fix, but the the result of write and write-read-write can't always be the same. For
[boxed.lp](https://github.com/ERGO-Code/HiGHS/files/10860989/boxed.lp.txt) `C2` is encountered before `C1`, so the column names are `C2` and `C1`, leading to the constraint being re-written as 

>  R1lo: +1 C2 +1 C1 >= -2
 R1up: +1 C2 +1 C1 <= +1

**Comment by ambros-gleixner** [comment]
Thanks, this fixes it for me!
