### ISSUE TITLE
Parser error on lp file 1443-0-9.lp

### ISSUE THREAD

**Issue by rschwarz** [ERGO-Code/HiGHS#1208]
While running HiGHS on the test suite of [coin-or/python-mip](https://github.com/coin-or/python-mip), I encountered the following error message:

```
Running HiGHS 1.5.1 [date: 2023-03-14, git hash: 45b80e859]
Copyright (c) 2023 HiGHS under MIT licence terms
ERROR:   Parser error reading ../python-mip/test/data/1443_0-9.lp
Error loading file
```

The same problem can be read without problems with SCIP and CPLEX. It's available at [1443_0-9.lp](https://raw.githubusercontent.com/coin-or/python-mip/master/test/data/1443_0-9.lp).

**Comment by jajhall** [comment]
This is because it uses the keyword Ìnteger` rather then `General`

**Comment by jajhall** [comment]
Fixed in `latest`
