### ISSUE TITLE
Improvement on highspy versioning

### ISSUE THREAD

**Issue by sebheger** [ERGO-Code/HiGHS#1210]
I have recognized, that you explicitly code the version into the setup.py

[ version='1.5.0.dev0',](https://github.com/ERGO-Code/HiGHS/blob/ce351010ec7be8b7aae73d847d02669c927c53da/src/interfaces/highspy/setup.py#L30)

1. I would suggest to use git tags as source for versioning
2. Nevertheless, from a best practices point of view it isn't very popular to upload ".dev0" to PyPI. See https://peps.python.org/pep-0440/ - especially the note under section of development release - and https://blog.inedo.com/python/best-practices-for-versioning-python-packages-in-the-enterprise/ - especially the last two best practices. Main issue is, that with the ".dev0" extension ordering of versions is not intuitive and you cannot state something like pip install "highspy>=1.5"

**Comment by jajhall** [comment]
Thanks for the observation. `highspy`is still WIP, and @galabovaa is working on automated builds, so maybe this is how the `.dev0`version has been uploaded.
