### ISSUE TITLE
Wrong optimal solution (compared to glpk)

### ISSUE THREAD

**Issue by yabata** [ERGO-Code/HiGHS#1211]
HiGHS 1.5.0 (highspy==1.5.0.dev0)
GLPK LP/MIP Solver, v4.65

When I solve the problem described in the LP file [model.txt](https://github.com/ERGO-Code/HiGHS/files/10982381/model.txt) with highs and glpk, I get worse results using highs than with glpk
(and from my point of view the results from highs are wrong).

I solve the problem with highspy as follows:
```
import highspy
import numpy as np

# Highs h
h = highspy.Highs()

# Load a model from LPfile model.lp
filename = 'model.txt'
status = h.readModel(filename)
status = h.run()
print( h.getObjectiveValue())
>> 1487475.993777095
```

And GLPK from the terminal:
```
glpsol --lp model.txt
>>...
>>Long-step dual simplex will be used
>>+   549: mip =     not found yet >=              -inf        (1; 0)
>>+   559: >>>>>   1.425619964e+06 >=   1.425619964e+06 < 0.1% (8; 1)
>>+   559: mip =   1.425619964e+06 >=     tree is empty   0.0% (0; 17)
>>INTEGER OPTIMAL SOLUTION FOUND
>>Time used:   0.1 secs
>>Memory used: 3.9 Mb (4048345 bytes)
```

The difference in the results of the objective is higher than 4%!

- HIGHS: 1487475.994
- GLPK:  1425619.964

Also when I look at the results, the results from GLPK are what I would expect!

**Comment by jajhall** [comment]
Gurobi gives the same optimal objective (1.487475993777e+06) as HiGHS so, despite the results from GLPK being what you would expect, it looks as if HiGHS is getting the optimal solution, and that GLPK is not.

Have you checked that the solution from GLPK is feasible?

I've run GLPK on your model, and there are some large optimal values for variables and constraint actives. I wonder whether GLPK has solved a scaled version of the problem and, after unscaling it violates variable/constraint bounds by more than the specified tolerance.

I don't believe that there is any issue with HiGHS for this model
