### ISSUE TITLE
Request to explain logging options

### ISSUE THREAD

**Issue by NPC** [ERGO-Code/HiGHS#1215]
For context, my task: HiGHS DLL is called from C# code which builds the input problem, calls the solver, and then records the solution. This calling code creates a log file which is often used for investigations. It would be helpful to include the information usually written to `Highs.log` in this “calling process” log file, at the point when the HiGHS is called. Having `Highs.log` as a separate file is unwieldy for a number of reasons. It is something I can live with, but I wonder if any of the “log” options can help in my situation.

The things I've tried so far:
* **log_file** — set to the same file as the calling process log. This, predictably, overwrites it with Highs.log content, instead of appending.
  * If there could be an option to “append” it would help, as long as the file is immediately released for subsequent writing by the calling process. But this could get messy.
* **output_flag**=0 seems to do the same thing as log_file="", simply disables writing to Highs.log.
* **log_to_console**=1 outputs the log to the console, but for the DLL called from C# this is not affected by Console.SetOut, so I can't (seem to) redirect HiGHS console output to an already opened file stream. This is possibly the closest option to what I need, but I feel that it's not in your control how the DLL's console is called from C# (please correct me if wrong).
* **log_file_stream** — this sounds relevant, but I can't figure out how to use it from C#, where I'm only allowed to pass string (and bool/int) values to HiGHS options.
* Also, I did try looking into log callbacks, potentially a very powerful feature, but from my experiments and the discussion in #708 I understand that it may not be usable from C# yet.

**Comment by jajhall** [comment]
It's possible that the logging control in the C# interface has not been updated since we switched logging control to follow Gurobi. That said, I've just spotted that `gurobi.log`is appended from one run to the next, so I'll modify HiGHS so that it does that, too

**Comment by jajhall** [comment]
In branch [fix-1215](https://github.com/ERGO-Code/HiGHS/tree/fix-1215) HiGHS now appends to any existing log file of desired name

**Comment by NPC** [comment]
@jajhall that's awesome, thank you!

I'll test it on release (when the binaries come out). My main concern with this is whether the target file will be released immediately for subsequent logic to be able to write to it immediately after HiGHS returns the solution.

PS Though documenting the options that I mentioned… and any others I didn't… may still be a good idea.

**Comment by jajhall** [comment]
The log callback facility only exists for the C++ API. I wouldn't know how to write the necessary C interface to it.

**Comment by NPC** [comment]
> The log callback facility only exists for the C++ API. I wouldn't know how to write the necessary C interface to it, so it's a long way off the C++ API

Well, the error I got when I tried to add a wrapper (which can be all kinds of wrong too) was: `System.EntryPointNotFoundException: Unable to find an entry point named 'Highs_setLogCallback' in DLL 'libhighs'`. So it looked like the DLL didn't expose the necessary method to even try. Whether that's a compilation option of something else I don't know, sorry.

And I don't know if exposing this method will allow me to properly use it from C#, so it may be a shot in the dark anyway, sigh.

**Comment by jajhall** [comment]
To "explain" the logging options, have a look at [options/definitions/#output_flag](https://ergo-code.github.io/HiGHS/dev/options/definitions/#output_flag).

**Comment by jajhall** [comment]
Note that "console" means `stdout`, as this is currently hard coded in the two methods used to generate logging messages.

**Comment by jajhall** [comment]
in [highs_csharp_api.cs](https://github.com/ERGO-Code/HiGHS/blob/latest/src/interfaces/highs_csharp_api.cs) there is no mention of any of the deprecated methods of controlling logging. All that's possible is to set option values using `Highs_setOptionValue`

**Comment by jajhall** [comment]
For C#, there's nothing else I can do at this point. Once the C API can pass a used logging callback, then someone who knows C# can write a call to it. 

As we work on callbacks properly, this will happen to the best of our ability.
