### ISSUE TITLE
How can I disable the HSimplexReport `Iteration total error` output?

### ISSUE THREAD

**Issue by Thell** [ERGO-Code/HiGHS#1257]
I currently have `output_flag` and `log_to_console` disabled but have 10s of thousands of these iteration messages being calculated and emitted to the console. The only spot I could find in the source matching the message is a `printf` call here...

https://github.com/ERGO-Code/HiGHS/blob/9bd630d7bda98f7b0113071fda732c32dbbc3bd8/src/simplex/HSimplexReport.cpp#L57

The first line of that `HSimplexReport` is

https://github.com/ERGO-Code/HiGHS/blob/9bd630d7bda98f7b0113071fda732c32dbbc3bd8/src/simplex/HSimplexReport.cpp#L25

and looks to be set here:

https://github.com/ERGO-Code/HiGHS/blob/d85660e3baaf2361db16c686cf6505e70829f724/src/simplex/SimplexStruct.h#L184

but is commented with

`// Internal options - can't be changed externally`

so.... 🤷

**Comment by jajhall** [comment]
Sorry about this 

Clearly you can delete the line if building from source. Otherwise I'll modify master and it'll appear in the next release

**Comment by jajhall** [comment]
Fixed by push to `master` (and `latest`)

**Comment by jajhall** [comment]
The iteration error messages were due to the use of  `static`, so almost inevitable when using multi-threaded HiGHS instances. Now non-static

**Comment by Thell** [comment]
Thank you! That made the output much cleaner!

**Comment by jajhall** [comment]
You're welcome, the spurious errors with multi threading were something I'd been meaning to fix for a while.

I guess you've not seen any other indication that HiGHS isn't thread safe.

**Comment by Thell** [comment]
No, not in Linux. When I tried on Windows using the `rust-or/highs-sys` crate the parallel tests hang and don't terminate. I opened a ticket https://github.com/rust-or/highs-sys/issues/9 and haven't heard back. I also wasn't able to find much for HiGHS and parallel on Windows via searching but after the headache of Coin-OR on Windows in parallel I didn't want to mess with it now.

As it stands though, on Linux it is working in parallel without any issues except being twice as slow as Python + OR-Tools with CBC backend. Literally, it takes twice as long. I really was expecting the combination of Rust and HiGHS to give a performance boost.

```
Benchmark 1: ORTools-CBC
  Time (mean ± σ):     12.473 s ±  0.513 s    [User: 186.529 s, System: 1.717 s]
  Range (min … max):   12.082 s … 14.405 s    20 runs

Benchmark 2: Rust-HiGHS
  Time (mean ± σ):     23.065 s ±  0.273 s    [User: 364.570 s, System: 0.435 s]
  Range (min … max):   22.618 s … 23.472 s    20 runs

Summary
  'ORTools-CBC' ran
    1.85 ± 0.08 times faster than 'Rust-HiGHS'
```

**Comment by jajhall** [comment]
Strange that Cbc is faster. Generally HiGHS is very much faster.

We've got a hanging issue on Widows 

 be related to

**Comment by Thell** [comment]
Well, well, welllll... what d'ya know?

```rust
        let option_name = CString::new("threads").unwrap();
        Highs_setIntOptionValue(highs, option_name.as_ptr(), 1);
```

and the parallel tests completed successfully on windows. Thanks for that @jajhall; that should resolve https://github.com/rust-or/highs-sys/issues/9 👍 

As for the speed, yes, very strange. I'm still investigating the 'why' of it.

**Comment by Thell** [comment]
Hah! :happy-dance: you might not have known what you had just done but **that** was the ticket to fixing the performance issues I was seeing too! **Fantastic!**

```sh
time target/release/highs-test --solve -j 16
good_count: 6977
real    0m6.179s
user    1m31.641s
sys     0m0.080s
```

That is _much_ more like what I was expecting. Now... _why_ the default is `0` I don't know but knowing to set it to `1` will keep me smiling for weeks. :)

**Comment by jajhall** [comment]
The default is set to `0` to prompt HiGHS to use half the number of threads available on the machine. Setting it to `1` will force HiGHS to run single-threaded. My thought is to set the default value to `4` or `8` and for `HiGHS` to trim it to half the number of available threads. Although this means that HiGHS may over-rule a user preference, it's likely to perform better, as it won't make good use of all threads, for example.

**Comment by Thell** [comment]
The default of `0` makes sense to flag automatic assignment and I suppose multi-threaded use on a single problem is more common than multi-threaded for a pool of workers using multiple problems. Perhaps a simple notation in the documentation of the "threads" option is really all that is needed. Perhaps something along the lines of

> Number of threads used by HiGHS  for a single solver, set to a positive value for concurrent solvers (0: automatic)
[Info threads entry](https://ergo-code.github.io/HiGHS/dev/options/definitions/#threads)

and then on the [Parallel](https://ergo-code.github.io/HiGHS/dev/parallel/) page

> By default, when running in parallel, HiGHS will use half the available threads on a machine. This number can be modified by setting the value of the [threads](https://ergo-code.github.io/HiGHS/dev/options/definitions/#threads) option. When running multiple concurrent solvers the threads option should be set to a positive value to improve performance and system stability.

If I had read that when I first started setting up my modelling with HiGHS it definitely would have saved time.

**Comment by Thell** [comment]
Don't give the time loss another moments thought, documentation isn't easy even when there is a fully staffed and well paid group trying to accomplish it. :)

> And what positive value is OK?

That's the crux of the matter isn't it? I suppose that if the default was half the cores available then it'd at least work and at least be performant. Then, users, like me, who are trying to squeeze whatever performance they can out of their implementation would see the resource monitor and think it is bound to physical cores instead of logical cores and immediately search for a setting to control that. _But it'd be working; which is a good thing._

For many solvers running concurrently `1` will be my default (in Linux or Windows) considering that performance increase. I mean, seriously, from 23s to 6s... I can't wait to finish my implementation of the model in HiGHS to test with my larger sets.

**Comment by odow** [comment]
> Unfortunately, if we stick with 0 as the default, HiGHS will continue to hang on Windows for ordinary punters, and they'll just assume it doesn't work, rather than seeking out understanding that they need to set threads to a positive value

Ah! We can set this by default on the Julia side
