### ISSUE TITLE
Building HiGHS for static linking in Debug mode

### ISSUE THREAD

**Issue by JacintaDFerreira** [ERGO-Code/HiGHS#1260]
I have built HiGHS from source using
```
cmake -DFAST_BUILD=OFF -D BUILD_SHARED_LIBS=OFF -D CMAKE_BUILD_TYPE=Debug -DSHARED=OFF ..
cmake --build . --config Debug 
```

I tried to run the C++ example in Visual Studio, but I get the following error in the highs.lib file:

`mismatch detected for '_ITERATOR_DEBUG_LEVEL': value '0' doesn't match value '2' in Source.obj`

I had no problems in Release mode. Am I missing something?

**Comment by jajhall** [comment]
I'm pretty certain that this is an example of #1129. 

It is fixed in https://github.com/ERGO-Code/HiGHS/tree/latest and will propagate to the next version
