### ISSUE TITLE
Build on Raspberry Pi

### ISSUE THREAD

**Issue by MikeSteglich** [ERGO-Code/HiGHS#1266]
When I try to build Highs on Raspi:

```
PRETTY_NAME="Raspbian GNU/Linux 11 (bullseye)"
NAME="Raspbian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"
```
it fails with an undefined reference to `__atomic_load_8':

e.g.:
```

/usr/bin/ld: ../lib/arm-linux-gnueabihf/libhighs.a(Highs.cpp.o): in function `HighsSplitDeque::WorkerBunk::pushSleeper(HighsSplitDeque*)':
Highs.cpp:(.text._ZN15HighsSplitDeque10WorkerBunk11pushSleeperEPS_[_ZN15HighsSplitDeque10WorkerBunk11pushSleeperEPS_]+0x18): undefined reference to `__atomic_load_8'

```

**Comment by jajhall** [comment]
I've no idea what this refers to and TBH, we can't support all possible architectures, so this has to rule out Raspi for now

**Comment by odow** [comment]
What version of the pi? You can find precompiled binaries for a range of platforms here: https://github.com/JuliaBinaryWrappers/HiGHS_jll.jl/releases/tag/HiGHS-v1.5.1%2B0

You probably want the [HiGHS.v1.5.1.aarch64-linux-gnu-cxx11.tar.gz](https://github.com/JuliaBinaryWrappers/HiGHS_jll.jl/releases/download/HiGHS-v1.5.1%2B0/HiGHS.v1.5.1.aarch64-linux-gnu-cxx11.tar.gz)

**Comment by MikeSteglich** [comment]
I was able to build it by adding a new line with `target_link_libraries(libhighs atomic)` into `CMakeList.txt`.

**Comment by mckib2** [comment]
This is the same issue as https://github.com/ERGO-Code/HiGHS/issues/1110
