### ISSUE TITLE
Does it support adding plugins to highs

### ISSUE THREAD

**Issue by xtjjyygy** [ERGO-Code/HiGHS#1276]
Highs is a high-performance solver, but it seems that Highs does not support adding plugins written by users, for example, I want to add branching rules. I would like to inquire if you have any plans to develop this plugin, which we can use the includeBranchrule to add users branching plugins and so on, If so, when can users use it? Thank you very much!

**Comment by odow** [comment]
HiGHS does not currently support callbacks. See https://github.com/ERGO-Code/HiGHS/issues/781

**Comment by jajhall** [comment]
We will be adding callbacks to the MIP solver in the medium term, and will consider having one for branching rules

**Comment by xtjjyygy** [comment]
Thank you for your reply. Could you please provide an approximate completion time? In addition to branching, are there any plans to support plugins such as node select, separate, propagator, and so on? Thank you again!

**Comment by jajhall** [comment]
Some simple callbacks are needed by the end of the year, but it's possible that what you're asking for will never be added

**Comment by xtjjyygy** [comment]
I get it， Thank you!
