### ISSUE TITLE
Running with --time_limit exit with error code when timeouts

### ISSUE THREAD

**Issue by madeken** [ERGO-Code/HiGHS#1279]
When running:
`> highs file.lp --time_limit 5`

When the timeout is hit, it exits with an error code

```
> echo $?
1
```

This behavior is unique amongst solvers (AFAICT) and would be nice to not have to special case HiGHS for this. Other solvers exit with no error, and in the solution file you can see the timeout limit was exceeded.

**Comment by jajhall** [comment]
A value of 1 (`kHighsStatusWarning` - see https://github.com/ERGO-Code/HiGHS/blob/master/src/interfaces/highs_c_api.h) warns the user that the problem has not been solved, although no error has ocurred.

We will add a comment to the documentation on running HiGHS from the command line
