### ISSUE TITLE
HIGHS errors on metabolic modeling QP

### ISSUE THREAD

**Issue by cdiener** [ERGO-Code/HiGHS#1285]
Hi,

The attached QP problem will lead HIGHS to terminate with an unspecified error. The optimal objective is `4*0.437^2` and it seems like the QP solver is somewhat off here. 

```
In [1]: import highspy as hs

In [2]: h = hs.Highs()

In [3]: h.readModel("/home/cdiener/scribble/micom_test.lp")
Running HiGHS 1.5.0 [date: 2023-05-09, git hash: d4809eae7]
Copyright (c) 2022 HiGHS under MIT licence terms
Out[3]: <HighsStatus.kOk: 0>

In [4]: h.setOptionValue("simplex_iteration_limit", 100)
Out[4]: <HighsStatus.kOk: 0>

In [5]: h.setOptionValue("ipm_iteration_limit", 100)
Out[5]: <HighsStatus.kOk: 0>

In [6]: h.run()
[...]
3396000, 0.815120, 3, 125.292524, 0.000000, 60, 0.000000, 1.000000
3397000, 0.815120, 3, 125.325373, 0.000000, 60, 0.000000, 1.000000
3398000, 0.815120, 3, 125.357455, 0.000000, 60, 0.000000, 1.000000
3399000, 0.815120, 3, 125.390469, 0.000000, 60, 0.000000, 1.000000
3400000, 1.112215, 1, 125.422946, 0.000000, 58, 0.000000, 1.000000
Model   status      : Not Set
HiGHS run time      :        125.44
Out[6]: <HighsStatus.kError: -1>
```

Scaling the objective coefficients will somewhat improve the guess, but will run quite long and always crash after a while. It also seems to ignore all iteration limit options.

CPLEX, Gurobi and OSQP will solve the problem just fine from the same file.

[micom_test.lp.gz](https://github.com/ERGO-Code/HiGHS/files/11436721/micom_test.lp.gz)

**Comment by cdiener** [comment]
It would also be helpful to know what the log output from the QP solver means. There are no column headers or mention in the docs. I assume the first two columns are the iteration and objective.

**Comment by feldmeier** [comment]
Thanks for providing the instance file, I'll take a look!

I will add column headers for the QP solver log output in a new commit to latest. The columns are: iteration, objective value, dimension of the nullspace (major factor in how long an iteration is taking to compute), runtime, sum of primal infeasibilities, number of primal infeasibilities, density of the nullspace matrix, density of the reduced cholesky factor.

Some of them are probably of little interest to the user so I will hide a few of them.

**Comment by cdiener** [comment]
Awesome, thanks so much. Also attaching the CPLEX run for reference:

```
CPLEX> read "/home/cdiener/scribble/micom_test.lp"
Problem '/home/cdiener/scribble/micom_test.lp' read.
Read time = 0.02 sec. (0.09 ticks)
CPLEX> opt
Version identifier: 20.1.0.0 | 2020-11-10 | 9bedb6d68
Tried aggregator 1 time.
QP Presolve eliminated 58 rows and 465 columns.
Aggregator did 108 substitutions.
Reduced QP has 147 rows, 228 columns, and 928 nonzeros.
Reduced QP objective Q matrix has 4 nonzeros.
Presolve time = 0.00 sec. (0.52 ticks)
Parallel mode: using up to 8 threads for barrier.
Number of nonzeros in lower triangle of A*A' = 1260
Using Approximate Minimum Degree ordering
Total time for automatic ordering = 0.00 sec. (0.09 ticks)
Summary statistics for Cholesky factor:
  Threads                   = 8
  Rows in Factor            = 147
  Integer space required    = 443
  Total non-zeros in factor = 2548
  Total FP ops to factor    = 53962
 Itn      Primal Obj        Dual Obj  Prim Inf Upper Inf  Dual Inf          
   0   3.5480514e+06  -3.8109821e+06  1.48e+05  1.74e+05  7.55e+03
   1   3.7561637e+05  -4.8557933e+05  4.90e+04  5.79e+04  2.50e+03
   2   4.3016648e+03  -4.0306505e+04  6.69e+03  7.91e+03  3.42e+02
   3   3.4974324e+03  -3.5993032e+04  5.11e+03  6.04e+03  2.61e+02
   4   2.8521814e+02  -1.8479836e+04  1.69e+03  1.96e+03  8.43e+01
   5   6.6254818e+01  -1.0377954e+04  7.64e+02  8.88e+02  3.82e+01
   6   2.7411413e+01  -7.2553916e+03  4.61e+02  5.35e+02  2.30e+01
   7   1.4537038e+00  -2.0092307e+03  3.38e+01  3.93e+01  1.69e+00
   8   7.8618818e-01  -2.6081057e+01  1.76e-01  2.05e-01  8.81e-03
   9   7.7933221e-01   4.1591029e-01  2.01e-03  2.33e-03  1.00e-04
  10   7.6413097e-01   7.6139410e-01  1.07e-05  1.24e-05  5.35e-07
  11   7.6387727e-01   7.6385789e-01  1.07e-07  6.16e-08  2.65e-09
  12   7.6387601e-01   7.6387587e-01  5.06e-08  3.05e-10  1.31e-11
  13   7.6387600e-01   7.6387600e-01  4.42e-08  6.37e-12  6.39e-14
Barrier time = 0.03 sec. (1.73 ticks)

Total time on 8 threads = 0.03 sec. (1.73 ticks)

Barrier - Optimal:  Objective =  7.6387600003e-01
Solution time =    0.04 sec.  Iterations = 13
Deterministic time = 1.73 ticks  (47.27 ticks/sec)
```

**Comment by feldmeier** [comment]
Thanks!
While I can't replicate the exact same issue on the latest branch on my current development setup on windows, I do get another issue on your instance. The instance is semidefinite (4 diagonal entries in the Hessian). The solver attempts to grow the nullspace beyond 4 dimensions due to a bug. I'll debug and try to find a bugfix tomorrow.

**Comment by cdiener** [comment]
Okay, best of luck. Weird that's it's not reproducible since I used the same version I think (the code from my first post shows the git hash). Happy to try with another branch if you point me to one.

**Comment by feldmeier** [comment]
Disabling regularization seems to fix this issue. Back in the day I added regularzation as a way of handling the semidefinite case. By now, semidefiniteness is handled algorithmically (but still new so likely buggy), so regularization is not necessary (it might still be for badly conditioned instances).

I'll see if this fix breaks anything, and if no, will create a pull request later.

**Comment by cdiener** [comment]
Awesome thanks! I also noted that it reads the zero entries explicitly when parsing the LP file. Like it says the Hessian has 801 entries on the diagonal even though all but 4 are zero.

**Comment by cdiener** [comment]
Working great now, thanks so much!

**Comment by feldmeier** [comment]
Good to hear! Let me know if you have any other feedback/issues with QPs in HiGHS.

**Comment by cdiener** [comment]
Will do, thanks!
