### ISSUE TITLE
Presolve bugs using "netlib" dataset

### ISSUE THREAD

**Issue by sschnug** [ERGO-Code/HiGHS#13]
While doing some first-hour experiments with this project (very interesting; especially the license!), the following was observed:

    sascha@sascha-VirtualBox:~/Downloads/HiGHS/build/bin$ ./highs -p On -f ~/Downloads/greenbea.mps
    Presolve is set to On
    Reading file /home/sascha/Downloads/greenbea.mps
    Setting default value crashMode = Off
    Setting default value edWtMode = DSE1
    ====================================================================================
    Running HiGHS
    ------
    terminate called after throwing an instance of 'std::out_of_range'
      what():  vector::_M_range_check: __n (which is 18446744073709551615) >= this->size() (which is 30877)
    Error during presolve: no variable found in singleton row 281.Aborted (core dumped)

It seems presolve is a relatively new addition and maybe bugs are to be expected. While probably not much relevant, i'm using a Linux + GCC + OpenMP=0 setup here and the exact mps-file in use can be obtained from [this link](http://www.zib.de/koch/perplex/data/netlib/mps/greenbea.mps.gz) (gz compressed).

Sascha

**-----------**
**UPDATE**
**-----------**
I wrote a small testing-script (available [here](https://github.com/sschnug/HiGHS_basic_tests)).

Using above setup against the whole netlib-dataset (as described in the link above; README describes setup), there are:

- **2 crashes in presolve**
- **1 timeout (with presolve on only)** (with 30 seconds; should be more than enough according to the citation mentioned in README)

Output of the script (2 configs: default vs. default + presolve with 94 netlib instances each):

    sascha@sascha-VirtualBox:~/Documents/HiGHS_eval$ python3 run.py
    ----------------
    Run all 188 tests...
    run 1/188
    run 2/188
    ... (omitted in example)
    run 188/188
        ...all tests finished!
    -------------------
    Check for errors...
    Observed error:
        Instance: /home/sascha/Documents/HiGHS_eval/netlib/greenbea.mps
        Arguments: ['-p', 'On']
        Error-type: SOLVER ERROR
        -> returncode: -6
        -> stdout:
     
            Presolve is set to On
            Reading file /home/sascha/Documents/HiGHS_eval/netlib/greenbea.mps
            Setting default value crashMode = Off
            Setting default value edWtMode = DSE1
            ====================================================================================
            Running HiGHS
            ------
            Error during presolve: no variable found in singleton row 281.
     
        -> stderr:
     
            terminate called after throwing an instance of 'std::out_of_range'
              what():  vector::_M_range_check: __n (which is 18446744073709551615) >= this->size() (which is 30877)
     
     
    Observed error:
        Instance: /home/sascha/Documents/HiGHS_eval/netlib/cycle.mps
        Arguments: ['-p', 'On']
        Error-type: TIMEOUT
        -> returncode: -999
        -> stdout:
     
     
     
        -> stderr:
     
     
     
    Observed error:
        Instance: /home/sascha/Documents/HiGHS_eval/netlib/greenbeb.mps
        Arguments: ['-p', 'On']
        Error-type: SOLVER ERROR
        -> returncode: -6
        -> stdout:
     
            Presolve is set to On
            Reading file /home/sascha/Documents/HiGHS_eval/netlib/greenbeb.mps
            Setting default value crashMode = Off
            Setting default value edWtMode = DSE1
            ====================================================================================
            Running HiGHS
            ------
            Error during presolve: no variable found in singleton row 281.
     
        -> stderr:
     
            terminate called after throwing an instance of 'std::out_of_range'
              what():  vector::_M_range_check: __n (which is 18446744073709551615) >= this->size() (which is 30877)
     
     
        ...all checks finished!

**Comment by galabovaa** [comment]
Thank you for the info Sasha, we will look into it. Presolve is a newer feature, yes, but it still should be able to handle greenbea and greenbeb and a previous version of presolve did so. We extended the list of presolve rules so that must have changed something. Cycle I had not tested on so I will check that too when I get a chance.

**Comment by mattmilten** [comment]
We should add all those instances to `check/CMakeLists.txt` to test them with TravisCI.

**Comment by galabovaa** [comment]
The bug is now fixed. Both problems are in check/instances and presolve is on in ctest too.
