### ISSUE TITLE
Include errors updating to 1.5.3

### ISSUE THREAD

**Issue by Dekker1** [ERGO-Code/HiGHS#1308]
I'm trying to update the version of HiGHS used in MiniZinc to version `1.5.3`. However, I'm running into the issue that the include path of the exported CMake configuration has changed.

This leads to `Highs.h` no longer being found when adding `${HIGHS_INCLUDE_DIRS}` to the target include path.

I then tried changing our source to use `highs/Highs.h`. This works, but then later runs into an inclusion issue within the Highs headers:

```
[build] /MiniZinc/libminizinc/vendor/highs/lib/cmake/highs/../../../include/highs/lp_data/HighsLpUtils.h:19:10: fatal error: 'lp_data/HConst.h' file not found
[build] #include "lp_data/HConst.h"
[build]          ^~~~~~~~~~~~~~~~~~
[build] 1 error generated.
```

Note that we are using
```
target_include_directories(my_target PRIVATE ${HIGHS_INCLUDE_DIRS})
target_link_libraries(my_target ${HIGHS_LIBRARIES})
```

Note that I also tried using
```
target_link_libraries(mzn highs::highs)
```
This has the same issue, and does not set any include targets. (I think normally the idea is to automatically set the include as well when you link to these types of targets).

**Comment by odow** [comment]
I ran into this yesterday and needed to set a couple of flags in the MiniZinc build: https://github.com/JuliaPackaging/Yggdrasil/pull/6807

I didn't look into the details for a better fix.

(@Dekker1 we're interfacing MiniZinc in Julia: https://github.com/jump-dev/MiniZinc.jl. This lets people solve constraint programs from JuMP: https://github.com/jump-dev/MiniZinc.jl/tree/master#use-with-jump.)

**Comment by Dekker1** [comment]
You seem to solve the problem there by manually adding the include directory that was previously declared the `${HIGHS_INCLUDE_DIRS}` by the exported CMake package. I don't think this is purely a MiniZinc problem, as I believe the same problem would occur with any CMake pacakge using the HiGHS dependency.

I also see you added the `FAST_BUILD` flag, but I don't really know what this does, or if this is something I should consider adding to my build for the MiniZinc dependencies.

**Comment by odow** [comment]
Yeah it's likely something that could be fixed here. I didn't dig into the details.

The `FAST_BUILD` is only needed because that's what we compile HiGHS with. 

It was causing a mismatch here:
https://github.com/ERGO-Code/HiGHS/blob/45a127b78060942721f75f46a04b274c2bb963d8/highs-config.cmake.in#L5-L17
because `HIGHS_LIBRARIES` is either `highs` or `libhighs` depending on `FAST_BUILD`.
