### ISSUE TITLE
log callback changed in 1.5.3 bugfix release

### ISSUE THREAD

**Issue by svigerske** [ERGO-Code/HiGHS#1309]
Release [1.5.3](https://github.com/ERGO-Code/HiGHS/releases/tag/v1.5.3) (with release notes "Bug fixes and build system") changed the behavior of the log callback.

Highs::setLogCallback takes a data pointer that shall be passed on to the log callback as second argument.
With https://github.com/ERGO-Code/HiGHS/commit/e002eca1b7412be40cc0222f5ad63ca6319724f6#diff-248f5a530d33e1092a792c81a84a490e61dbfb1154781ead64dbfb111a612e58, this argument is not passed on to the log callback anymore.

1. How is this change in behavior a bugfix?
2. How am I supposed to pass on data to my log callback now or in the future?

**Comment by jajhall** [comment]
Fixed via #1310
