### ISSUE TITLE
Update CMakelists.txt for C Example

### ISSUE THREAD

**Issue by ccwutw** [ERGO-Code/HiGHS#1312]
Dear HiGHS Developer Team,

I am writing to submit a change of Cmake files for C Example.
I revised the root Cmake file to include a function for c files and updated the Cmake file in the example folder.
Hope this change met your policies.
I look forward to hearing from you.

Cheers,
Cheng

**Comment by jajhall** [comment]
Thanks: this is fixed by #1313
