### ISSUE TITLE
Incorrect condition in `updateScatterData`

### ISSUE THREAD

**Issue by rdeits** [ERGO-Code/HiGHS#1315]
GCC caught an issue here with `-Werror=logical-op`:

https://github.com/ERGO-Code/HiGHS/blob/45a127b78060942721f75f46a04b274c2bb963d8/src/util/HighsUtils.cpp#L903

The warning from gcc is `logical 'or' of equal expressions`, but I suspect the code should actually be:

```
if (value0 <= 0 || value1 <= 0) return false;
```

**Comment by jajhall** [comment]
Yes, this is an error in unused code that I'll fix

**Comment by jajhall** [comment]
Fixed by 8fbb1e282e6874f3529e4f3f133799972c171efc
