### ISSUE TITLE
Confusing with the swap row duals in detectParallelRowsAndCols

### ISSUE THREAD

**Issue by xtjjyygy** [ERGO-Code/HiGHS#1317]
Learning from your open-source code is an honor, but I am a litter bit confused with the code in "src/presolve/HPresolve.cpp, line 6019", simply swapping the bounds on the row duals is meaningful? can you give me some theoretical information, regarding this part of the code? Looking forward to your reply, thanks!

**Comment by jajhall** [comment]
I've not studied this part of presolve in detail, but the code will be correct

Note that this is not an issue
