### ISSUE TITLE
BIND: Move python bindings and switch build systems

### ISSUE THREAD

**Issue by HaoZeke** [ERGO-Code/HiGHS#1321]
## Move away from `setup.py`

- A lot of issues (including the `pyomo` dep!) come from being unable to bundle `highs` the library with the bindings
- With `meson` as a build system this would be trivial (and it implements more robust library finding methods than the `find_library` stuff in `setup.py` or `pyomo` 

Personally (more divisively) I would prefer to have `meson` as a build system and then have the bindings in a different repository altogether, this approach has worked well for me (as a toy example there is https://github.com/TheochemUI/potlib and the bindings in https://github.com/TheochemUI/pypotlib)

Another reason to have a separation between binding code and the main library is that the issues pertaining to builds (especially for bindings) and general memory issues need not be relevant to the core library (and algorithm developers).

**Comment by jajhall** [comment]
Closed by #1343
