### ISSUE TITLE
Does the pip install still include pyomo?

### ISSUE THREAD

**Issue by jckantor** [ERGO-Code/HiGHS#1323]
The code on this page ... https://mobook.github.io/MO-book/notebooks/07/fleet-assignment.html ... had been previously tested and run successfully on Google Colab.  It's no longer working because the pyomo package is no longer found when attempting to import. You can reproduce the  problem by opening

https://colab.research.google.com/github/mobook/MO-book/blob/main/notebooks/07/fleet-assignment.ipynb

Is there a fix or workaround that would allow us to continue using HIGHS for our project?

Jeff Kantor

**Comment by jajhall** [comment]
Sorry, we're in the process of eliminating the pyomo dependency.

**Comment by rschwarz** [comment]
You should be able to just install `pyomo` directly, instead of implicitly via `highspy`, right?

**Comment by jckantor** [comment]
Yes, we can do that.  

My colleagues and I have used HiGHS quite extensively in a book manuscript and companion website https://mobook.github.io/MO-book/intro.html.  One of our goals was to make our materials as accessible as possible, and for that reason designed the notebooks to open and run in Google Colab. It was helpful to have the HiGHS installer also include Pyomo.  We will need to modify our notebooks to explicitly install Pyomo, which is probably better form anyways.

Thanks for the quick response.

Jeff

**Comment by jajhall** [comment]
Ah, now I understand. `highspy` only imported pyomo for a couple of utilities, and now we've found an alternative source of these we didn't need pyomo. Sorry we don't have release notes to account for all such changes, but we're just a two-person team.
