### ISSUE TITLE
HIGHS_LIBRARIES should be set to highs, not libhighs

### ISSUE THREAD

**Issue by yurivict** [ERGO-Code/HiGHS#1329]
[This](https://github.com/ERGO-Code/HiGHS/blob/master/highs-config.cmake.in#L16) line should be:
> set(HIGHS_LIBRARIES highs)

Otherwise, MiniZinc fails to link because it tries to use ```-llibhighs``` as a link flag.

**Comment by galabovaa** [comment]
That is correct, thank you, we will fix it

**Comment by galabovaa** [comment]
Actually, with 1.5.3 this line should not be reached since FAST_BUILD is on by default. This block is an attempt to transition gradually from the legacy FAST_BUILD off config.

Could you please give more details about the build setting in which you get the error? And what code is used to include HiGHS?

**Comment by yurivict** [comment]
This is the build w/in the FreeBSD ports framework.
We don't set FAST_BUILD.
MiniZinc uses ```-llibhighs``` which breaks it.

**Comment by galabovaa** [comment]
HiGHS 1.5.3 uses FAST_BUILD on by default. FAST_BUILD off will be kept for legacy for a while. Would you try using 1.5.3 or setting FAST_BUILD=ON to confirm it still breaks? 

We are aware of a MiniZinc issue relating to this and are working on a fix.

**Comment by yurivict** [comment]
This problem exists in 1.5.3

You are talking about ```FAST_BUILD``` being set to OFF during the highs build.
But when other projects source high's cmake scripts - ```FAST_BUILD``` remains undefined. This is when the problem occurs.

**Comment by odow** [comment]
See https://github.com/ERGO-Code/HiGHS/issues/1308#issuecomment-1566384941

**Comment by matbesancon** [comment]
https://github.com/ERGO-Code/HiGHS/blob/latest/highs-config.cmake.in
Fixed on latest by https://github.com/ERGO-Code/HiGHS/pull/1483
