### ISSUE TITLE
Command line output when using HiGHS as a library

### ISSUE THREAD

**Issue by Dekker1** [ERGO-Code/HiGHS#1344]
I recently bumped into an issue that HiGHS outputs information to `std::cout` when it is used (by MiniZinc) as a library. This interferes with our other tools that in certain mode expect all output on `std::cout` to be in JSON format.

In this case it turned out to be the code here: https://github.com/ERGO-Code/HiGHS/blob/master/src/simplex/HEkkPrimal.cpp#L115C12-L126, but I wonder whether there should be a more general look at the usage of print statements in HiGHS: e.g., https://github.com/search?q=repo%3AERGO-Code%2FHiGHS%20printf&type=code. Are the remaining results shielded from being executed in library mode?

Additionally, I wonder why the value set using `setLogCallback` isn't used.

**Comment by jajhall** [comment]
Thanks for flagging this up. The particular printf statement is for debugging and I'll shield it more clearly. As for the rest, I believe that they are shielded in library mode, but I'll trawl through them at some point to check. 

The value set using `setLogCallback` is used in `highsLogUser` and `highsLogDev` (see util/HighsIO.cpp)

**Comment by Dekker1** [comment]
Great! Thank you 👍

**Comment by jajhall** [comment]
So, I've fixed this, but don't have time to pore through the rest
