### ISSUE TITLE
highspy function vs docs

### ISSUE THREAD

**Issue by Cellophil** [ERGO-Code/HiGHS#1346]
Hi, awesome solver, we love it, reporting a tiny inconsistency between docs and the highspy module:
h.getNumCol() works, it's getNumCols in the docs ([here](https://ergo-code.github.io/HiGHS/dev/interfaces/python/example-py/)). Possibly there's further plural s differences in that list.

Best,
Andreas

**Comment by jajhall** [comment]
Thanks for flagging this up: `getNumRows` and `getNumEntries` were also wrong.

Fix should propagate shortly
