### ISSUE TITLE
HiGHS Solver Installation issue (__ZN5Highs10clearModelEv) not found

### ISSUE THREAD

**Issue by FRS-3** [ERGO-Code/HiGHS#1348]
Hello, 

I am trying to install highspy in order to run the PyPSA package. 

I am receiving: highs_bindings.cpython-310-darwin.so, 0x0002): symbol not found in flat namespace (__ZN5Highs10clearModelEv)

I have tried uninstalling and installing it, but still, nothing works. Highspy is package 1.5.3 and I am running on Intel macOS Monterey

**Comment by rschwarz** [comment]
This may be related to #1328

**Comment by boeckerb** [comment]
unfortunately I have the same error:
lib/python3.9/site-packages/highspy/highs_bindings.cpython-39-darwin.so, 0x0002): symbol not found in flat namespace '__ZN5Highs10clearModelEv'

I have a M1 MacBook with Ventura but Python is running as Intel.

Are there any solutions?

**Comment by jajhall** [comment]
@galabovaa is working on this, but it's hard when things move underneath her

**Comment by d3netxer** [comment]
I also have an M1 mac and I am receiving the same error with python 3.9 and python 3.10

**Comment by kylestahl** [comment]
Same issue here on intel mac with Python 3.10

**Comment by jajhall** [comment]
What happens if you 'pip install highspy'?

**Comment by kylestahl** [comment]
Install works fine. The error appears on `import highspy`. I've tried both 1.5.3 and 1.5.2

```
kylestahl@NADQA0VMD6MOSX ~ % pip install highspy
Collecting highspy
  Using cached highspy-1.5.3-cp310-cp310-macosx_10_9_x86_64.whl (266 kB)
Installing collected packages: highspy
Successfully installed highspy-1.5.3

kylestahl@NADQA0VMD6MOSX ~ % python -c "import highspy"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/kylestahl/anaconda3/lib/python3.10/site-packages/highspy/__init__.py", line 1, in <module>
    from .highs import (
  File "/Users/kylestahl/anaconda3/lib/python3.10/site-packages/highspy/highs.py", line 1, in <module>
    from .highs_bindings import (
ImportError: dlopen(/Users/kylestahl/anaconda3/lib/python3.10/site-packages/highspy/highs_bindings.cpython-310-darwin.so, 0x0002): symbol not found in flat namespace '__ZN5Highs10clearModelEv'
kylestahl@NADQA0VMD6MOSX ~ % 
```

**Comment by galabovaa** [comment]
Thank you, apologies that this is taking so long. We are almost ready with the new python build and will update highspy asap.

**Comment by kylestahl** [comment]
Adding an update here.
I've tested Highs one 3 M1 MacBook's and never received this error. Only on an intel Mac. Not saying that is the root cause, just interesting, hope this helps.

**Comment by galabovaa** [comment]
Indeed, it is an Intel mac issue. I used to have one, but I upgraded to M1 so at the moment I have no way of testing.

**Comment by galabovaa** [comment]
We have just pushed the latest pre-release version 1.7.1.dev1 to PyPi, would you please check if this works for you, on Intel MacOS?

**Comment by kylestahl** [comment]
Works for me with 1.7.1.dev1.
Thanks!
