### ISSUE TITLE
Headers are missing for MSVC 

### ISSUE THREAD

**Issue by Downsite** [ERGO-Code/HiGHS#1349]
On MSVC, some headers are reported to be missing, causing the build to fail for me.
 I believe this is similar to the already closed issue #1151.
Concretely, I get an error on the call of std::tolower in the following line:
https://github.com/ERGO-Code/HiGHS/blob/9e519472fb3e630552178d8196b54e9b58dab27d/src/io/Filereader.cpp#L22

I think adding the headers as in 297517b871d8b900113a6120c59f8c20ff3d8b8d should fix that issue.

Thanks!

**Comment by feldmeier** [comment]
The #1358 pull request should fix this
