### ISSUE TITLE
LP reader Infinite Loop on malformed LP file

### ISSUE THREAD

**Issue by ecyrb** [ERGO-Code/HiGHS#1354]
A zero byte can cause the LP reader to enter an infinite loop. I acknowledge that this is user error, but it would be friendlier to the user to exit instead of entering an infinite loop.

Test case attached. Changing this assert in reader.cpp:

```cpp
    case '\0':  // empty line
      assert(this->linebufferpos == this->linebuffer.size());
      return false;
```

to an `lpassert` seems to fix the issue (i.e. cause an immediate exit).

[test.lp.txt](https://github.com/ERGO-Code/HiGHS/files/12073550/test.lp.txt)

As always, thank you for HiGHS.

**Comment by feldmeier** [comment]
I'll take a look at this tomorrow, should be easy enough to fix. Thanks for reporting this issue.

**Comment by jajhall** [comment]
I'm fixing it now. It looks as if the `assert(this->linebufferpos == this->linebuffer.size());` should have been `lpassert(this->linebufferpos == this->linebuffer.size());` all along
