### ISSUE TITLE
About HiGHSstatic and HIGHS_debug

### ISSUE THREAD

**Issue by Licht123** [ERGO-Code/HiGHS#1373]
I am compiling the HIGHS project using CMake on a Windows environment. After running the runHighs.cpp file for solving, I compared it with the provided static version of HIGHS-win.exe and noticed differences in the solving steps and solving time. Does your team have a process for generating high.exe on the Windows system?

**Comment by galabovaa** [comment]
Hi @Licht123, apologies for the delay. 

We generate highs.exe locally on Windows using CMake. You should try the instructions on the bottom of this page: https://ergo-code.github.io/HiGHS/stable/installation/

Please let us know if you run into any problems with that, by re-opening the issue!
