### ISSUE TITLE
1.5.4 release was not completed?

### ISSUE THREAD

**Issue by chenrui333** [ERGO-Code/HiGHS#1375]
👋 it looks like 1.5.4 release was not completed (this pypi build failed, https://github.com/ERGO-Code/HiGHS/actions/runs/5739645904/job/15556209032).  Raise this issue for some awareness. Thanks!

relates to https://github.com/Homebrew/homebrew-core/pull/138335

**Comment by jajhall** [comment]
Yes, @galabovaa knows that the pypi build failed. Since she's working on automating the pypi build on release, there's only one way to test it.

**Comment by chenrui333** [comment]
any luck?

**Comment by galabovaa** [comment]
Working on it, the automation works OK now! We have a few more errors to clean and we will publish the release.

**Comment by jajhall** [comment]
Since we know that `PyPI` build failed, and you know why, and that fixing it is WIP for us, I'll close the issue
