### ISSUE TITLE
Error installing on Windows

### ISSUE THREAD

**Issue by dmeoli** [ERGO-Code/HiGHS#1376]
Hi,

I'm trying to install HiGHS on Windows by following these steps:

C:\HiGHS\build> cmake -DFAST_BUILD=ON ..
-- HIGHS version: 1.5.3
-- Build C++ library: ON
-- Build Python: OFF
-- Build Fortran: OFF
-- Build CSharp: OFF
-- Found long size: 4
-- Found long long size: 8
-- Found int64_t size: 8
-- Found unsigned long size: 4
-- Found unsigned long long size: 8
-- Found uint64_t size: 8
-- Found int * size: 8
FLAG_MPOPCNT_SUPPORTED is not available on this architecture
-- Git hash: 9e519472f
-- Compilation date: 2023-08-04
-- FAST_BUILD set to on.
 Note: The HiGHS team is preparing for our first official release. If you
       experience any issues please let us know via email or on GitHub.
-- Build type: RELEASE
-- Build examples: ON
-- Build C++:
-- Build Python: OFF
-- Build CSharp: OFF
-- Build ZLIB: OFF
-- No CSharp support
-- Configuring test C:/HiGHS/examples/call_highs_from_cpp.cpp: ...
-- Configuring test C:/HiGHS/examples/call_highs_from_cpp.cpp: ...DONE
-- Configuring test C:/HiGHS/examples/call_highs_from_c.c: ...
-- Configuring test C:/HiGHS/examples/call_highs_from_c.c: ...DONE
-- Configuring done (1.7s)
-- Generating done (1.3s)
-- Build files have been written to: C:/HiGHS/build

after a successful "cmake --build .", I run:

C:\HiGHS\build> cmake --install .
-- Install configuration: "Release"
-- Up-to-date: C:/HiGHS/include/highs/filereaderlp/builder.hpp
-- Up-to-date: C:/HiGHS/include/highs/filereaderlp/model.hpp
-- Up-to-date: C:/HiGHS/include/highs/filereaderlp/reader.hpp
-- Up-to-date: C:/HiGHS/include/highs/io/Filereader.h
-- Up-to-date: C:/HiGHS/include/highs/io/FilereaderLp.h
-- Up-to-date: C:/HiGHS/include/highs/io/FilereaderEms.h
-- Up-to-date: C:/HiGHS/include/highs/io/FilereaderMps.h
-- Up-to-date: C:/HiGHS/include/highs/io/HMpsFF.h
-- Up-to-date: C:/HiGHS/include/highs/io/HMPSIO.h
-- Up-to-date: C:/HiGHS/include/highs/io/HighsIO.h
-- Up-to-date: C:/HiGHS/include/highs/io/LoadOptions.h
-- Up-to-date: C:/HiGHS/include/highs/lp_data/HConst.h
-- Up-to-date: C:/HiGHS/include/highs/lp_data/HStruct.h
-- Up-to-date: C:/HiGHS/include/highs/lp_data/HighsAnalysis.h
-- Up-to-date: C:/HiGHS/include/highs/lp_data/HighsDebug.h
-- Up-to-date: C:/HiGHS/include/highs/lp_data/HighsInfo.h
-- Up-to-date: C:/HiGHS/include/highs/lp_data/HighsInfoDebug.h
-- Up-to-date: C:/HiGHS/include/highs/lp_data/HighsLp.h
-- Up-to-date: C:/HiGHS/include/highs/lp_data/HighsLpSolverObject.h
-- Up-to-date: C:/HiGHS/include/highs/lp_data/HighsLpUtils.h
-- Up-to-date: C:/HiGHS/include/highs/lp_data/HighsModelUtils.h
-- Up-to-date: C:/HiGHS/include/highs/lp_data/HighsOptions.h
-- Up-to-date: C:/HiGHS/include/highs/lp_data/HighsRanging.h
-- Up-to-date: C:/HiGHS/include/highs/lp_data/HighsRuntimeOptions.h
-- Up-to-date: C:/HiGHS/include/highs/lp_data/HighsSolution.h
-- Up-to-date: C:/HiGHS/include/highs/lp_data/HighsSolutionDebug.h
-- Up-to-date: C:/HiGHS/include/highs/lp_data/HighsSolve.h
-- Up-to-date: C:/HiGHS/include/highs/lp_data/HighsStatus.h
-- Up-to-date: C:/HiGHS/include/highs/mip/HighsCliqueTable.h
-- Up-to-date: C:/HiGHS/include/highs/mip/HighsCutGeneration.h
-- Up-to-date: C:/HiGHS/include/highs/mip/HighsConflictPool.h
-- Up-to-date: C:/HiGHS/include/highs/mip/HighsCutPool.h
-- Up-to-date: C:/HiGHS/include/highs/mip/HighsDebugSol.h
-- Up-to-date: C:/HiGHS/include/highs/mip/HighsDomainChange.h
-- Up-to-date: C:/HiGHS/include/highs/mip/HighsDomain.h
-- Up-to-date: C:/HiGHS/include/highs/mip/HighsDynamicRowMatrix.h
-- Up-to-date: C:/HiGHS/include/highs/mip/HighsGFkSolve.h
-- Up-to-date: C:/HiGHS/include/highs/mip/HighsImplications.h
-- Up-to-date: C:/HiGHS/include/highs/mip/HighsLpAggregator.h
-- Up-to-date: C:/HiGHS/include/highs/mip/HighsLpRelaxation.h
-- Up-to-date: C:/HiGHS/include/highs/mip/HighsMipSolverData.h
-- Up-to-date: C:/HiGHS/include/highs/mip/HighsMipSolver.h
-- Up-to-date: C:/HiGHS/include/highs/mip/HighsModkSeparator.h
-- Up-to-date: C:/HiGHS/include/highs/mip/HighsNodeQueue.h
-- Up-to-date: C:/HiGHS/include/highs/mip/HighsObjectiveFunction.h
-- Up-to-date: C:/HiGHS/include/highs/mip/HighsPathSeparator.h
-- Up-to-date: C:/HiGHS/include/highs/mip/HighsPrimalHeuristics.h
-- Up-to-date: C:/HiGHS/include/highs/mip/HighsPseudocost.h
-- Up-to-date: C:/HiGHS/include/highs/mip/HighsRedcostFixing.h
-- Up-to-date: C:/HiGHS/include/highs/mip/HighsSearch.h
-- Up-to-date: C:/HiGHS/include/highs/mip/HighsSeparation.h
-- Up-to-date: C:/HiGHS/include/highs/mip/HighsSeparator.h
-- Up-to-date: C:/HiGHS/include/highs/mip/HighsTableauSeparator.h
-- Up-to-date: C:/HiGHS/include/highs/mip/HighsTransformedLp.h
-- Up-to-date: C:/HiGHS/include/highs/model/HighsHessian.h
-- Up-to-date: C:/HiGHS/include/highs/model/HighsHessianUtils.h
-- Up-to-date: C:/HiGHS/include/highs/model/HighsModel.h
-- Up-to-date: C:/HiGHS/include/highs/parallel/HighsBinarySemaphore.h
-- Up-to-date: C:/HiGHS/include/highs/parallel/HighsCacheAlign.h
-- Up-to-date: C:/HiGHS/include/highs/parallel/HighsCombinable.h
-- Up-to-date: C:/HiGHS/include/highs/parallel/HighsMutex.h
-- Up-to-date: C:/HiGHS/include/highs/parallel/HighsParallel.h
-- Up-to-date: C:/HiGHS/include/highs/parallel/HighsRaceTimer.h
-- Up-to-date: C:/HiGHS/include/highs/parallel/HighsSchedulerConstants.h
-- Up-to-date: C:/HiGHS/include/highs/parallel/HighsSpinMutex.h
-- Up-to-date: C:/HiGHS/include/highs/parallel/HighsSplitDeque.h
-- Up-to-date: C:/HiGHS/include/highs/parallel/HighsTaskExecutor.h
-- Up-to-date: C:/HiGHS/include/highs/parallel/HighsTask.h
-- Up-to-date: C:/HiGHS/include/highs/qpsolver/quass.hpp
-- Up-to-date: C:/HiGHS/include/highs/qpsolver/vector.hpp
-- Up-to-date: C:/HiGHS/include/highs/qpsolver/scaling.hpp
-- Up-to-date: C:/HiGHS/include/highs/qpsolver/perturbation.hpp
-- Up-to-date: C:/HiGHS/include/highs/simplex/HApp.h
-- Up-to-date: C:/HiGHS/include/highs/simplex/HEkk.h
-- Up-to-date: C:/HiGHS/include/highs/simplex/HEkkDual.h
-- Up-to-date: C:/HiGHS/include/highs/simplex/HEkkDualRHS.h
-- Up-to-date: C:/HiGHS/include/highs/simplex/HEkkDualRow.h
-- Up-to-date: C:/HiGHS/include/highs/simplex/HEkkPrimal.h
-- Up-to-date: C:/HiGHS/include/highs/simplex/HighsSimplexAnalysis.h
-- Up-to-date: C:/HiGHS/include/highs/simplex/HSimplex.h
-- Up-to-date: C:/HiGHS/include/highs/simplex/HSimplexReport.h
-- Up-to-date: C:/HiGHS/include/highs/simplex/HSimplexDebug.h
-- Up-to-date: C:/HiGHS/include/highs/simplex/HSimplexNla.h
-- Up-to-date: C:/HiGHS/include/highs/simplex/SimplexConst.h
-- Up-to-date: C:/HiGHS/include/highs/simplex/SimplexStruct.h
-- Up-to-date: C:/HiGHS/include/highs/simplex/SimplexTimer.h
-- Up-to-date: C:/HiGHS/include/highs/presolve/ICrash.h
-- Up-to-date: C:/HiGHS/include/highs/presolve/ICrashUtil.h
-- Up-to-date: C:/HiGHS/include/highs/presolve/ICrashX.h
-- Up-to-date: C:/HiGHS/include/highs/presolve/HighsPostsolveStack.h
-- Up-to-date: C:/HiGHS/include/highs/presolve/HighsSymmetry.h
-- Up-to-date: C:/HiGHS/include/highs/presolve/HPresolve.h
-- Up-to-date: C:/HiGHS/include/highs/presolve/HPresolveAnalysis.h
-- Up-to-date: C:/HiGHS/include/highs/presolve/PresolveComponent.h
-- Up-to-date: C:/HiGHS/include/highs/test/DevKkt.h
-- Up-to-date: C:/HiGHS/include/highs/test/KktCh2.h
-- Up-to-date: C:/HiGHS/include/highs/util/FactorTimer.h
-- Up-to-date: C:/HiGHS/include/highs/util/HFactor.h
-- Up-to-date: C:/HiGHS/include/highs/util/HFactorConst.h
-- Up-to-date: C:/HiGHS/include/highs/util/HFactorDebug.h
-- Up-to-date: C:/HiGHS/include/highs/util/HighsCDouble.h
-- Up-to-date: C:/HiGHS/include/highs/util/HighsComponent.h
-- Up-to-date: C:/HiGHS/include/highs/util/HighsDataStack.h
-- Up-to-date: C:/HiGHS/include/highs/util/HighsDisjointSets.h
-- Up-to-date: C:/HiGHS/include/highs/util/HighsHash.h
-- Up-to-date: C:/HiGHS/include/highs/util/HighsHashTree.h
-- Up-to-date: C:/HiGHS/include/highs/util/HighsInt.h
-- Up-to-date: C:/HiGHS/include/highs/util/HighsIntegers.h
-- Up-to-date: C:/HiGHS/include/highs/util/HighsLinearSumBounds.h
-- Up-to-date: C:/HiGHS/include/highs/util/HighsMatrixPic.h
-- Up-to-date: C:/HiGHS/include/highs/util/HighsMatrixSlice.h
-- Up-to-date: C:/HiGHS/include/highs/util/HighsMatrixUtils.h
-- Up-to-date: C:/HiGHS/include/highs/util/HighsRandom.h
-- Up-to-date: C:/HiGHS/include/highs/util/HighsRbTree.h
-- Up-to-date: C:/HiGHS/include/highs/util/HighsSort.h
-- Up-to-date: C:/HiGHS/include/highs/util/HighsSparseMatrix.h
-- Up-to-date: C:/HiGHS/include/highs/util/HighsSparseVectorSum.h
-- Up-to-date: C:/HiGHS/include/highs/util/HighsSplay.h
-- Up-to-date: C:/HiGHS/include/highs/util/HighsTimer.h
-- Up-to-date: C:/HiGHS/include/highs/util/HighsUtils.h
-- Up-to-date: C:/HiGHS/include/highs/util/HSet.h
-- Up-to-date: C:/HiGHS/include/highs/util/HVector.h
-- Up-to-date: C:/HiGHS/include/highs/util/HVectorBase.h
-- Up-to-date: C:/HiGHS/include/highs/util/stringutil.h
-- Up-to-date: C:/HiGHS/include/highs/Highs.h
-- Up-to-date: C:/HiGHS/include/highs/interfaces/highs_c_api.h
-- Up-to-date: C:/HiGHS/include/highs/ipm/IpxWrapper.h
-- Installing: C:/HiGHS/include/highs/HConfig.h
-- Up-to-date: C:/HiGHS/lib/cmake/highs/highs-config.cmake
-- Up-to-date: C:/HiGHS/lib/pkgconfig/highs.pc
-- Up-to-date: C:/HiGHS/include/highs_export.h
CMake Error at cmake_install.cmake:60 (file):
  file INSTALL cannot find "C:/HiGHS/build/RELEASE/bin/highs.dll": No error.

but I obtain the following error.

**Comment by galabovaa** [comment]
Thank you for raising this, is this the master branch you are trying to compile or latest?

**Comment by dmeoli** [comment]
master branch

**Comment by dmeoli** [comment]
> Thank you for raising this, is this the master branch you are trying to compile or latest?

master branch

**Comment by galabovaa** [comment]
Would you please try to compile with latest and let us know if you get the same error?

**Comment by dmeoli** [comment]
> Would you please try to compile with latest and let us know if you get the same error?


ofc.

I get the same error:

[ . . . ]
CMake Error at cmake_install.cmake:60 (file):
  file INSTALL cannot find "C:/HiGHS/build/RELEASE/bin/highs.dll": File
  exists.

But exists a "./DEBUG/bin" folder with:

C:\HiGHS\build\DEBUG\bin> ls


    Directory: C:\HiGHS\build\DEBUG\bin


Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
-a----        11/08/2023     22:34          88064 call_highs_from_c.exe
-a----        11/08/2023     22:34         970752 call_highs_from_c.pdb
-a----        11/08/2023     22:34         212992 call_highs_from_cpp.exe
-a----        11/08/2023     22:34        2609152 call_highs_from_cpp.pdb
-a----        11/08/2023     22:34       11681280 highs.dll
-a----        11/08/2023     22:34         905728 highs.exe
-a----        11/08/2023     22:34        7596461 highs.exp
-a----        11/08/2023     22:34       12573904 highs.lib
-a----        11/08/2023     22:34       28094464 highs.pdb

for some reason, it fails to do the same thing with the RELEASE
