### ISSUE TITLE
Missing required packages for highspy 

### ISSUE THREAD

**Issue by torressa** [ERGO-Code/HiGHS#1378]
When installing `highspy` from pip no required packages are installed with it (e.g. `numpy` is required as per [highspy/highs_bindings.cpp#L5](https://github.com/ERGO-Code/HiGHS/blob/9e519472fb3e630552178d8196b54e9b58dab27d/highspy/highs_bindings.cpp#L5)).
This was removed in https://github.com/ERGO-Code/HiGHS/commit/95b0a9cefa0bdee30ee5bd16818cfa7642fa9c5d.

**Comment by jajhall** [comment]
OK I guess that @galabovaa did this for a good reason

**Comment by jajhall** [comment]
Fixed by #1384
