### ISSUE TITLE
SetLogCallback removed in Python

### ISSUE THREAD

**Issue by siwy** [ERGO-Code/HiGHS#1379]
Hi - 

The HiGHS adapter for pulp no longer works when we enable logging, for HiGHs version > 1.5.0.dev (issue: https://github.com/coin-or/pulp/pull/678)

The error is caused by the removal of the `setLogCallback` function from the highs python api (In this PR: https://github.com/ERGO-Code/HiGHS/pull/1183). 

Is there a plan to restore this function? If not, is there a blessed way of enabling logging from the HiGHS python API?

**Comment by jajhall** [comment]
Sorry about this. I removed `setLogCallback` from `highspy` when I started to think about a more general form of callback. I'll reinstate it. Now that new versions of HiGHS are automatically pushed to `PyPI`, it shouldn't take long to propagate

**Comment by siwy** [comment]
@jajhall - Sorry to ping on this, do you know roughly when we can expect `setLogCallback` to be reinstated?

**Comment by Vincent-Liagre-QB** [comment]
Hey @jajhall I was just trying with 

```
PuLP                       3.2.1
highspy                    1.11.0
python 3.11.0
```

And had to put msg=False in 
```
solver = pulp.HiGHS(msg=False)
```

Is the problem on PuLP's side ?

**Comment by jajhall** [comment]
So far as I remember the callback was reinstated a long time ago. We've just made changes to the other callbacks, but I don't imagine that they affected the old logging callback. Any insight @mathgeekcoder ?

**Comment by mathgeekcoder** [comment]
I don't believe the callback changes should have broken this.  I had a quick look at the HiGHS adapter in PuLP but couldn't see anything obvious.

@Vincent-Liagre-QB was there an error message at all?   Are you using the HiGHS_CMD or HiGHS backend in PuLP?
