### ISSUE TITLE
Windows EXE application fails to terminate correctly

### ISSUE THREAD

**Issue by stiv-yakovenko** [ERGO-Code/HiGHS#1382]
I am launching x64 exectutable from this distribution: https://github.com/JuliaBinaryWrappers/HiGHSstatic_jll.jl/releases

highs.exe semi-continuous.lp --solution_file sol.txt

```
Maximize
x1 + 2 x2 - 0.1 x3 -3 x4
Subject To
x1 + x2 <= 5
2 x1 - x2 >= 0
-x1 + 3 x2 >= 0
x3 + x4 >= .5
Bounds
x3 >= 1.1
x3 <= 10
Semi-continuous
x3
End

```

Application writes sol.txt correctly, but never terminates, waiting at last output line:

```
Solving report
  Status            Optimal
  Primal bound      8.22333333333
  Dual bound        8.22333333333
  Gap               0% (tolerance: 0.01%)
  Solution status   feasible
                    8.22333333333 (objective)
                    0 (bound viol.)
                    0 (int. viol.)
                    0 (row viol.)
  Timing            0.23 (total)
                    0.05 (presolve)
                    0.00 (postsolve)
  Nodes             1
  LP iterations     6 (total)
                    0 (strong br.)
                    2 (separation)
                    0 (heuristics)
Writing the solution to sol.txt
```
![image](https://github.com/ERGO-Code/HiGHS/assets/4163254/9dc494d8-fc59-40ae-82fa-fa68d113f666)

**Comment by jajhall** [comment]
Sorry, this is a known issue relating to multi-threading - which currently yields little performance gain.

You should run HiGHS as follows 

highs.exe semi-continuous.lp --solution_file sol.txt --options_file options.txt

where 'options.txt' contains the line

threads=1

**Comment by stiv-yakovenko** [comment]
Wait, but if I set threads=1, I can't employ all my cpu cores.

**Comment by jajhall** [comment]
HiGHS will make very little use of more than one core
