### ISSUE TITLE
Objective limit in MIP

### ISSUE THREAD

**Issue by matbesancon** [ERGO-Code/HiGHS#1399]
In some cases, one needs the first solution to be good enough based on the objective, e.g. when implementing a separation algorithm.
We just had this discussion on MOI and added the corresponding attribute: https://github.com/jump-dev/MathOptInterface.jl/pull/2257

**Comment by jajhall** [comment]
Available in `latest` by #1408

**Comment by matbesancon** [comment]
great thanks!

**Comment by matbesancon** [comment]
as I understand it, it is a generic callback implementation. Is there one already there for MIP primal bound stop?

**Comment by jajhall** [comment]
It's sufficient to set the option `objective_target`, and when this is reached the MIP solver will return with model status `HighsModelStatus::kObjectiveTarget`, so no need for a callback.

That said, in HighsMipSolverData::checkLimits, where the objective value of the best integer solution is checked against `objective_target`, there is an interrupt, that passes the objective value of the best integer solution, so this is an alternative way to interrupt the MIP solver. However, in this case the MIP solver will return with model status `HighsModelStatus::kInterrupt`
