### ISSUE TITLE
Eliminate compiler warning from HighsCliqueTable.cpp, HighsDomain.cpp and HighsMipSolverData.cpp

### ISSUE THREAD

**Issue by jajhall** [ERGO-Code/HiGHS#1412]
/home/jajhall/HiGHS/src/mip/HighsCliqueTable.cpp:1617:18: warning: variable 'numDel' set but not used [-Wunused-but-set-variable]
        HighsInt numDel = 0;
                 ^
/home/jajhall/HiGHS/src/mip/HighsDomain.cpp:2421:16: warning: variable 'propnnz' set but not used [-Wunused-but-set-variable]
      HighsInt propnnz = 0;
               ^
/home/jajhall/HiGHS/src/mip/HighsDomain.cpp:2514:18: warning: variable 'propnnz' set but not used [-Wunused-but-set-variable]
        HighsInt propnnz = 0;
                 ^
/home/jajhall/HiGHS/src/mip/HighsMipSolverData.cpp:598:20: warning: use of bitwise '&' with boolean operands [-Wbitwise-instead-of-logical]
        numBin += ((mipsolver.model_->col_lower_[i] == 0.0) &
                  ~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                                                            &&
/home/jajhall/HiGHS/src/mip/HighsMipSolverData.cpp:598:20: note: cast one or both operands to int to silence this warning

**Comment by fwesselm** [comment]
I think these warnings were fixed by #1464 , #1468 or #1471.
