### ISSUE TITLE
Presolve log

### ISSUE THREAD

**Issue by fwesselm** [ERGO-Code/HiGHS#1417]
Hi!

I am passing a model (LP) to HiGHS via "passModel" and then presolving it by calling "presolve". This seems to work fine!

Now, my questions is how to find out about the reductions that presolve has performed, i.e. which rows/columns have been removed?

I tried getting the log using "getPresolveLog", but it seems to be empty. I tried to enable option "presolve_rule_logging", but it still does not seem to work (- the log is partially empty).

Is there another way to get the information about the presolve reductions?

Thanks!

**Comment by jajhall** [comment]
In short, no. All you can do is to extract the presolved LP. However, I don't think that this will have any names allowing you to identify which rows/columns remain. It's soon added, though.

To get the presolve log, you have set the option `presolve_rule_logging` to true

**Comment by fwesselm** [comment]
OK, thanks. Just one more question, why is presolve logging not available for MIPs (or when solving the LP relaxation of a MIP)?

`// Allow logging if option is set and model is not a MIP`
`allow_logging_ = options_->presolve_rule_logging && !model_->isMip();`

**Comment by jajhall** [comment]
I implemented the presolve logging for students studying LP presolve techniques, so stopped there. The MIP exclusion is, I think, due to a bug that was found when an LP with free rows was presolved.
