### ISSUE TITLE
Stuck process when writing solution

### ISSUE THREAD

**Issue by dhoop-iidev** [ERGO-Code/HiGHS#1425]
Hello and thanks for the development of these amazing optimization tool !

I've had an issue using HiGHS when I run several optimization in a row. This happened recently within the PyPSA Earth project, and now again with the python optimization package pulp. What usually happens is that some simulations succeed and then one simulation get stuck (it can the second, third, fifth, seventh...) writing the solution to the .sol file. Implementing a time-out kills the process with an error, which is not very useful in my case, since I want to do hundreds of optimization in a row.
I use the solver from the command line and have highs downloaded from the github repo:
solver = pulp.HiGHS_CMD() 
prob.solve(solver)
[run_results.txt](https://github.com/ERGO-Code/HiGHS/files/12702669/run_results.txt)

Thanks in advance for any person that might have a clue on how I could get rid of that, maybe some memory issue (although there is space left on my disk and have 64gb ram).

**Comment by jajhall** [comment]
Are you working on Windows?

**Comment by dhoop-iidev** [comment]
Yes on Windows 11 with Python 3.9

**Comment by jajhall** [comment]
Then it may be the issue relating to multi-threading, for which the fix is to set the HiGHS option

threads=1

This won't impair performance, as our solvers are almost entirely serial at present.

**Comment by dhoop-iidev** [comment]
Thank you very much, it does work now ! ;)
