### ISSUE TITLE
Publish highspy 1.6.0 wheels

### ISSUE THREAD

**Issue by AdeelK93** [ERGO-Code/HiGHS#1439]
I believe 1.6.0 includes the fix for wheel build issues (https://github.com/ERGO-Code/HiGHS/pull/1343) and allowing macos to install highspy via pypi rather than building from source. 

It would be great if the 1.6.0 wheels could be built and uploaded! Thank you!!

**Comment by jajhall** [comment]
Thanks, but we need to be confident that this allows highspy to be installed via PyPI on all architectures

**Comment by AdeelK93** [comment]
anything i can do to help with that? would a GHA testing matrix help?

**Comment by galabovaa** [comment]
Thank you for your offer, the GHA matrix is not the issue. Do you know much about meson? One issue at the moment is the shared library lookup. 

https://github.com/ERGO-Code/HiGHS/actions/runs/6403243988/job/17381362923

**Comment by galabovaa** [comment]
Moving this to a discussion, updating highspy is a WIP
