### ISSUE TITLE
Using mps filereader on native Macbook compilation gives strange output

### ISSUE THREAD

**Issue by feldmeier** [ERGO-Code/HiGHS#145]
output in HDualRow.cpp
printf("!! STRANGE: Empty Freelist has size %d\n", freeListSize);
is triggered thousands of time when readingin qap10.mps using highs as a library. Error does not appear when using .lp filereader.

**Comment by feldmeier** [comment]
This error appears also on windows. Possibly not visible on linux due to some compiler settings?

**Comment by galabovaa** [comment]
@feldmeier is this still an issue?

**Comment by feldmeier** [comment]
unfourtunately I don't have a Macbook to test with, back then the issue was encountered when I gave a talk at a local company.
