### ISSUE TITLE
MIP warm start example

### ISSUE THREAD

**Issue by jiawlu** [ERGO-Code/HiGHS#1455]
I am working with MIP using HiGHS. I already have feasible integer solutions of good quality. How can I utilize these solutions as a warm start in HiGHS? Are there any examples or references that could guide me?

**Comment by jajhall** [comment]
Pass the solution to HiGHS with Highs::setSolution and, if it's feasible then the HiGHS MIP solver will use it for bounding.

Only available for C++ and C, unless you can install the latest version of the Python interface yourself.
