### ISSUE TITLE
Use mip_feasibility_tolerance when assessing user solution

### ISSUE THREAD

**Issue by jajhall** [ERGO-Code/HiGHS#1458]
For the problem:
min 0 :
1 x <= -1e-6
x \in [0, inf]
x integer
HiGHS gets the x = 0. However, if it's set a starting solution, it's deemed infeasible.

See #1457

**Comment by odow** [comment]
Gurobi also has a similar problem. The tolerances used in presolve can be different to the final optimality tolerances. It caused me no end of trouble to debug...
