### ISSUE TITLE
When will the highspy 1.6.0 package be released?

### ISSUE THREAD

**Issue by ZedongPeng** [ERGO-Code/HiGHS#1469]
Hi. I notice that `highs` 1.6.0 has been released for a month. However, the highspy 1.6.0 package hasn't been released yet.
Is there any plan for the release of highspy 1.6.0 package?

Thanks.

**Comment by jajhall** [comment]
We cannot currently build highspy for all architectures, so the release of highspy 1.6.0 will be delayed, sorry.

**Comment by ZedongPeng** [comment]
Hi @jajhall. Just one more question.  Is there an estimated delay for the next release?
Many thanks.
