### ISSUE TITLE
Time limit enforced with respect to global run time 

### ISSUE THREAD

**Issue by hlefebvr** [ERGO-Code/HiGHS#1477]
Hi all,

I am a new user of HiGHS and have an issue with the way run time is taken into account. 

**Observed behavior**
The time limit seems to be enforced with respect to the global run time, i.e., the cumulative run time of all runs for a given Highs object.

**Expected behavior**
I would have expected that the time limit be compared to the run time of the current execution, or that this behavior be warned in the documentation as it is a non-standard choice (comparing to GLPK, Gurobi, Mosek, Lpsolve, ...). 

Language: C++
OS: Linux (Ubuntu 22)
Version: 1.6.0

**Comment by jajhall** [comment]
We're aware of the difference, and this behaviour will be changed when we reach version 2.0. It doesn't seem to be a sufficiently major issue to highlight in our (limited) documentation.

Otherwise, I hope you're happy with HiGHS
