### ISSUE TITLE
Vector subscript out of range in HFactor

### ISSUE THREAD

**Issue by feldmeier** [ERGO-Code/HiGHS#148]
The highs library and executable now compile on windows using visual studio 2017 on branch https://github.com/ERGO-Code/HiGHS/commits/windows.

Running highs on qap4 results in a runtime error ("vector subscript out of range"):

  highs.dll!std::vector<int,std::allocator<int> >::operator[](const unsigned __int64 _Pos)
  highs.dll!HFactor::buildFinish() Line 1072
  highs.dll!HFactor::build() Line 283
  highs.dll!compute_factor(HighsModelObject & highs_model_object) Line 1860
  highs.dll!setupForSimplexSolve(HighsModelObject & highs_model_object) Line 301
  highs.dll!runSimplexSolver(const HighsOptions & opt, HighsModelObject & highs_model_object) Line 88
  highs.dll!Highs::runSolver(HighsModelObject & model) Line 819
  highs.dll!Highs::run() Line 125

In the line
   Ulastp.assign(&Ustart[1], &Ustart[numRow + 1]);
Ustart has a size of 105, numRow has a value of 104, so index 105 (corresponding to the 106th element) is being accessed.

The beheaviour is also happening on linux afaik, but GCC doesn't appear to check for the size, and valgrind only checks the capacity (which is a lot higher due to the + 1000 at .reserve()), which is why it goes both unnoticed and without negative effects on linux.  But MSVC is stricter.

**Comment by svigerske** [comment]
https://stackoverflow.com/questions/5594686/gcc-stl-bound-checking

**Comment by feldmeier** [comment]
Thanks @svigerske. That will help in finding all occurrences easily!
We should add this to CMAKE to run the checks if compiled in debug. I will do this in the windows branch for now.
