### ISSUE TITLE
Force generation of primal and dual ray

### ISSUE THREAD

**Issue by hlefebvr** [ERGO-Code/HiGHS#1481]
Hi,

I'm using the C++ API. Is there a way to tell HiGHS that, in case of infeasibility or unboundedness, I would like to retrieve a dual or primal ray ? 

As far as I understand, if the problem is solved during presolved, no such ray is accessible right now. But it could be (with large probability) that I am just missing an API feature here. 

Thanks!

**Comment by jajhall** [comment]
There's no way to _tell_ HiGHS to return a dual or primal ray. If such a ray has been generated to prove primal or dual unboundedness, then it's available. 

In the case of primal or dual infeasibility being identified in presolve, no such ray is available. In this event, a ray can only be generated by attempting to solve the LP with `presolve="off"`
