### ISSUE TITLE
stream_solver doesn't stream in real time

### ISSUE THREAD

**Issue by juzun** [ERGO-Code/HiGHS#1489]
I am using HiGHS solver on my optimization problem in Python, Pyomo library. 
Issue I have is that when I set the solver option `stream_solver` to `True`, I don't get the real time streaming while solving the problem. It shows up after the problem was solved. I know other solvers do stream in real time (Cbc, CPLEX...) but this one doesn't. Is there some way to force this solver to stream in real time?

My usage is basic and hopefully correct:
```
self.slvr = appsi.solvers.Highs()
self.slvr.config.stream_solver = True
self.results = self.slvr.solve(self.model)
```

**Comment by jajhall** [comment]
If I understand correctly, you want the HiGHS logging information to be displayed in real time. Since HiGHS generates logging output in real time, this sound like a Pyomo issue, rather than a HiGHS issue.

**Comment by juzun** [comment]
Yes, you understand that correctly. It could be, but as I say, all the other solvers I tried do generate logging output in real time. Using the same attributes, with nothing changed, just solver.

**Comment by jajhall** [comment]
Since I understand the issue that you're having, it's a Pyomo issue, not a HiGHS issue. Please raise it with Pyomo

**Comment by juzun** [comment]
No, if it was Pyomo issue, other solvers would have the same problem, no? But the problem occurs only with HiGHS. Why should I close this issue?

**Comment by jajhall** [comment]
Because there's nothing in HiGHS that causes what you observe. Nothing to change or fix in HiGHS. Hence, not a HiGHS issue. Understand?

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by jajhall** [comment]
Plus I've given you the route out of the issue you're having: raise it with Pyomo.

**Comment by juzun** [comment]
Ok, understand. Thank you.
