### ISSUE TITLE
All variables in constraint ignored if just one coefficient is 0

### ISSUE THREAD

**Issue by matt035343** [ERGO-Code/HiGHS#1495]
When I make a constraint where just one of the coefficients is zero, the all variables are removed from the constraint.

Example:

```python
import highspy
solver = highspy.Highs()

solver.addVar(0, 1)
solver.changeColIntegrality(0, highspy.HighsVarType.kInteger)

solver.addVar(0, 1)
solver.changeColIntegrality(1, highspy.HighsVarType.kInteger)

solver.addRow(-highspy.kHighsInf, 5, 1, [0,1], [0,1])

solver.writeModel("highs_bug_1.lp")
```
In this example, two variables are added and used in a constraint. Variable 0 has coefficient 0, and variable 1 has coefficient 1. Then I write the model to the file. Above code emits this error:

```
WARNING: LP matrix packed vector contains 1 |values| in [0, 0] less than or equal to 1e-09: ignored
```

And writes this to the file:

```
\ File written by HiGHS .lp file handler
min
 obj: 
st
 con1: <= +5
bounds
 x1 <= 1
 x2 <= 1
bin
 x1
 x2
gen
semi
end
```

Notice that there are no variables in the constraint, there is only an upper bound. I would have expected that variable 1 is included in the model.

If I instead run the following code:

```
import highspy
solver = highspy.Highs()

solver.addVar(0, 1)
solver.changeColIntegrality(0, highspy.HighsVarType.kInteger)


solver.addVar(0, 1)
solver.changeColIntegrality(1, highspy.HighsVarType.kInteger)

solver.addRow(-highspy.kHighsInf, 5, 1, [1], [1])

solver.writeModel("highs_bug_2.lp")
```

Where I manually remove the variable with coefficient 0 from the constraint, following model is generated:

```
\ File written by HiGHS .lp file handler
min
 obj: 
st
 con1: +1 x2 <= +5
bounds
 x1 <= 1
 x2 <= 1
bin
 x1
 x2
gen
semi
end
```
This shows the behavior I expected from the first code snippet as well.

Environment:
python=3.9.17
highspy=1.5.3, `Running HiGHS 1.5.3 [date: 2023-05-16, git hash: 594fa5a9d-dirty]`

**Comment by jajhall** [comment]
Strange, I will investigate

**Comment by jajhall** [comment]
An error is returned by `solver.addRow(-highspy.kHighsInf, 5, 1, [0,1], [0,1])`, so the row isn't added.

I'll investigate why an error is returned

**Comment by jajhall** [comment]
The third parameter of `solver.addRow(-highspy.kHighsInf, 5, 1, [0,1], [0,1])` is the number of entries in the arrays of indices and values. In documentation it may refer (casually) to the number of nonzeros in the row. 

HiGHS is assuming that your row has one entry - in column 0, and with value 0
