### ISSUE TITLE
Optimal objective function value different when "--presolve==off"

### ISSUE THREAD

**Issue by jajhall** [ERGO-Code/HiGHS#1510]
Highs 1.6.0 for [issue-1510.lp](https://github.com/ERGO-Code/HiGHS/files/13363508/issue-1510.lp.txt) yields an objective value of

- 21 (correct) with presolve 
- 20 _without_ presolve

New issue spawned by #1284

**Comment by fwesselm** [comment]
In the run without presolve all integer-constrained variables are feasible at the root node with respect to the default `mip_feasibility_tolerance`.

However, some of the solution values are slightly fractional:

`sol.col_value[6] = 0.99999990000000005`
`sol.col_value[8] = 1.0000000005838672e-07`

When I set 

`highs.setOptionValue("mip_feasibility_tolerance", 1e-9);`

HiGHS finds the correct optimal solution.

**Comment by jajhall** [comment]
Interesting, so not a bug
