### ISSUE TITLE
Fortran interface doesn't build on Windows

### ISSUE THREAD

**Issue by ogmundur** [ERGO-Code/HiGHS#1549]
The Fortran interface to HiGHS won't build on Windows because the search for a fortran compiler is turned off in the presence of MSVC and some of the compiler options added by add_definitions are not necessarily understood by the fortran compiler (I'm using ifort and it doesn't like /W4). I added a very rough patch that at least corrected these issues on my machine but ymmv.

[Win_Fortran.patch](https://github.com/ERGO-Code/HiGHS/files/13675887/Win_Fortran.patch)

**Comment by HaoZeke** [comment]
@jajhall this can be closed now.

**Comment by jajhall** [comment]
Closed by #1604
