### ISSUE TITLE
Suggestion for Addition of Routine to Query Size of HighsInt in HiGHS

### ISSUE THREAD

**Issue by WalterLu3** [ERGO-Code/HiGHS#1565]
The suggestion involves the addition of a routine in HiGHS to query and return the value of sizeof(HighsInt) (and potentially sizeof(lu_int) as I do work with the basiclu routine). 

Allowing the HiGHS users to access this information might be beneficial. Currently, the way for a developer to ensure that they use the correct version (int64 or int32 version) of HiGHS is only at the building phase where they can change the config for compilation. 

Take the shared library of HiGHS for example, after the compilation, there is no way a user can know the int version of it, as the macros of HighsInt do not create symbol in the shared library. This addition allows HiGHS users to add another layer of int version check int their applications (so make sure that sizeof(HighsInt) == sizeof(user's int), else give a warning message asking to use 2^(sizeof(user's int))-bit version of HiGHS ) where they call or link HiGHS.

**Comment by jajhall** [comment]
Fair enough: it's easy to add. Note that by virtue of [basiclu.h#L26](https://github.com/ERGO-Code/HiGHS/blob/master/src/ipm/basiclu/basiclu.h#L26), `lu_int` and `HighsInt` are the same size

**Comment by jajhall** [comment]
Fixed by #1566
