### ISSUE TITLE
Pass tests with sanitizer

### ISSUE THREAD

**Issue by Coloquinte** [ERGO-Code/HiGHS#1576]
Using the meson build, it is easy to run address, undefined and thread sanitizers.

```
meson setup build_address -Dwith_tests=True -Db_sanitize=address; meson test -C build_address
meson setup build_undefined -Dwith_tests=True -Db_sanitize=undefined; meson test -C build_undefined
meson setup build_thread -Dwith_tests=True -Db_sanitize=thread; meson test -C build_thread
```

The address sanitizer fails due to leaks in the C API tests. The undef and thread sanitizers seem to uncover more serious errors.

(I'll get around to investigating it more at some point, but probably not this week)

**Comment by jajhall** [comment]
Thanks, that's useful to know. I can well imagine that there are memory leaks in the testing of the C API, as we're C++ developers!
