### ISSUE TITLE
Python-3.12 wheels ?

### ISSUE THREAD

**Issue by stonebig** [ERGO-Code/HiGHS#1580]
having also Python-3.12 wheels would be interesting, if it's not a problem.

**Comment by jajhall** [comment]
Does the heart reaction imply this this works for you @stonebig, so we can close the issue?

**Comment by stonebig** [comment]
Sorry, forgot to close

**Comment by ollie-bell** [comment]
> We have just pushed the latest pre-release version 1.7.1.dev1 to PyPi, including python 3.12 wheels. Would you please check if this works for you?

Hey, I'm getting a bit confused by this. On PyPi the latest release is 1.5.3 (which distributes wheels for Python 3.9-3.11, but not Python 3.12) ... but `pip install highspy` on Python 3.12 successfully installs 1.7.1.dev1 as is without having to specify the `--pre` option.

I'm having issues with `conda-lock` which uses Poetry's dependency solver to find pip packages specified in a conda environment file. Poetry can't find 1.7.1.dev1.
