### ISSUE TITLE
Out-of-bound access in HighsLpUtils.cpp

### ISSUE THREAD

**Issue by Coloquinte** [ERGO-Code/HiGHS#1581]
I think there is an out-of-bound access in HighsLpUtils.cpp [here](https://github.com/ERGO-Code/HiGHS/blob/6c9fa1b23a3fc178588443ae1597bcd465deece3/src/lp_data/HighsLpUtils.cpp#L424) (access after the bounds of the container), which is picked by the address sanitizer in some conditions.
This can be shown by running the tests with [this commit](https://github.com/Coloquinte/Highs-solver/commit/05bcdd85b455f012616f6c0f1aa5f7055ca04d66), which checks the bounds explicitly.

Related to #1576, but a bit more involved to fix than the other issues.

**Comment by jajhall** [comment]
fixed by #1582
