### ISSUE TITLE
Presolve fails on model with no variable

### ISSUE THREAD

**Issue by rhshadrach-8451** [ERGO-Code/HiGHS#1588]
Certainly of no consequence on anything useful, but when building a model piece-by-piece, we were stumped a little when starting out on why HiGHs couldn't find a feasible solution to an empty model.

```
import pyomo.environ as pe

m = pe.ConcreteModel()
m.a = pe.Var(domain=pe.Binary)
m.obj = pe.Objective(rule=lambda m: 0)
solver = pe.SolverFactory('appsi_highs')

result = solver.solve(m)
# RuntimeError: A feasible solution was not found, ...
```

Adding a variable into the objective (but still having the zero function) solves successfully:

    m.obj = pe.Objective(rule=lambda m: 0 * m.a)

Turning on output with `tee=True`, we see presolve as giving:

    Model   status      : Empty

My take: I think it's reasonable to error on empty models, but maybe a more informative error message could be raised in this specific edge-case?

**Comment by jajhall** [comment]
I'm not a Pyomo user, so can't be sure of what HiGHS is getting as a result of the lines

>m = pe.ConcreteModel()
m.a = pe.Var(domain=pe.Binary)
m.obj = pe.Objective(rule=lambda m: 0)
solver = pe.SolverFactory('appsi_highs')
result = solver.solve(m)

From your subsequent comments, it would appear that HiGHS has been asked to solve a model with one (binary) variable, zero objective coefficient and no constraints.

I've created this in various versions of HiGHS - which one are you using - and in each case the solver identifies optimality and returns with a status of "OK".

Either I'm mis-interpreting what you're doing with Pyomo - could you send me a .lp or MPS file created just before you call `solver.solve(m)` - or this is a Pyomo issue.

**Comment by jajhall** [comment]
Do you agree that  this seems like a Pyomo issue?

I'll close the issue in a few days unless you disagree

**Comment by jajhall** [comment]
@michaelbynum Is this anything you can reproduce?

**Comment by michaelbynum** [comment]
This is likely a Pyomo issue. I'll take a look.

**Comment by rhshadrach-8451** [comment]
Sorry for the delay here - I do think it is correct that Pyomo is doing this. E.g. in the recent changelog I noticed [this PR](https://github.com/Pyomo/pyomo/pull/3056) about removing unused variables. I don't know the Pyomo internals, but this indicates to me that Pyomo is indeed sending over an empty model.

**Comment by jajhall** [comment]
OK, thanks. I'll repeat my experiment with an empty model.

**Comment by michaelbynum** [comment]
That Pyomo PR only has to do with the NL writer, which is not used in the Pyomo-HiGHS interface. I believe this is a problem in the Pyomo-HiGHS interface.

**Comment by michaelbynum** [comment]
I created a Pyomo issue (https://github.com/Pyomo/pyomo/issues/3106). This one can probably be closed.
