### ISSUE TITLE
Python Interface should release the GIL when run gets called

### ISSUE THREAD

**Issue by michaelbynum** [ERGO-Code/HiGHS#1593]
The GIL prevents other python threads from running. Releasing it when `run` is called (and grabbing it again at the end of `run`) will allow other threads to proceed while HiGHS is running.

**Comment by michaelbynum** [comment]
Please assign me.

**Comment by Basdbruijne** [comment]
Relatedly, HiGHS ignores keyboard interrupts. I assume that this is also due to how HiGHS gets called.

**Comment by jajhall** [comment]
Through highspy, I can well imagine that it does ignore keyboard interrupts

**Comment by michaelbynum** [comment]
Yes, I believe releasing the GIL will also fix the keyboard interrupt issue.

**Comment by KelvinCheng5507** [comment]
Hello, may I ask whether this has been fixed? I'm sometimes experiencing similar problems. Thanks!

**Comment by michaelbynum** [comment]
I did try to fix this, but my initial attempt was not successful. I'll give it another try today.

**Comment by michaelbynum** [comment]
Ahh... I think I see how to fix this.

**Comment by michaelbynum** [comment]
I've got the keyboard interrupt working. I'll create a PR shortly.

**Comment by galabovaa** [comment]
Should be fixed in latest already, note, that https://github.com/ERGO-Code/HiGHS/pull/1942 was just merged with some significant updates. Closing this, @michaelbynum please open another issue if you run into any further problems. Thank you!
