### ISSUE TITLE
Compiling with VS 2022 in Windows

### ISSUE THREAD

**Issue by dmeoli** [ERGO-Code/HiGHS#1624]
Hello,

I'm trying to compile with Visual Studio 17 2022, so I run:

`C:\HiGHS\build> cmake -DFAST_BUILD=ON -DBUILD_SHARED_LIBS=OFF -DCMAKE_INSTALL_PREFIX=C:/HiGHS ..`

-- Building for: Visual Studio 17 2022
-- Selecting Windows SDK version 10.0.22621.0 to target Windows 10.0.22000.
-- The CXX compiler identification is MSVC 19.37.32824.0
-- The C compiler identification is MSVC 19.37.32824.0
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.37.32822/bin/Hostx64/x64/cl.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.37.32822/bin/Hostx64/x64/cl.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- HIGHS version: 1.6.0
-- Build C++ library: ON
-- Build Python: OFF
-- Build Fortran: OFF
-- Build CSharp: OFF
-- Looking for C++ include sys/types.h
-- Looking for C++ include sys/types.h - found
-- Looking for C++ include stdint.h
-- Looking for C++ include stdint.h - found
-- Looking for C++ include stddef.h
-- Looking for C++ include stddef.h - found
-- Check size of long
-- Check size of long - done
-- Found long size: 4
-- Check size of long long
-- Check size of long long - done
-- Found long long size: 8
-- Check size of int64_t
-- Check size of int64_t - done
-- Found int64_t size: 8
-- Check size of unsigned long
-- Check size of unsigned long - done
-- Found unsigned long size: 4
-- Check size of unsigned long long
-- Check size of unsigned long long - done
-- Found unsigned long long size: 8
-- Check size of uint64_t
-- Check size of uint64_t - done
-- Found uint64_t size: 8
-- Check size of int *
-- Check size of int * - done
-- Found int * size: 8
-- Performing Test HIGHS_HAVE_MM_PAUSE
-- Performing Test HIGHS_HAVE_MM_PAUSE - Success
-- Performing Test HIGHS_HAVE_BITSCAN_REVERSE
-- Performing Test HIGHS_HAVE_BITSCAN_REVERSE - Success
FLAG_MPOPCNT_SUPPORTED is not available on this architecture
-- Performing Test NO_OMIT_FRAME_POINTER_FLAG_SUPPORTED
-- Performing Test NO_OMIT_FRAME_POINTER_FLAG_SUPPORTED - Failed
-- Found ZLIB: C:/msys64/ucrt64/lib/libz.dll.a (found suitable version "1.3", minimum required is "1.2.3")
-- Git hash: b49188ffe
-- Compilation date: 2024-02-18
-- FAST_BUILD set to on.
-- Build type: Release
-- Build examples: ON
-- Build C++:
-- Build Python: OFF
-- Build CSharp: OFF
-- Build ZLIB: OFF
-- No CSharp support
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - not found
-- Found Threads: TRUE
-- Performing Test COMPILER_HAS_DEPRECATED_ATTR
-- Performing Test COMPILER_HAS_DEPRECATED_ATTR - Failed
-- Performing Test COMPILER_HAS_DEPRECATED
-- Performing Test COMPILER_HAS_DEPRECATED - Success
-- Configuring test C:/HiGHS/examples/call_highs_from_cpp.cpp: ...
-- Configuring test C:/HiGHS/examples/call_highs_from_cpp.cpp: ...DONE
-- Configuring test C:/HiGHS/examples/call_highs_from_c.c: ...
-- Configuring test C:/HiGHS/examples/call_highs_from_c.c: ...DONE
-- Configuring done (39.8s)
-- Generating done (0.2s)
-- Build files have been written to: C:/HiGHS/build

and then `cmake --build .`

but I obtain the following errors:

C:\HiGHS\build> cmake --build .
MSBuild version 17.7.2+d6990bcfa for .NET Framework

  1>Checking Build System
  Building Custom Rule C:/HiGHS/src/CMakeLists.txt
  reader.cpp
  Filereader.cpp
  FilereaderLp.cpp
  FilereaderEms.cpp
C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.37.32822\include\vcruntime.h(386,51): error C2065: 'uintptr_t': undeclared identifier (compiling source file C:\HiGHS
\src\io\Filereader.cpp) [C:\HiGHS\build\src\highs.vcxproj]
C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.37.32822\include\vcruntime.h(386,51): error C2065: 'uintptr_t': undeclared identifier (compiling source file C:\HiGHS
\extern\filereaderlp\reader.cpp) [C:\HiGHS\build\src\highs.vcxproj]
C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.37.32822\include\vcruntime.h(386,61): error C2146: syntax error: missing ')' before identifier '_StackCookie' (compil
ing source file C:\HiGHS\src\io\Filereader.cpp) [C:\HiGHS\build\src\highs.vcxproj]
C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.37.32822\include\vcruntime.h(386,61): error C2146: syntax error: missing ')' before identifier '_StackCookie' (compil
ing source file C:\HiGHS\extern\filereaderlp\reader.cpp) [C:\HiGHS\build\src\highs.vcxproj]
C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.37.32822\include\vcruntime.h(387,67): error C2065: 'uintptr_t': undeclared identifier (compiling source file C:\HiGHS
\src\io\Filereader.cpp) [C:\HiGHS\build\src\highs.vcxproj]
C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.37.32822\include\vcruntime.h(387,67): error C2065: 'uintptr_t': undeclared identifier (compiling source file C:\HiGHS
\extern\filereaderlp\reader.cpp) [C:\HiGHS\build\src\highs.vcxproj]
C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.37.32822\include\vcruntime.h(387,77): error C2146: syntax error: missing ')' before identifier '_StackCookie' (compil
ing source file C:\HiGHS\src\io\Filereader.cpp) [C:\HiGHS\build\src\highs.vcxproj]
C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.37.32822\include\vcruntime.h(387,77): error C2146: syntax error: missing ')' before identifier '_StackCookie' (compil
ing source file C:\HiGHS\extern\filereaderlp\reader.cpp) [C:\HiGHS\build\src\highs.vcxproj]
C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.37.32822\include\vcruntime.h(391,18): error C2146: syntax error: missing ';' before identifier '__security_cookie' (c
ompiling source file C:\HiGHS\src\io\Filereader.cpp) [C:\HiGHS\build\src\highs.vcxproj]
C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.37.32822\include\vcruntime.h(391,18): error C2146: syntax error: missing ';' before identifier '__security_cookie' (c
ompiling source file C:\HiGHS\extern\filereaderlp\reader.cpp) [C:\HiGHS\build\src\highs.vcxproj]
C:\msys64\ucrt64\include\corecrt.h(75,44): error C2378: 'uintptr_t': redefinition; symbol cannot be overloaded with a typedef (compiling source file C:\HiGHS\src\io\Filereader.cpp) [C:\HiGHS
\build\src\highs.vcxproj]
C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.37.32822\include\vcruntime.h(391,8): message : see declaration of 'uintptr_t' (compiling source file C:\HiGHS\src\io\
Filereader.cpp) [C:\HiGHS\build\src\highs.vcxproj]
C:\msys64\ucrt64\include\corecrt.h(75,44): error C2378: 'uintptr_t': redefinition; symbol cannot be overloaded with a typedef (compiling source file C:\HiGHS\extern\filereaderlp\reader.cpp)
[C:\HiGHS\build\src\highs.vcxproj]
C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.37.32822\include\vcruntime.h(391,8): message : see declaration of 'uintptr_t' (compiling source file C:\HiGHS\extern\
filereaderlp\reader.cpp) [C:\HiGHS\build\src\highs.vcxproj]
C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.37.32822\include\vcruntime.h(386,51): error C2065: 'uintptr_t': undeclared identifier (compiling source file C:\HiGHS
\src\io\FilereaderLp.cpp) [C:\HiGHS\build\src\highs.vcxproj]
C:\msys64\ucrt64\include\stddef.h(26,28): error C2143: syntax error: missing ';' before '__cdecl' (compiling source file C:\HiGHS\src\io\Filereader.cpp) [C:\HiGHS\build\src\highs.vcxproj]
C:\msys64\ucrt64\include\stdio.h(195,64): error C2144: syntax error: 'int' should be preceded by ';' (compiling source file C:\HiGHS\extern\filereaderlp\reader.cpp) [C:\HiGHS\build\src\highs
.vcxproj]
C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.37.32822\include\vcruntime.h(386,61): error C2146: syntax error: missing ')' before identifier '_StackCookie' (compil
ing source file C:\HiGHS\src\io\FilereaderLp.cpp) [C:\HiGHS\build\src\highs.vcxproj]
C:\msys64\ucrt64\include\stddef.h(26,18): error C2370: 'uintptr_t': redefinition; different storage class (compiling source file C:\HiGHS\src\io\Filereader.cpp) [C:\HiGHS\build\src\highs.vcx
proj]
C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.37.32822\include\vcruntime.h(391,8): message : see declaration of 'uintptr_t' (compiling source file C:\HiGHS\src\io\
Filereader.cpp) [C:\HiGHS\build\src\highs.vcxproj]
C:\msys64\ucrt64\include\stdio.h(198,69): error C2144: syntax error: 'int' should be preceded by ';' (compiling source file C:\HiGHS\extern\filereaderlp\reader.cpp) [C:\HiGHS\build\src\highs
.vcxproj]
C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.37.32822\include\vcruntime.h(387,67): error C2065: 'uintptr_t': undeclared identifier (compiling source file C:\HiGHS
\src\io\FilereaderLp.cpp) [C:\HiGHS\build\src\highs.vcxproj]
C:\msys64\ucrt64\include\stdio.h(201,87): error C2144: syntax error: 'int' should be preceded by ';' (compiling source file C:\HiGHS\extern\filereaderlp\reader.cpp) [C:\HiGHS\build\src\highs
.vcxproj]
C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.37.32822\include\cstdint(52,25): error C2874: using-declaration causes a multiple declaration of 'uintptr_t' (compili
ng source file C:\HiGHS\src\io\Filereader.cpp) [C:\HiGHS\build\src\highs.vcxproj]
C:\msys64\ucrt64\include\corecrt.h(75,44): message : see declaration of 'uintptr_t' (compiling source file C:\HiGHS\src\io\Filereader.cpp) [C:\HiGHS\build\src\highs.vcxproj]
C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.37.32822\include\vcruntime.h(386,51): error C2065: 'uintptr_t': undeclared identifier (compiling source file C:\HiGHS
\src\io\FilereaderEms.cpp) [C:\HiGHS\build\src\highs.vcxproj]
C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.37.32822\include\vcruntime.h(387,77): error C2146: syntax error: missing ')' before identifier '_StackCookie' (compil
ing source file C:\HiGHS\src\io\FilereaderLp.cpp) [C:\HiGHS\build\src\highs.vcxproj]
C:\msys64\ucrt64\include\stdio.h(204,92): error C2144: syntax error: 'int' should be preceded by ';' (compiling source file C:\HiGHS\extern\filereaderlp\reader.cpp) [C:\HiGHS\build\src\highs
.vcxproj]
C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.37.32822\include\vcruntime.h(386,61): error C2146: syntax error: missing ')' before identifier '_StackCookie' (compil
ing source file C:\HiGHS\src\io\FilereaderEms.cpp) [C:\HiGHS\build\src\highs.vcxproj]
C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.37.32822\include\cstdint(86,17): error C2874: using-declaration causes a multiple declaration of 'uintptr_t' (compili
ng source file C:\HiGHS\src\io\Filereader.cpp) [C:\HiGHS\build\src\highs.vcxproj]
C:\msys64\ucrt64\include\corecrt.h(75,44): message : see declaration of 'uintptr_t' (compiling source file C:\HiGHS\src\io\Filereader.cpp) [C:\HiGHS\build\src\highs.vcxproj]
[ . . . ]

and so on...

Any help?

**Comment by jajhall** [comment]
I've no idea. How about you, @galabovaa ?

**Comment by metab0t** [comment]
It seems that you are mixing header file of msys2 and MSVC. You can remove the msys2 directory from your PATH and try again.

**Comment by dmeoli** [comment]
@metab0t ok, now it seems working.. I had a lot of warnings about conversion from size_t to int and other similar but it's ok. thx.
