### ISSUE TITLE
Python HiGHS rounding of integers

### ISSUE THREAD

**Issue by IvoW10** [ERGO-Code/HiGHS#1626]
Python HiGHS seems to do strange roundings of integer variables. It seems that there is little to no rounding applied after the variables get their value, which could give issues in the constraints.

So for example, it seems to be a case that a binary variable can have a value equal to 0.00000001, which might lead to issues in constraints. 

An example of an LP that gives issues
[model_pyomo.txt](https://github.com/ERGO-Code/HiGHS/files/14331738/model_pyomo.txt)

**Comment by jajhall** [comment]
Indeed, no rounding is applied after the variables get their value. This is _because_ this can give issues in the constraints. Although unlikely, the rounding "perturbation" of a solution value it could lead to a constraint no longer being satisfied to within the feasibility tolerance.

As with commercial MIP solvers, HiGHS solves problems to within tolerances, not exactly. In the case of integer variables, in an optimal solution they are within 1e-06 of an integer value.
