### ISSUE TITLE
Could we release a new version?

### ISSUE THREAD

**Issue by bachdavi** [ERGO-Code/HiGHS#1630]
Hello 👋 

Would it be possible to release a new version?  We've been facing issues in Julia with hijacked CTRL-C behavior that was fixed with this commit: https://github.com/ERGO-Code/HiGHS/commit/c0360c9927a70411da178c37c781a84d8697317b.
I'm not sure what the release cadence is here :) 

Thanks!

**Comment by jajhall** [comment]
We're hoping to release a new version by Monday 🙂

**Comment by bachdavi** [comment]
@jajhall Awesome!
