### ISSUE TITLE
Callback support for highspy

### ISSUE THREAD

**Issue by KelvinCheng5507** [ERGO-Code/HiGHS#1645]
Before raising the issue, I must thank you for creating such a wonderful project! I'm using highs through pyomo which is working fabulously.

In the file /examples/call_highs_from_python.py, there appears to be a setCallback function for the highspy interface, but I couldn't run it on my computer (after doing pip install highspy).

Aside from that file, the callback support for python interface is mentioned nowhere else. The only mention I found was in /docs/src/callbacks.md which specified callback only for the C++ interface, which makes me believe that callback is only available through C++ currently (please correct me if I am wrong). Is adding the callback support for python planned for future?

Thank you so much!

**Comment by jajhall** [comment]
We've added a range of callbacks (all using the same handler) but they not available in https://pypi.org/project/highspy/ (HiGHS v1.5.3). To use them, highspy must be installed locally using (at least) HiGHS v1.6.0

Sorry for the confusion: I've added a comment to `examples/call_highs_from_python.py`
