### ISSUE TITLE
New release with `SIGINT` handler removed

### ISSUE THREAD

**Issue by kpamnany** [ERGO-Code/HiGHS#1650]
The current release, `v1.6.0`, installs a `SIGINT` handler that calls `exit`. This causes problems for downstream applications that are managing signals themselves (such as ours). We hadn't opened an issue about it because we saw that the handler was removed in [this commit](https://github.com/ERGO-Code/HiGHS/commit/c0360c9927a70411da178c37c781a84d8697317b). However, there hasn't been a new release of HiGHS since that fix was merged, so this problem is still plaguing us. Could you please make a new release that includes that fix? Thanks!

**Comment by jajhall** [comment]
An new release without the handler is imminent
