### ISSUE TITLE
highspy 1.7.0 - module not found - python 3.9 - win 11

### ISSUE THREAD

**Issue by lpierezan** [ERGO-Code/HiGHS#1655]
In Win 11, using conda, I´ve created an env with python 3.9 and installed highspy with pip

Here is the conda env

```
name: p39
channels:
  - conda-forge
dependencies:
  - bzip2=1.0.8=hcfcfb64_5
  - ca-certificates=2024.2.2=h56e8100_0
  - libffi=3.4.2=h8ffe710_5
  - libsqlite=3.45.1=hcfcfb64_0
  - libzlib=1.2.13=hcfcfb64_5
  - openssl=3.2.1=hcfcfb64_0
  - pip=24.0=pyhd8ed1ab_0
  - python=3.9.18=h4de0772_1_cpython
  - setuptools=69.1.1=pyhd8ed1ab_0
  - tk=8.6.13=h5226925_1
  - tzdata=2024a=h0c530f3_0
  - ucrt=10.0.22621.0=h57928b3_0
  - vc=14.3=hcf57466_18
  - vc14_runtime=14.38.33130=h82b7239_18
  - vs2015_runtime=14.38.33130=hcb4865c_18
  - wheel=0.42.0=pyhd8ed1ab_0
  - xz=5.2.6=h8d14728_0
  - pip:
      - highspy==1.7.0
      - numpy==1.26.4
```

No error installing highspy

![image](https://github.com/ERGO-Code/HiGHS/assets/856658/71347765-8e0e-4ab6-b57b-d01eb4a16b85)

But no module is found when trying to import highspy

![image](https://github.com/ERGO-Code/HiGHS/assets/856658/d20037a1-c9b0-4582-971e-9bb34df4b299)

**Comment by jajhall** [comment]
This is an issue that we've just discovered ourselves - when I updated `highspy` on my W10 laptop, which uses the Microsoft store Python 3.9, and it's why we've deleted v1.7.0 on PyPI.

@galabovaa will work on fixing this, but making `highspy` build and run on all reasonable architectures and Python versions is exceptionally difficult

**Comment by galabovaa** [comment]
We have just pushed the latest pre-release version 1.7.1.dev1 to PyPi,  would you please check if this works for you?

**Comment by lpierezan** [comment]
@galabovaa yes, it works! Thanks! :)
