### ISSUE TITLE
Illegal access on vectors in presolve

### ISSUE THREAD

**Issue by feldmeier** [ERGO-Code/HiGHS#170]
The windows branch introduces the D_GLIBCXX_DEBUG flag when compiling in debug mode.

This detects illegal accesses in two unit tests.

Here the stacktrace for the box1.mps with debug enabled:

 __GI_raise(int sig) (/build/glibc-OTsEL5/glibc-2.27/sysdeps/unix/sysv/linux/raise.c:51)
__GI_abort() (/build/glibc-OTsEL5/glibc-2.27/stdlib/abort.c:79)
[Unknown/Just-In-Time compiled code] (Unknown Source:0)
std::__debug::vector<int, std::allocator<int> >::operator[](std::__debug::vector<int, std::allocator<int> > * const this, std::__debug::vector<int, std::allocator<int> >::size_type __n) (/usr/include/c++/7/debug/vector:417)
HPreData::isZeroA(HPreData * const this, int i, int j) (/home/s1613957/master/src/presolve/HPreData.cpp:54)
Presolve::removeDoubletonEquations(Presolve * const this) (/home/s1613957/master/src/presolve/Presolve.cpp:358)
Presolve::presolve(Presolve * const this, int print) (/home/s1613957/master/src/presolve/Presolve.cpp:143)
Presolve::presolve(Presolve * const this) (/home/s1613957/master/src/presolve/Presolve.cpp:168)
Highs::runPresolve(Highs * const this, PresolveInfo & info) (/home/s1613957/master/src/lp_data/Highs.cpp:857)
Highs::run(Highs * const this) (/home/s1613957/master/src/lp_data/Highs.cpp:159)
main(int argc, char ** argv) (/home/s1613957/master/app/RunHighs.cpp:103)

**Comment by galabovaa** [comment]
Fixed.
