### ISSUE TITLE
Shouldn't Highs header be logged only when the output flags are set to "true"?

### ISSUE THREAD

**Issue by guifcoelho** [ERGO-Code/HiGHS#1702]
After `highspy.Highs()`, if any variable is added the version header will be logged

```
Running HiGHS 1.7.0 (git hash: 27ccfaa): Copyright (c) 2024 HiGHS under MIT licence terms
```

Setting option 'output_flag' to 'false'  before adding variables will make the header to not be logged.

Shouldn't the header be logged only when the output flags are set to "true"?

This came to my attention after [this](https://github.com/ERGO-Code/HiGHS/issues/1670#issuecomment-2018578877)

**Comment by jajhall** [comment]
The default setting of 'output_flag' is true, and will remain so. In this, HiGHS is consistent with commercial solver software like Gurobi.

If anyone wants to suppress logging, 'output_flag' must be set to be false before calling a HiGHS method (other than the method to set the option, of course).
