### ISSUE TITLE
cmake config tests FAST_BUILD variable

### ISSUE THREAD

**Issue by discopt** [ERGO-Code/HiGHS#1715]
The generated (and installed) `highs-config.make` file contains a test
```
if (FAST_BUILD)
  if(NOT TARGET highs)
    include("${CMAKE_CURRENT_LIST_DIR}/highs-targets.cmake")
  endif()
  set(HIGHS_LIBRARIES highs)
else()
  if(NOT TARGET libhighs)
    include("${CMAKE_CURRENT_LIST_DIR}/highs-targets.cmake")
  endif()
  set(HIGHS_LIBRARIES highs)
endif()
```
This file is included from cmake projects that _use_ HiGHS. So they typically don't have a FAST_BUILD variable. Even if they have one, it may be different from the value that this variable had when _building_ HiGHS. I don't know exactly what the difference between FAST_BUILD and non-FAST_BUILD is, but I guess the intended behavior would be to have `@FAST_BUILD@` in the if-statement.

**Comment by galabovaa** [comment]
Thank you! We intend to remove FAST_BUILD but until then I have added your suggestion in https://github.com/ERGO-Code/HiGHS/pull/1744
