### ISSUE TITLE
saved MIP solutions pool is empty when solution is found during presolve

### ISSUE THREAD

**Issue by lkapelevich** [ERGO-Code/HiGHS#1724]
I noticed that when an optimal solution is found during presolve, it's not recorded or returned with getSavedMipSolutions().

Any reason not to record it e.g. [here](https://github.com/ERGO-Code/HiGHS/blob/master/src/mip/HighsMipSolver.cpp#L127)?

**Comment by jajhall** [comment]
Well spotted. No reason not to store it - for completeness

**Comment by jajhall** [comment]
Closed by #1742
