### ISSUE TITLE
Add writePresolvedModel

### ISSUE THREAD

**Issue by jajhall** [ERGO-Code/HiGHS#1729]
If users want to write out the model after the HiGHS presolve, they must extract it using `getPresolvedLp`, load it into HiGHS, and then call `writeModel`. Adding `writePresolvedModel` isn't difficult...

**Comment by feldmeier** [comment]
Alternative idea would be having write(filename) as a function of Model rather than the Highs class (and maybe read(filename) as a  static function of Model producing a Model object).
The syntax would then be something like getPresolvedLp().write()

**Comment by jajhall** [comment]
Closed by #1741

**Comment by Thell** [comment]
I know this is closed but I'm not sure my question warrants a new ticket.

Could the executable have

`--write_presolve_file arg    File for writing out presolved model.`

and the options have

`presolve_file`.

I know it'd be greatly helpful when using non-direct interfaces to HiGHS.

If you think it might warrant opening a new ticket just say the word.

**Comment by jajhall** [comment]
I think it's too esoteric to have as a command-line option - the option would have to be set in an options file - but I see that if you're wanting just a file of the presolved model then, at the moment, you can't get it when running HiGHS from the command line. 

It's easy to add.

**Comment by jajhall** [comment]
Closed by #1863
