### ISSUE TITLE
HiGHS always run in parallel mode

### ISSUE THREAD

**Issue by bobozi-cmd** [ERGO-Code/HiGHS#1731]
I find whatever argument set for "--parallel", the HiGHS will create threads to solve, why?
Details:
I built the binary followed README, and run "./build/bin/HiGHS --parallel on xxx.mps" and "./build/bin/HiGHS --parallel off xxx.mps", then the HiGHS will create 12 threads in my pc. Then I look source code, fine "initialize_scheduler()" will always create multithreads, maybe this is a bug?

**Comment by jajhall** [comment]
It's not a bug. The --parallel option controls whether the parallel simplex solver is used if the model in HiGHS is an LP. For symmetry detection in the MIP solver parallelism is always used unless threads=1 is set.
