### ISSUE TITLE
MPS file reader for highs.rs Rust crate

### ISSUE THREAD

**Issue by DaveLanday** [ERGO-Code/HiGHS#1755]
I cannot figure out how to read mps files using the highs.rs rust crate. Do I need to use an external .mps file reader? If so, am I better off using the PyO3 crate to use the built in parser of highspy?

**Comment by jajhall** [comment]
HiGHS didn't create the highs.rs rust crate, so we can't help you on this. 

I suggest that you raise it as an issue on https://github.com/lovasoa/HiGHS so @lovasoa can help?

**Comment by lovasoa** [comment]
see https://github.com/rust-or/highs/issues/15
