### ISSUE TITLE
clearing of `HighsCallbackDataIn`

### ISSUE THREAD

**Issue by lkapelevich** [ERGO-Code/HiGHS#1761]
I am wondering if `HighsCallback::clearHighsCallbackDataIn()` should be exposed and exported.

I have some code that is calling `highs.run()` twice. The first time I request to interrupt the solve via a callback. For the second run I don't want `highs.callback_.data_in.user_interrupt` to be true. But the only way I see to clear it is to call `highs.setCallback` again, which I shouldn't have to do, if the callback function is unchanged. Apologies if I missed a method.

**Comment by jajhall** [comment]
Are you saying that if you've once set `highs.callback_.data_in.user_interrupt` to be true, then it remains true? 

In suggesting that you should just set  `highs.callback_.data_in.user_interrupt` to be false, I suspect that I've misunderstood your scenario
