### ISSUE TITLE
v1.70 cannot be compiled under Windows

### ISSUE THREAD

**Issue by mingcaixiao** [ERGO-Code/HiGHS#1768]
# Error Info
cupdlp_linalg.c(790,41): error C2039: 'dBeta': is not a member of 'CUPDLP_STEPSIZE'
# build config
CMake:3.29.2
vs2022

**Comment by jajhall** [comment]
I don't see why you're getting this error, as `v1.7.0` is compiled on many versions of Windows as part of our CI tests. 

As you [see](https://github.com/ERGO-Code/HiGHS/blob/master/src/pdlp/cupdlp/cupdlp_defs.h), `dBeta` clearly is a member of 'CUPDLP_STEPSIZE'

**Comment by mingcaixiao** [comment]
**dBeta** is indeed a member variable of **CUPDLP_STEPSIZE**
My Visual Studio error list shows:
![image](https://github.com/ERGO-Code/HiGHS/assets/40676838/56f3974f-6d46-4c00-b2b2-67901c7e4e0f)
When I delete square root symbol in the comment before the **dBeta**  member, the compilation works with no erros!
![image](https://github.com/ERGO-Code/HiGHS/assets/40676838/d121680b-9c2b-409d-9190-92f596aa3292)
It looks like it's an issue with character encoding.
PS. I use a Chinese Windows11 Operating System.

**Comment by jajhall** [comment]
Interesting - I never thought that a comment could ever become compilable code!

Also interesting, as the comment was written by a Chinese person, but maybe in the USA. 

I'll modify the comment to remove the nonstandard symbol

**Comment by jajhall** [comment]
@galabovaa @odow 

Have you ever seen a non-ascii symbol act as an escape character like this - effectively extending a comment to prevent an identifier from being declared?

**Comment by odow** [comment]
Nope. This is out of my wheelhouse

**Comment by jajhall** [comment]
Reopened as a reminder

**Comment by jajhall** [comment]
Closed by #e1e6152
