### ISSUE TITLE
Documentation of HiGHS' output

### ISSUE THREAD

**Issue by kbrix2000** [ERGO-Code/HiGHS#1772]
Dear HiGHS team,

thanks a lot for providing HiGHS!

Currently I am looking for a documentation of HiGHS' output, maybe I missed it in the documentation.

In particular, in the first column (even before the number of nodes) there from time to time is a letter, e.g. L, R, B, T. What does this indicate? Which other letters can occur and what do they mean? 

Could you give me a hint?

**Comment by jajhall** [comment]
See https://github.com/ERGO-Code/HiGHS/discussions/1736

**Comment by kbrix2000** [comment]
Ok, thanks a lot! :+1:
