### ISSUE TITLE
Build fails on macOS: `f951: Error: '-fno-fat-lto-objects' are supported only with linker plugin`

### ISSUE THREAD

**Issue by barracuda156** [ERGO-Code/HiGHS#1801]
```
  f951: Error: '-fno-fat-lto-objects' are supported only with linker plugin
  make[2]: *** [src/CMakeFiles/FortranHighs.dir/interfaces/highs_fortran_api.f90.o] Error 1
  make[2]: Leaving directory `/opt/local/var/macports/build/_Users_runner_work_macports-ports_macports-ports_ports_math_HiGHS/HiGHS/work/build'
  make[1]: *** [src/CMakeFiles/FortranHighs.dir/all] Error 2
  make[1]: *** Waiting for unfinished jobs....
```

**Comment by barracuda156** [comment]
For some reason a pure GCC build on my 10.6 did not complain, but Clang + gfortran on CI fails:
https://github.com/macports/macports-ports/actions/runs/9487009099/job/26142622690?pr=24455

**Comment by galabovaa** [comment]
Thank you for raising this, @barracuda156. I reproduced the issue on my mac, addressed in https://github.com/ERGO-Code/HiGHS/pull/1802, which will be merged in latest after @jajhall 's review.

**Comment by galabovaa** [comment]
Merged in latest!
