### ISSUE TITLE
Get Column Cost

### ISSUE THREAD

**Issue by enri07** [ERGO-Code/HiGHS#1804]
Hi everyone,

First of all, thank you very much for your amazing work!

I am currently using HiGHS in a project and was wondering if there is a way to retrieve the objective coefficient associated with a specific variable. I was looking for a function named like `Highs_getColCost`, but couldn't find anything like that. Can someone help me with this?

Thank you in advance for your time!

Enrico Calandrini

**Comment by jajhall** [comment]
You can get the objective coefficient associated with a specific variable `my_col` by using the following general function for getting data for a range of columns

> Highs_getColsByRange(const void* highs, const HighsInt from_col,
                              const HighsInt to_col, HighsInt* num_col,
                              double* costs, double* lower, double* upper,
                              HighsInt* num_nz, HighsInt* matrix_start,
                              HighsInt* matrix_index, double* matrix_value);

with the following parameter values 

> Highs_getColsByRange(highs, my_col,
                              my_col, num_col,
                              cost, NULL, NULL, 
                              num_nz, NULL,
                              NULL, NULL);

where (from the definition) `num_col`, `cost` and `num_nz` are pointers to scalars. 

I know that you don't need `num_col`, or `num_nz`, but they cannot (currently) be passed as `NULL` pointers.
