### ISSUE TITLE
Presolve with infeasible LP and postsolve with empty LPs

### ISSUE THREAD

**Issue by jajhall** [ERGO-Code/HiGHS#181]
Presolve on [infeasible_norows.mps.gz](https://github.com/ERGO-Code/HiGHS/files/3382042/infeasible_norows.mps.gz) reduces the model to empty, but should identify the trivial infeasibility due to the bounds on column 0. [Originally such inconsistent bounds were going to be flagged up when the model was loaded, but now it's felt that the LP should be permitted.]

Postsolve on [presolve_to_empty.mps.gz](https://github.com/ERGO-Code/HiGHS/files/3382051/presolve_to_empty.mps.gz) has a dual residual error of 1.

**Comment by galabovaa** [comment]
Fixed.
