### ISSUE TITLE
Stop MIP solve on `simplex_iteration_limit` (or other LP iteration limit) - Access iteration count via callback?

### ISSUE THREAD

**Issue by spoorendonk** [ERGO-Code/HiGHS#1814]
I would like to stop the MIP solve early using the number of LP iterations. This seems only to be checked when the problem is a pure LP.

On a side note, it could be nice to also have access to the `simplex_iteration_count`in the callback out data object. Then one can control the stop dynamically via the `kCallbackMipInterrupt`

**Comment by jajhall** [comment]
It's easy to put in, and I'll do it, but for MIP it doesn't strike me as a natural interrupt criterion - unlike LP.

**Comment by jajhall** [comment]
Fixed by #1839
