### ISSUE TITLE
Reported optimal solution is not optimal

### ISSUE THREAD

**Issue by TheSil** [ERGO-Code/HiGHS#1864]
HiGHS returns optimal solution but when inspected or compared with other solvers, better solutions are found. I collected one example.

Input: [tmp.zip](https://github.com/user-attachments/files/16479180/tmp.zip)
Code:

```
import highspy

h = highspy.Highs()
filename = 'tmp.mps'
h.readModel(filename)
h.run()

solution = h.getSolution()
info = h.getInfo()
model_status = h.getModelStatus()
print('Model status = ', h.modelStatusToString(model_status))
print('Optimal objective = ', info.objective_function_value)
print(solution.col_value)
```

It reports:
Model status =  Optimal
Optimal objective =  1126020.0
`[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 714.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 26.0]`

True optimal is in fact 1126000, for example with: 
`[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 136, 0, 0, 0, 0, 0, 0, 0, 15, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 26]`

Am I missing some output flag or setting?

**Comment by jajhall** [comment]
HiGHS may well have found a solution that is optimal to within the relative MIP gap. Other solvers may have smaller default MIP gap or happen to find the optimal solution

**Comment by TheSil** [comment]
Oh, that explains a lot. I played with mip_rel_gap / mip_abs_gap params and was able to achieve better results. 

Thank you, I had no idea...

**Comment by jajhall** [comment]
You're welcome. For many models, getting something within 0.01% is enough, and getting provable optimality is very much more time-consuming. Hence the default . But I understand that there are other applications where folk need probable optimality.
