### ISSUE TITLE
Python type stubs for native extensions

### ISSUE THREAD

**Issue by N-Wouda** [ERGO-Code/HiGHS#1866]
The native extensions in the `highspy` package are currently untyped, which makes it difficult for many editors/language servers to discover available methods and data fields. In particular, in VS Code, I get `Any` as the return type for almost every method call into the native extensions in `_core`.

I can work around this for the most part by following the documentation, but not being able to discover the interface of many objects from my IDE makes for a frustrating development experience.

The canonical way to solve this with Python is via [type stub files](https://peps.python.org/pep-0484/#stub-files), in this case a `_core.pyi` file. They can be generated relatively easily using [mypy's stubgen](https://mypy.readthedocs.io/en/stable/stubgen.html) and then updated as needed. Looking at the bindings, this should not be too much work to set up and maintain. I could have a go at this if there's any interest?

Edit: `stubgen --parse-only -o . -m _core` seems to work. I need to check the output a bit and then I'll open a PR.

**Comment by jajhall** [comment]
Thanks, the nature of solver development means that HiGHS team does not contain any Python developers, so we welcome community contributions!

**Comment by N-Wouda** [comment]
@jajhall alright, I'll look into this soon!

**Comment by jajhall** [comment]
closed by #1867
