### ISSUE TITLE
Double free or corruption on STADAT1 problem

### ISSUE THREAD

**Issue by stephane-caron** [ERGO-Code/HiGHS#1875]
> [!NOTE]\
> Sorry for the double-posting but I was not able to re-open https://github.com/ERGO-Code/HiGHS/issues/995 after reporting in https://github.com/ERGO-Code/HiGHS/issues/995#issuecomment-2288292977 that the error can be reproduced with HiGHS 1.7.2. Feel free to re-organize these issues as you see fit.

I tried re-enabling and testing again this problem today with HiGHS 1.7.2, and the following error happens:

```console
[2024-08-14 11:00:07,531] [info] Solving STADAT1 by highs with default settings... (run.py:108)
error
error
error
error
...  <- repeated many times
error
error
error
double free or corruption (out)
[1]    48891 abort (core dumped)  python maros_meszaros.py run --rerun
```

This test can be reproduced by running the following command in the [maros_meszaros_qpbenchmark](https://github.com/qpsolvers/maros_meszaros_qpbenchmark/) project:

```console
$ python maros_meszaros.py run --rerun --problem STADAT1 --solver highs
```

**Comment by jajhall** [comment]
Thanks, I'll try to reproduce this
