### ISSUE TITLE
WARNING: LP matrix packed vector contains 2 |values| in [0, 0] less than or equal to 1e-09: ignore

### ISSUE THREAD

**Issue by few** [ERGO-Code/HiGHS#1899]
With the `latest` branch (not with 1.7.2), I get lots of the following warnings:
`WARNING: LP matrix packed vector contains 2 |values| in [0, 0] less than or equal to 1e-09: ignore`

I guess that's because I'm adding constraints (using highspy) with a coefficient of `0` for some variables. There is some code that computes these coefficients and some end up as `0`. Is that a problem? Is there a way to silence these warnings?

**Comment by jajhall** [comment]
Closed by #1919
