### ISSUE TITLE
Enable QP handling in C# and tidy up the use of HighsModel

### ISSUE THREAD

**Issue by jajhall** [ERGO-Code/HiGHS#1900]
The C# interface cannot handle QPs, so some mechanism needs to be added. 

I can add a C# call to `Highs::passHessian` that allows a Hessian term to be added to the incumbent LP

In C++ the Hessian is held as an instance of the `HighsHessian` class, and a QP is represented as an instance of the `HighsModel` class - that consists of a `HighsLp` and a `HighsHessian` instance.

In C# there is a "HighsModel" object that corresponds to (a subset of) the data members of the `HighsLp` class, which is a bit of a mess. This should be sorted so that the C# there is a "HighsModel" object corresponds to the C++ `HighsModel`  class, and something else (in C#) relates to `HighsLp`  class.

But this would break the C# API...

@Thiago-NovaesB: are you in a position to advise/help us on this

**Comment by Thiago-NovaesB** [comment]
I believe that exposing the internal structures of HiGHS via API is not a good idea.
I really like the API created by SCIP, I recently made an interface in C# for it and we can use some ideas from there.
SCIP exposes pointers to its structures via API. The API methods receive these pointers. So these structures do not need to be replicated in each API. Some examples:

The Create method just give us the pointer to the main scip struct:
`private static partial ScipRetCode SCIPcreate(ref IntPtr scip);`
`// SCIP_RETCODE SCIPcreate(SCIP** scip)`

The get solution receive just the main struct pointer and returns the pointer to the solution struct:
`private static partial IntPtr SCIPgetBestSol(IntPtr scip);`
`// SCIP_SOL* SCIPgetBestSol(SCIP* scip)`

The get the value of a variable in the solution, just pass the main struct pointer, solution pointer and variable pointer:
`private static partial double SCIPgetSolVal(IntPtr scip, IntPtr sol, IntPtr v);`
`// SCIP_Real SCIPgetSolVal(SCIP* scip, SCIP_SOL* sol, SCIP_VAR* var)`

**Comment by Thiago-NovaesB** [comment]
Do you think that we can do the same in HiGHS? Share the pointers to avoid replicate structs?

**Comment by jajhall** [comment]
If I understand correctly, 

- In principle this would make the HiGHS C# API similar to its C API, where the parameter lists consist only of scalars and pointers to vectors.
- The C# structures are local to C# and allow users to build structures of scalars, enums and vectors so that an LP (and now Hessian) can be represented as a single object. In [call_highs_from_csharp.cs](https://github.com/ERGO-Code/HiGHS/blob/master/examples/call_highs_from_csharp.cs) this is done by creating `HighsModel model` (sic) to represent an LP, allowing the call `HighsStatus status = solver.passLp(model);` to be used to pass the model to HiGHS. 

However, all this call does is pass the individual components of `model` (plus the scalar dimensions deduced from lengths and casting enums to int) into the C API method. 

Other than saving a user from having identifiers for the number of rows, columns and nonzeros, this doesn't achieve a lot. But I'm not a C# user, so I don't know whether it's appreciated by anyone. 

Note that I've just edited  [call_highs_from_csharp.cs](https://github.com/ERGO-Code/HiGHS/blob/master/examples/call_highs_from_csharp.cs) heavily, since the LP it formed was infeasible! [I've changed the LP completely and, after solving it, I've added a Hessian and solved again.](https://github.com/ERGO-Code/HiGHS/blob/fix-1900a/examples/call_highs_from_csharp.cs)

**Comment by Thiago-NovaesB** [comment]
"In principle this would make the HiGHS C# API similar to its C API, where the parameter lists consist only of scalars and pointers to vectors."
I dont think so. I'm talking about create strucs in C# just to keep the C++ pointer private (so the user of C# API dont care about how C++ works):

```
public struct ScipVariable
{
    private IntPtr ptr;
}
public struct ScipConstraint
{
    private IntPtr ptr;
}
public struct ScipSolution
{
    private IntPtr ptr;
}
```
Then the C# API uses will looks like:

```
ScipVariable x = solver.CreateVariable("xVar", 0d, 1d, -1d, ScipVartype.SCIP_VARTYPE_CONTINUOUS);
ScipVariable y = solver.CreateVariable("yVar", 0.5, 1d, 1d, ScipVartype.SCIP_VARTYPE_BINARY);
ScipVariable z = solver.CreateVariable("zVar", 0.5, 1d, 1d, ScipVartype.SCIP_VARTYPE_BINARY);
solver.DeleteVariable(y);
solver.Solve();
ScipSolution sol = solver.GetBestSolution();
double xVal = solver.GetSolutionVariableValue(sol, x);
```

The C# API will use just private pointers, the one who will consumes the API will have a clean C# code.

The downside of this approach is that we need to expose many methods for all types of necessary edits.

If you think this is not a good idea, we can continue with the current idea, replicating the structures in C#.

**Comment by Thiago-NovaesB** [comment]
I'm a little confused by your initial comment about breaking the C# API. Isn't it just necessary to add some fields in the HighsModel class to accommodate the Hessian?

**Comment by jajhall** [comment]
I still don't see what you mean, or appreciate the value of having "a clean C# code", as I'm not a C# user. Specifically, I don't see the difference between what you suggest and having

>       HighsLpSolver solver = new HighsLpSolver();

where `HighsLpSolver` has a ` private IntPtr highs` - the pointer to the HiGHS C++ instance? 

Both then use `solver.run()` etc

How would "solver" be instantiated the way you would want. 

> I'm a little confused by your initial comment about breaking the C# API. Isn't it just necessary to add some fields in the HighsModel class to accommodate the Hessian?

Again, I'm displaying my almost complete ignorance of C#. I thought that if non-optional parameters were added to 

> public HighsModel(double[] colcost, ...

then code written for the original parameter list would fail due to having insufficient parameters.

**Comment by jajhall** [comment]
I'll leave the issue open and retain the branch, but I believe that what I've done works, and @LatonCypher wants to use it.

**Comment by LatonCypher** [comment]
Yeah. It works. I am Laton cypher. I am about to test it. I just modified the name of the solver. I now called it HighsSolver against HighsLpSolver.

Thanks so much.

Lateef
________________________________

**Comment by Thiago-NovaesB** [comment]
Sorry, I hadn't seen your branch and I was confused about what exactly you wanted.
In fact, if the parameter is not optional, it needs to be passed. But couldn't you do the same as you did with MIP? Keep null as default: 
```
public class HighsModel
{
    public HighsObjectiveSense sense;
    public double[] colcost;
    public double offset;
    public double[] collower;
    public double[] colupper;
    public double[] rowlower;
    public double[] rowupper;
    public HighsMatrixFormat a_format;
    public int[] astart;
    public int[] aindex;
    public double[] avalue;
    public int[] highs_integrality;
    public HessianFormat? q_format;
    public int[] qstart;
    public int[] qindex;
    public double[] qvalue;

    public HighsModel()
    {

    }

    public HighsModel(double[] colcost, double[] collower, double[] colupper, double[] rowlower, double[] rowupper,
    int[] astart, int[] aindex, double[] avalue, int[] highs_integrality = null, double offset = 0, HighsMatrixFormat a_format = HighsMatrixFormat.kColwise, HighsObjectiveSense sense = HighsObjectiveSense.kMinimize, HessianFormat? q_format = null, int[]? qstart = null,int[]? qindex = null, double[]? qvalue = null)
    {
        this.colcost = colcost;
        this.collower = collower;
        this.colupper = colupper;
        this.rowlower = rowlower;
        this.rowupper = rowupper;
        this.astart = astart;
        this.aindex = aindex;
        this.avalue = avalue;
        this.offset = offset;
        this.a_format = a_format;
        this.sense = sense;
        this.highs_integrality = highs_integrality;
        this.qstart = qstart;
        this.qindex = qindex;
        this.qvalue = qvalue;
        this.q_format = q_format;
    }
}
```
And then:
```
public HighsStatus passModel(HighsModel model)
{
    return (HighsStatus)HighsLpSolver.Highs_passModel(
        this.highs,
        model.colcost.Length,
        model.rowlower.Length,
        model.avalue.Length,
        model.qvalue.Length,
        (int)model.a_format,
        (int)model.q_format,
        (int)model.sense,
        model.offset,
        model.colcost,
        model.collower,
        model.colupper,
        model.rowlower,
        model.rowupper,
        model.astart,
        model.aindex,
        model.avalue,
        model.qstart,
        model.qindex,
        model.qvalue,
        model.highs_integrality);
}
```

**Comment by Thiago-NovaesB** [comment]
Anyway, I'll think a bit about how to improve this interface, if I have an interesting idea, I'll open a PR for you to check what you think.

**Comment by LatonCypher** [comment]
I think this modification by Thiago is another improvement. So I can use the same constructor to make but LPModel and QPmodel. If I am making LP, I just stop after highs_integrality since parameters that follow are optional. And if I have a QP problem, then I list the hessian parameters in the call to the model constructor and every other things follow just as for the Lp.

Thank you for all your work.

Lateef

________________________________

**Comment by LatonCypher** [comment]
@jajhall and @Thiago-NovaesB  thank you so much for the contribution. I have used both original modification by @jajhall and then the additional modification by @Thiago-NovaesB . Both works well. 

I have decided to go with the final modification by @Thiago-NovaesB. I have tested it and the results were consistent. 

I also modified the info to contain the qp_Iteration_Count. 

May be I should provide my version of  "highs_csharp_api.cs".

**Comment by LatonCypher** [comment]
Thank you for all your contribution since yesterday. I have not completed and integration and tested all examples provided by Matlab here
Quadratic programming - MATLAB quadprog (mathworks.com)<https://www.mathworks.com/help/optim/ug/quadprog.html>
And gotten the same result.

I feel that LP in highs is just a special case of QP without Hessian (I am not sure I am correct since QP in Highs can not handle integer variable).

Attached here is the copy of my modifications to "highs_csharp_api.cs"  file.

I have modified it to handle cases where Q might not be given, or the As of the inequality/equality might not be given.

And added the "qp_Iteration_Count" to the info.

Also, I set the default Matrixformat to "kRowwise"

I have also gotten rid of the passLp and passMip, I am now only having passModel.

So my QP and LP use of the highs now look very similar.

Because in my application, as I am indexing the number of wells, and the facility the flow passes through, the equalities and inequalites came naturally in compressed row form.

Note: We are planning to make our Mathematics Library open and freely available to everyone by the end of October. Is there anything we need to do as regards with our use of Highs?



Lateef A. Kareem

CypherCrescent Ltd.

76 Fiddil Ave.

Trans-amadi, PH

Tel: +2349091633519
Email: ***@***.***



________________________________

**Comment by jajhall** [comment]
> Thank you for all your contribution since yesterday. I have not (**now?**) completed and integration and tested all examples provided by Matlab here Quadratic programming - MATLAB quadprog (mathworks.com)<https://www.mathworks.com/help/optim/ug/quadprog.html> And gotten the same result. 

Great, that's very good to know

>I feel that LP in highs is just a special case of QP without Hessian (I am not sure I am correct since QP in Highs can not handle integer variable). 

Not really, HiGHS is an LP/MIP solver that's got a QP solver bolted onto it. Hence the HighsModel class consists of a HighsLp instance and a HighsHessian instance.

>Attached here is the copy of my modifications to "highs_csharp_api.cs" file. I have modified it to handle cases where Q might not be given, or the As of the inequality/equality might not be given. And added the "qp_Iteration_Count" to the info. Also, I set the default Matrixformat to "kRowwise" I have also gotten rid of the passLp and passMip, I am now only having passModel. So my QP and LP use of the highs now look very similar. Because in my application, as I am indexing the number of wells, and the facility the flow passes through, the equalities and inequalites came naturally in compressed row form. 

Thanks, I'll have a look, but "highs_csharp_api.cs" must be backwards compatible so that code that ran before isn't broken - until we release HiGHS v2.0

> Note: We are planning to make our Mathematics Library open and freely available to everyone by the end of October. Is there anything we need to do as regards with our use of Highs?

No, the MIT license means that you can use HiGHS without giving any acknowledgement. Of course, it would be nice if you do.

**Comment by LatonCypher** [comment]
Oh. Ok. Thanks for the clarification.
________________________________

**Comment by jajhall** [comment]
@LatonCypher Thanks for your file, but it breaks the API in several ways, so we can't use it. 

Note that `passHessian` will always be necessary since an LP can be modified by adding columns, but there are no corresponding methods to update the Hessian.  

We will be sure to revise ` highs_csharp_api.cs` to incorporate QPs in a way that's consistent with the C++ API when we prepare v2.0 of HiGHS.
