### ISSUE TITLE
Add documentation page listing and naming available solvers?

### ISSUE THREAD

**Issue by pierre-haessig** [ERGO-Code/HiGHS#1915]
Hello,

I wonder whether it may be useful to add a documentation page listing the available solvers in HiGHS. In particular, this may clarify some aspects:
- provide fully developed names to the short names (`simplex`, `ipm` and `pdlp`) used in the `solver` setting option https://ergo-code.github.io/HiGHS/dev/options/definitions/#solver
- is the "Dual simplex" mentioned on the  Parallelism page (https://ergo-code.github.io/HiGHS/dev/parallel/#Dual-simplex) the same as `pdlp`? (seems yes from previous [discussion](https://github.com/ERGO-Code/HiGHS/discussions/1836#discussioncomment-9958225))
  - if yes, add the discussion comment that it is meant for GPU usage?
- finally (but this is a separate issue), a parallel interior point method is mentioned as future plans https://ergo-code.github.io/HiGHS/dev/parallel/#Future-plans. Is it indeed a work in progress?

**Comment by jajhall** [comment]
> I wonder whether it may be useful to add a documentation page listing the available solvers in HiGHS. In particular, this may clarify some aspects:

There is already some information on [Solution-algorithms](https://ergo-code.github.io/HiGHS/dev/#Solution-algorithms)

> * provide fully developed names to the short names (`simplex`, `ipm` and `pdlp`) used in the `solver` setting option https://ergo-code.github.io/HiGHS/dev/options/definitions/#solver

This isn't necessary, as these are three wholly distinct solution techniques for LP. Variants within these techniques are 

> * is the "Dual simplex" mentioned on the  Parallelism page (https://ergo-code.github.io/HiGHS/dev/parallel/#Dual-simplex) the same as `pdlp`? (seems yes from previous [discussion](https://github.com/ERGO-Code/HiGHS/discussions/1836#discussioncomment-9958225))
>   
>   * if yes, add the discussion comment that it is meant for GPU usage?

No, "Dual simplex" is a variant of the simplex algorithm, but "PDLP" is a first order method. 

I've realised that [Solution-algorithms](https://ergo-code.github.io/HiGHS/dev/#Solution-algorithms) doesn't say anything about what PDLP is, so I'll add that, stressing that PDLP is currently only available for CPUs, and may be totally uncompetitive.

> * finally (but this is a separate issue), a parallel interior point method is mentioned as future plans https://ergo-code.github.io/HiGHS/dev/parallel/#Future-plans. Is it indeed a work in progress?

Yes, and much progress has been made on the most challenging part of the development. We could make a prototype serial version available soon - that may be significantly faster than the current IPM solver on some problem classes. However, a full parallel implementation is unlikely to be available within the next 12 months.

**Comment by jajhall** [comment]
Closed by #1916

**Comment by pierre-haessig** [comment]
Thanks a lot for the feedback and PR https://github.com/ERGO-Code/HiGHS/pull/1916. I've made a minor Markdown syntax correction in https://github.com/ERGO-Code/HiGHS/pull/1939/.

Overall PR https://github.com/ERGO-Code/HiGHS/pull/1916 is fine to me, except that now that there are links from the [solvers](https://ergo-code.github.io/HiGHS/dev/solvers/) explanation page to the options [solver](https://ergo-code.github.io/HiGHS/dev/options/definitions/#option-solver) and [simplex_strategy](https://ergo-code.github.io/HiGHS/dev/options/definitions/#option-simplex_strategy), I would also add the matching back-links from these options to the solvers explanation page.

Also perhaps add "see also simplex_strategy" in the "solver" option
