### ISSUE TITLE
Non-optimal final results with options changes.

### ISSUE THREAD

**Issue by Thell** [ERGO-Code/HiGHS#1924]
While comparing three slightly different variants of a model and doing some performance tuning I noted the following:

```
Model   Option                                                  (* denotes Non-Optimal)
  A    default     21445       0      8698 100.00%   368763714.3773  368726866.78       0.01%     3454    742  10149     7096k  2448.4s
  A   soft pool    25323       0      9934 100.00%   368746531.4465  368709699.36*      0.01%     3667    531   5028     9262k  3129.0s
  A     seed       20401       0      6359 100.00%   368746568.3696  368709699.36*      0.01%     3788    718   9476     5653k  2001.6s
  
  B    default     22920       0     10121 100.00%   368746560.8499  368709699.36*      0.01%     4143    724  10087     9753k  3261.2s
  B   soft pool    18992       0      6438 100.00%   368740571.7638  368703766.29*      0.01%     3284    801   4885     6013k  2216.7s
  B     seed       17280       0      6503 100.00%   368754377.0905  368717540.94*      0.01%     3551    745  10114     6248k  2021.1s

  C    default     13636       0      4902 100.00%   368763721.2009  368726866.78       0.01%     3038    557  10069     4400k  1590.0s
  C   soft pool    13636       0      4902 100.00%   368763721.2009  368726866.78       0.01%     3038    557   4977     4400k  1650.7s
  C     seed       18554       0      5127 100.00%   368746369.6753  368709699.36*      0.01%     3000    596  10102     5143k  1829.6s
```
default = default options
soft pool = `mip_pool_soft_limit=5000`
seed = `random_seed=123456`

`.lp` files:
[VariantA.txt](https://github.com/user-attachments/files/16994759/VariantA.txt)
[VariantB.txt](https://github.com/user-attachments/files/16994757/VariantB.txt)
[VariantC.txt](https://github.com/user-attachments/files/16994758/VariantC.txt)

**Comment by jajhall** [comment]
In all cases the value of |UB-LB|/|UB| is within the (default) relative MIP gap of 0.01%

You can't expect to get UB corresponding to the optimal solution - just a value that's guaranteed to be within 0.01% of being optimal. 

Where you mark the UB value as "non-optimal" then, empirically, it's within 0.01% of being optimal, and this is guaranteed due to the values of LB for non-optimal UB values being lower than when UB is optimal.

So, not an issue

**Comment by Thell** [comment]
Ah, thanks! Sorry to take your time to look at that, I should have seen it. 🤦

**Comment by jajhall** [comment]
No problem. It's good for me to think through the argument from time to time :-)
