### ISSUE TITLE
highs.dev website down

### ISSUE THREAD

**Issue by pierre-haessig** [ERGO-Code/HiGHS#1937]
I cannot reach the https://www.highs.dev/ homepage this morning.

In case it's (semi?)-permanent, perhaps it should be removed from https://github.com/ERGO-Code/HiGHS/blob/master/README.md (“Find out more about HiGHS at https://www.highs.dev.”)

**Comment by jajhall** [comment]
Works for me just now

**Comment by odow** [comment]
Works for me too

**Comment by pierre-haessig** [comment]
OK it works also on my cell phone (should have checked this first), so that will become a ticket for the University network...
Sorry for the noise.
