### ISSUE TITLE
Compute the primal-dual integral and return it via callback

### ISSUE THREAD

**Issue by jajhall** [ERGO-Code/HiGHS#1946]

**Comment by odow** [comment]
We don't necessarily have to make it available via the callback. Just reporting it in the end `info` struct would be enough.

I was going to use the callback from Julia to estimate it.

**Comment by jajhall** [comment]
[like]  Julian Hall reacted to your message:
________________________________

**Comment by jajhall** [comment]
I was just thinking that someone will want to plot it sometimes, although that is done by parsing HiGHS.log with the Python utility

**Comment by jajhall** [comment]
Closed by #2014
