### ISSUE TITLE
Assert in feasibilityRelaxation

### ISSUE THREAD

**Issue by few** [ERGO-Code/HiGHS#1952]
I accidentally built a debug build of highs (git hash: b3c61c18b) and ran my test cases. One of them triggered this assert when calling feasibilityRelaxation (through highspy). In release mode, it runs just fine and gives a sensible result.

HiGHS/src/lp_data/HighsInterface.cpp:2049: HighsStatus Highs::elasticityFilter(double, double, double, const double*, const double*, const double*, bool, std::vector<int>&): Assertion `this->model_status_ == HighsModelStatus::kOptimal || this->model_status_ == HighsModelStatus::kUnbounded' failed.

**Comment by jajhall** [comment]
We need to model to address this issue, thanks

**Comment by jajhall** [comment]
Sorry, this code corresponds to WIP that was inadvertently merged into latest
