### ISSUE TITLE
Add EQ-UB CSR LP/MIP interface

### ISSUE THREAD

**Issue by jajhall** [ERGO-Code/HiGHS#1955]
With reference to [#2568](https://github.com/cvxpy/cvxpy/issues/2568) CVXPY holds LP/MIP in  the following format, which will probably be more natural for other users. Add this to the C++ API, C API and highspy

-  $n_{vars}$ the dimension of $x$, the variable in the problem
-  $c$ a vector such that $c^T x$ is the objective
-  $\ell, u$ such that $\ell \leq x \leq u$
-  $A, b$ some CSR matrix $A$ and vector $b$ such that $Ax + s = b$ where $s$ is a slack variable
-  A list of indices of $s$ that should be required to be $0$ and a list of indices of $s$ that should be required to be $\geq 0$
-  A list of indices of $x$ that should be required to be integer

**Comment by odow** [comment]
I'm not a massive fan of this suggestion. It's moving logic from CVXPY into HiGHS, which we then have to maintain (instead of them). Why can't they just loop over the rows?

**Comment by jajhall** [comment]
> Why can't they just loop over the rows?

It's less efficient since it's written in Python

The C++ required is minimal and won't change, so I don't see a meaningful maintenance cost.

The mindset of single-sided constraints is quite widespread, so I think this may be appreciated. 

I also favour adding the separate $A_{EQ}x=b_{EQ}$ and  $A_{UB}\le b_{UB}$ format used by SciPy

**Comment by jajhall** [comment]
> Why can't they just loop over the rows?

They are happy to do this, so I'll not create the interface unless they find that there's a meaningful overhead
