### ISSUE TITLE
Dual simplex fails at the first iteration on this LP with small coefficients

### ISSUE THREAD

**Issue by deryaozyurt** [ERGO-Code/HiGHS#1965]
When we try to solve the problem attached, we get the following output. Note that setting 'simplex_strategy' to 4 or 'simplex_scale_strategy' to 5, makes the solver progress and converge.
Running HiGHS 1.7.1: Copyright (c) 2024 HiGHS under MIT licence terms
WARNING: LP matrix packed vector contains 1176 |values| in [1.20981e-70, 9.7101e-10] less than or equal to 1e-09: ignored
Coefficient ranges:
  Matrix [1e-09, 1e+00]
  Cost   [1e+00, 1e+00]
  Bound  [0e+00, 0e+00]
  RHS    [1e-03, 1e+00]
WARNING: No semi-integer/integer variables in model with non-empty integrality
Presolving model
211 rows, 467 cols, 8741 nonzeros  0s
211 rows, 467 cols, 8741 nonzeros  0s
Presolve : Reductions: rows 211(-0); columns 467(-0); elements 8741(-0) - Not reduced
Problem not reduced by presolve: solving the LP
Using EKK dual simplex solver - serial
  Iteration        Objective     Infeasibilities num(sum)
          0     0.0000000000e+00 Pr: 211(29.8113); Du: 0(3.82173e-08) 0s
Model   status      : Not Set
HiGHS run time      :          0.01
[failingLPproblem.zip](https://github.com/user-attachments/files/17299861/failingLPproblem.zip)

**Comment by jajhall** [comment]
This issue is a consequence of the default scaling procedure in HiGHS that will be addressed in due course
