### ISSUE TITLE
Bound/RHS value warning anomalies

### ISSUE THREAD

**Issue by jajhall** [ERGO-Code/HiGHS#1969]
For `neos_3025225`, the following difference has been observed on a wide sweep of systems and compilers

> Bound  [1e+00, 1e+00] vs Bound  [1e+00,   inf]
> RHS    [1e+00, 3e+02] vs RHS    [1e+00,   inf]

Possibly due to operations with the numeric infinity being interpreted differently on different systems and compilers

**Comment by jajhall** [comment]
Assumed to be an artefact of excessive compiler optimization

**Comment by fwesselm** [comment]
I am just speculating here, but could it be possible that `std::numeric_limits<double>::infinity()` is not defined for some compilers / platforms? My question would be if there should be a check for `std::numeric_limits<double>::has_infinity`, and if this returns `false`, define `kHighsInf` as `std::numeric_limits<double>::max()`?
