### ISSUE TITLE
windows binary hangs after solution

### ISSUE THREAD

**Issue by mhechthz** [ERGO-Code/HiGHS#1970]
I'm using `HiGHS version 1.7.2 Githash 5ce7a2753. Copyright (c) 2024 HiGHS under MIT licence terms` on commandline on Windows 11.

Very frequently, calling highs with an lp-file hangs the program, even if finished with solving the actual problem:
![image](https://github.com/user-attachments/assets/a8c72996-b63d-41ea-9132-3c837ee261ed)

i.e. highs has finished but does not return to commandline (as expected):
![image](https://github.com/user-attachments/assets/15cfe221-a5fd-45be-9b54-e789cf8ca5e9)

It is independent of writing a solution or not.

**Comment by jajhall** [comment]
Fixed by #1942, but we ought to propagate this to a release @galabovaa
