### ISSUE TITLE
Add functionality to serialize (memory dump) the solver data

### ISSUE THREAD

**Issue by joaquimg** [ERGO-Code/HiGHS#1976]
This is extremely helpful for debugging issues that are non-trivial to reproduce.
Maybe this helps?
- https://github.com/thekvs/cpp-serializers
- https://isocpp.org/wiki/faq/serialization

I imagine the main challenge is to find something good under MIT.

**Comment by odow** [comment]
Someone I talked to said that their solver just traces the C API calls. I think we can do this by overloading `ccall` in the Julia wrapper. If it works, we could think about porting it to HiGHS, but the person also said that it added a lot of complication for minimal benefit.

**Comment by jajhall** [comment]
Thanks for looking into this Oscar

> but the person also said that it added a lot of complication for minimal benefit.

This is why it won't be happening any time soon in HiGHS

**Comment by odow** [comment]
I'm happy to close this issue, and I'll open one in HiGHS.jl.
