### ISSUE TITLE
Add methods to compute primal/dual directions of unboundedness 

### ISSUE THREAD

**Issue by jajhall** [ERGO-Code/HiGHS#1977]

**Comment by odow** [comment]
I think all that is missing is to populate `.coldual` following
https://github.com/jump-dev/HiGHS.jl/blob/c736c0260d9bf74dcb544e4e76ebf05a00ac0593/src/MOI_wrapper.jl#L1906-L1953

**Comment by jajhall** [comment]
> I think all that is missing is to populate `.coldual` following https://github.com/jump-dev/HiGHS.jl/blob/c736c0260d9bf74dcb544e4e76ebf05a00ac0593/src/MOI_wrapper.jl#L1906-L1953

Yes, I've done this already within https://github.com/ERGO-Code/HiGHS/tree/fix-1956-1977-1981

**Comment by jajhall** [comment]
Closed by #1984
