### ISSUE TITLE
Compute dual objective value

### ISSUE THREAD

**Issue by jajhall** [ERGO-Code/HiGHS#1981]

**Comment by odow** [comment]
Here's where we do it: https://github.com/jump-dev/HiGHS.jl/blob/c736c0260d9bf74dcb544e4e76ebf05a00ac0593/src/MOI_wrapper.jl#L2107-L2193

 * We don't include the offset if there is a ray
 * If there is a primal solution we pick the closest bound
 * If there is no primal solution (like a ray) we pick the bound corresponding to `if ( d <= 0 ) {u } else { l }`

**Comment by jajhall** [comment]
Closed by #1984
