### ISSUE TITLE
SIGILL on older x86_64 hardware

### ISSUE THREAD

**Issue by orlitzky** [ERGO-Code/HiGHS#2017]
I have an older x86_64 (Core 2 Duo) laptop that lacks the popcnt instruction. The check in `CMakeLists.txt` erroneously adds `-mpopcnt` to its compiler flags, and that eventually causes Illegal Instruction (SIGILL) crashes.

IIRC popcnt can be detected at runtime, and certainly at build time with a compile/run test. But it may be simpler these days to just trust that most people have `-march=native` in their CXXFLAGS when compiling locally.

**Comment by galabovaa** [comment]
Thank you, this is a bit that's been needing revision but it got left further back on the to do list
