### ISSUE TITLE
Feature request: pickle support

### ISSUE THREAD

**Issue by rachtsingh** [ERGO-Code/HiGHS#2031]
Python `Highs` objects are not currently pickleable:

```python
In [1]: import highspy
   ...: import numpy as np
   ...: h = highspy.Highs()

In [2]: import pickle

In [3]: with open("test.highs", "wb") as fh:
   ...:     pickle.dump(h, fh)
   ...:
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[3], line 2
      1 with open("test.highs", "wb") as fh:
----> 2     pickle.dump(h, fh)

TypeError: cannot pickle 'Highs' object
```

I think based on [this explanation](https://pybind11.readthedocs.io/en/latest/advanced/classes.html#pickling-support) we'd need to define a `py::pickle` `__getstate__` and `__setstate__` in `src/highs_bindings.cpp`, possibly around line 1081. Is that right? 

If someone could point me to the state variables in the Highs class, I'd be happy to take a stab at this (I'm pretty unfamiliar with the codebase but willing to learn).

**Comment by jajhall** [comment]
Any views @galabovaa or @mathgeekcoder ?

**Comment by mathgeekcoder** [comment]
I've no issues against *some* pickle support.  But I suspect it will be a challenge to serialize/deserialize the entire state of the solver, especially in a forwards and backwards compatible manner.  

Honestly, I suspect it would be a lot of work to implement the underlying infrastructure correctly, and I'm unclear if it's worth the effort.  That said, a limited version could essentially read/write the model - but we can already do that with existing methods.

@rachtsingh: How were you hoping to use the pickle? e.g., were you thinking to keep the model, current basis (if using simplex), current solution, branching/cut information (if integer programming), etc.?

Would a simple load/save model be sufficient?

**Comment by jajhall** [comment]
Thanks @mathgeekcoder, this resonates with my instinct in relation to the request to serialize HiGHS in C++ #1976. Unless it's totally automatic - as it might be within C++ - it would be very complicated to do, and would use resources that HiGHS simply doesn't have.
