### ISSUE TITLE
Error with `ceil` operating on a `HighsCdouble`

### ISSUE THREAD

**Issue by jajhall** [ERGO-Code/HiGHS#2041]
For the following, the assert fails.
> #include "util/HighsCDouble.h"
#include <cassert>
int main() {
    HighsCDouble a = 1e-23;
    double ceil_a;
    double double_a;
    ceil_a = double(ceil(a));
    double_a = double(a);
    assert(ceil_a >= double_a);
   // Original assert reported by user
    assert(ceil(a) >= a);
}

I'll investigate and debug, but maybe you're interested to see this @lgottwald?

**Comment by jajhall** [comment]
So, `ceil` in `HighsCDouble` hasn't changed meaningfully since originally written by @lgottwald . However, the bug was exposed by user due to the following change

https://github.com/ERGO-Code/HiGHS/commit/c57d455fc0cb7d847cb6186083825e9af3a16bb0#diff-51311a5b3434ff12770a8b899e690aeff9e8b490893fea1c5d58a46cacacf9a1R1368

In other words, the bug in `ceil` in `HighsCDouble` was always there, but now is exposed.

**Comment by jajhall** [comment]
@fwesselm I wonder if this could lie behind some presolve bugs

**Comment by fwesselm** [comment]
> @fwesselm I wonder if this could lie behind some presolve bugs

It is possible, but I think it may not be causing the issues I am currently investigating. However, I could try to replace `ceil(...)` by `std::ceil(double(...))` and see if it affects behavior.

**Comment by jajhall** [comment]
I'd rather fix `ceil(HighsCDouble x)`, and am working on it now

**Comment by fwesselm** [comment]
> I'd rather fix `ceil(HighsCDouble x)`, and am working on it now

Of course, I was just interested in seeing how many problems are affected by the bug in `ceil`.

**Comment by jajhall** [comment]
Unsurprisingly, there are values for which the current `floor(HighsCDouble x)` is also incorrect

**Comment by jajhall** [comment]
Closed by #2043
