### ISSUE TITLE
CPPCLEAN output

### ISSUE THREAD

**Issue by feldmeier** [ERGO-Code/HiGHS#206]
Here is the current output of cppclean:

- /highs/src/Highs.h:18: 'lp_data/HighsModelBuilder.h' does not need to be #included
- /highs/src/Highs.h:22: 'mip/SolveMip.h' does not need to be #included; use a forward declaration instead
- /highs/src/interfaces/GAMS.cpp:9: unable to find 'gmomcc.h'
- /highs/src/interfaces/GAMS.cpp:10: unable to find 'gevmcc.h'
- /highs/src/interfaces/GAMS.cpp:48: 'gevprint' not found in any directly #included header
- /highs/src/interfaces/GAMS.cpp:57: 'gevlog' not found in any directly #included header
- /highs/src/interfaces/GAMS.cpp:277: 'his_Initialize' not found in any directly #included header
- /highs/src/interfaces/GAMS.cpp:283: 'his_Finalize' not found in any directly #included header
- /highs/src/interfaces/GAMS.cpp:289: 'hisXCreate' not found in any directly #included header
- /highs/src/interfaces/GAMS.cpp:296: 'hiscreate' not found in any directly #included header
- /highs/src/interfaces/GAMS.cpp:309: 'hisXFree' not found in any directly #included header
- /highs/src/interfaces/GAMS.cpp:321: 'hisfree' not found in any directly #included header
- /highs/src/interfaces/GAMS.cpp:335: 'C__hisXAPIVersion' not found in any directly #included header
- /highs/src/interfaces/GAMS.cpp:341: 'D__hisXAPIVersion' not found in any directly #included header
- /highs/src/interfaces/GAMS.cpp:347: 'C__hisXCheck' not found in any directly #included header
- /highs/src/interfaces/GAMS.cpp:349: 'D__hisXCheck' not found in any directly #included header
- /highs/src/interfaces/GAMS.cpp:351: 'C__hisReadyAPI' not found in any directly #included header
- /highs/src/interfaces/GAMS.cpp:375: 'C__hisCallSolver' not found in any directly #included header
- /highs/src/interfaces/GAMS.cpp:431: 'C__hisHaveModifyProblem' not found in any directly #included header
- /highs/src/interfaces/GAMS.cpp:433: 'C__hisModifyProblem' not found in any directly #included header
- /highs/src/interfaces/OsiHiGHSSolverInterface.cpp:19: unable to find 'HighsLp.h'
- /highs/src/interfaces/OsiHiGHSSolverInterface.cpp:20: unable to find 'HighsOptions.h'
- /highs/src/interfaces/OsiHiGHSSolverInterface.cpp:21: unable to find 'HighsStatus.h'
- /highs/src/interfaces/OsiHiGHSSolverInterface.cpp:26: unable to find 'CoinWarmStartBasis.hpp'
- /highs/src/interfaces/OsiHiGHSSolverInterface.hpp:17: unable to find 'OsiSolverInterface.hpp'
- /highs/src/interfaces/OsiHiGHSSolverInterface.hpp:21: 'HighsLp' not used
- /highs/src/interfaces/highs_c_api.cpp:92: 'Highs_setHighsOptionValue' not found in expected header '- /highs/src/interfaces/highs_c_api.h' or any other directly #included header
- /highs/src/interfaces/highs_c_api.h:88: 'Highs_setOptionValue' declared but not defined
- /highs/src/io/Filereader.h:17: 'lp_data/HighsLp.h' does not need to be #included; use a forward declaration instead
- /highs/src/io/Filereader.h:18: 'lp_data/HighsModelBuilder.h' does not need to be #included; use a forward declaration instead
- /highs/src/io/Filereader.h:19: 'lp_data/HighsOptions.h' does not need to be #included; use a forward declaration instead
- /highs/src/io/FilereaderEms.h:21: 'io/HighsIO.h' does not need to be #included
- /highs/src/io/FilereaderLp.cpp:28: 'emptyTokenQueue' not found in expected header '- /highs/src/io/FilereaderLp.h' or any other directly #included header
- /highs/src/io/HMpsFF.h:34: 'lp_data/HConst.h' does not need to be #included
- /highs/src/io/HToyIO.cpp:26: 'cmath' already #included on line 16
- /highs/src/io/HToyIO.cpp:27: 'cstdio' already #included on line 17
- /highs/src/io/HToyIO.cpp:29: 'cstring' already #included on line 18
- /highs/src/io/HToyIO.cpp:43: 'readToy_LP_c' not found in expected header '- /highs/src/io/HToyIO.h' or any other directly #included header
- /highs/src/io/HighsIO.cpp:20: 'lp_data/HighsLp.h' already #included in '- /highs/src/io/HighsIO.h'
- /highs/src/io/HighsIO.cpp:23: static data 'logfile'
- /highs/src/io/HighsIO.cpp:24: static data 'output'
- /highs/src/io/HighsIO.cpp:25: static data 'message_level'
- /highs/src/io/HighsIO.cpp:26: static data 'printmsgcb'
- /highs/src/io/HighsIO.cpp:27: static data 'logmsgcb'
- /highs/src/io/HighsIO.cpp:28: static data 'msgcb_data'
- /highs/src/io/HighsIO.cpp:30: static data 'msgbuffer'
- /highs/src/io/HighsIO.h:17: 'lp_data/HighsLp.h' does not need to be #included
- /highs/src/io/LoadProblem.h:24: 'lp_data/HighsLpUtils.h' does not need to be #included
- /highs/src/lp_data/Highs.cpp:21: unable to find 'HConfig.h'
- /highs/src/lp_data/Highs.cpp:24: 'lp_data/HighsLp.h' already #included in '- /highs/src/Highs.h'
- /highs/src/lp_data/Highs.cpp:27: 'lp_data/HighsStatus.h' already #included in '- /highs/src/Highs.h'
- /highs/src/lp_data/HighsLp.cpp:15: 'lp_data/HConst.h' already #included in '- /highs/src/lp_data/HighsLp.h'
- /highs/src/lp_data/HighsLp.h:22: unable to find 'HConfig.h'
- /highs/src/lp_data/HighsLpUtils.cpp:19: 'HConfig.h' already #included in '- /highs/src/lp_data/HighsLpUtils.h'
- /highs/src/lp_data/HighsLpUtils.cpp:19: unable to find 'HConfig.h'
- /highs/src/lp_data/HighsLpUtils.cpp:23: 'lp_data/HighsStatus.h' already #included in '- /highs/src/lp_data/HighsLpUtils.h'
- /highs/src/lp_data/HighsLpUtils.cpp:1566: 'getBoundType' not found in expected header '- /highs/src/lp_data/HighsLpUtils.h' or any other directly #included header
- /highs/src/lp_data/HighsLpUtils.cpp:1721: 'convertBasis' not found in expected header '- /highs/src/lp_data/HighsLpUtils.h' or any other directly #included header
- /highs/src/lp_data/HighsLpUtils.h:17: unable to find 'HConfig.h'
- /highs/src/lp_data/HighsLpUtils.h:18: 'io/Filereader.h' does not need to be #included
- /highs/src/lp_data/HighsLpUtils.h:19: 'lp_data/HighsLp.h' does not need to be #included; use a forward declaration instead
- /highs/src/lp_data/HighsLpUtils.h:20: 'lp_data/HighsOptions.h' does not need to be #included; use a forward declaration instead
- /highs/src/lp_data/HighsModelBuilder.h:17: 'lp_data/HighsLp.h' does not need to be #included; use a forward declaration instead
- /highs/src/lp_data/HighsModelObject.h:14: 'lp_data/HighsOptions.h' does not need to be #included; use a forward declaration instead
- /highs/src/lp_data/HighsModelObject.h:18: 'util/HighsTimer.h' does not need to be #included; use a forward declaration instead
- /highs/src/lp_data/HighsModelObjectUtils.h:19: unable to find 'HConfig.h'
- /highs/src/lp_data/HighsModelObjectUtils.h:20: 'io/HighsIO.h' does not need to be #included
- /highs/src/lp_data/HighsModelObjectUtils.h:22: 'lp_data/HighsModelObject.h' does not need to be #included
- /highs/src/lp_data/HighsModelUtils.cpp:18: 'HConfig.h' already #included in '- /highs/src/lp_data/HighsModelUtils.h'
- /highs/src/lp_data/HighsModelUtils.cpp:18: unable to find 'HConfig.h'
- /highs/src/lp_data/HighsModelUtils.cpp:78: 'ch4VarStatus' not found in expected header '- /highs/src/lp_data/HighsModelUtils.h' or any other directly #included header
- /highs/src/lp_data/HighsModelUtils.h:17: unable to find 'HConfig.h'
- /highs/src/lp_data/HighsModelUtils.h:18: 'Highs.h' does not need to be #included
- /highs/src/lp_data/HighsOptions.cpp:20: 'optionEntryType2string' not found in expected header '- /highs/src/lp_data/HighsOptions.h' or any other directly #included header
- /highs/src/lp_data/HighsOptions.cpp:510: 'setMessageLevelValue' not found in expected header '- /highs/src/lp_data/HighsOptions.h' or any other directly #included header
- /highs/src/lp_data/HighsOptions.h:19: 'io/HighsIO.h' does not need to be #included
- /highs/src/lp_data/HighsOptions.h:21: 'lp_data/HighsLp.h' does not need to be #included
- /highs/src/lp_data/HighsOptions.h:23: 'presolve/Presolve.h' does not need to be #included
- /highs/src/lp_data/HighsOptions.h:24: 'simplex/SimplexConst.h' does not need to be #included
- /highs/src/lp_data/HighsRuntimeOptions.h:7: 'io/LoadProblem.h' does not need to be #included
- /highs/src/lp_data/HighsRuntimeOptions.h:9: 'lp_data/HConst.h' does not need to be #included
- /highs/src/lp_data/HighsRuntimeOptions.h:11: 'lp_data/HighsStatus.h' does not need to be #included
- /highs/src/mip/SolveMip.h:8: 'lp_data/HighsLp.h' does not need to be #included
- /highs/src/mip/SolveMip.h:9: 'lp_data/HighsStatus.h' does not need to be #included
- /highs/src/presolve/FindFeasibility.cpp:15: 'isEqualityProblem' not found in expected header '- /highs/src/presolve/FindFeasibility.h' or any other directly #included header
- /highs/src/presolve/FindFeasibility.cpp:22: 'getAtb' not found in expected header '- /highs/src/presolve/FindFeasibility.h' or any other directly #included header
- /highs/src/presolve/FindFeasibility.cpp:34: 'getAtLambda' not found in expected header '- /highs/src/presolve/FindFeasibility.h' or any other directly #included header
- /highs/src/presolve/FindFeasibility.cpp:49: 'getQuadraticObjective' not found in expected header '- /highs/src/presolve/FindFeasibility.h' or any other directly #included header
- /highs/src/presolve/FindFeasibility.cpp:71: 'printMinorIterationDetails' not found in expected header '- /highs/src/presolve/FindFeasibility.h' or any other directly #included header
- /highs/src/presolve/FindFeasibility.cpp:262: 'chooseStartingMu' not found in expected header '- /highs/src/presolve/FindFeasibility.h' or any other directly #included header
- /highs/src/presolve/FindFeasibility.cpp:271: 'initialize' not found in expected header '- /highs/src/presolve/FindFeasibility.h' or any other directly #included header
- /highs/src/presolve/FindFeasibility.h:4: 'lp_data/HighsLp.h' does not need to be #included; use a forward declaration instead
- /highs/src/presolve/HPreData.cpp:15: 'lp_data/HConst.h' already #included in '- /highs/src/presolve/HPreData.h'
- /highs/src/simplex/HApp.h:22: unable to find 'HConfig.h'
- /highs/src/simplex/HApp.h:24: 'lp_data/HighsLpUtils.h' does not need to be #included
- /highs/src/simplex/HApp.h:29: 'util/HighsUtils.h' does not need to be #included
- /highs/src/simplex/HApp.h:33: 'simplex/SimplexConst.h' does not need to be #included
- /highs/src/simplex/HCrash.h:20: 'lp_data/HighsModelObject.h' does not need to be #included; use a forward declaration instead
- /highs/src/simplex/HCrash.h:22: 'HMatrix' not used
- /highs/src/simplex/HDual.cpp:28: 'lp_data/HighsModelObject.h' already #included in '- /highs/src/simplex/HDual.h'
- /highs/src/simplex/HDual.cpp:29: 'simplex/HCrash.h' already #included in '- /highs/src/simplex/HDual.h'
- /highs/src/simplex/HDual.cpp:31: 'simplex/HSimplex.h' already #included in '- /highs/src/simplex/HDual.h'
- /highs/src/simplex/HDual.cpp:1993: static data 'previous_updated_dual_objective_value'
- /highs/src/simplex/HDual.cpp:1994: static data 'previous_dual_objective_value'
- /highs/src/simplex/HDual.h:21: unable to find 'HConfig.h'
- /highs/src/simplex/HDual.h:23: 'simplex/HCrash.h' does not need to be #included
- /highs/src/simplex/HDual.h:27: 'simplex/HSimplex.h' does not need to be #included
- /highs/src/simplex/HDualRHS.cpp:22: 'lp_data/HighsModelObject.h' already #included in '- /highs/src/simplex/HDualRHS.h'
- /highs/src/simplex/HDualRHS.h:19: 'lp_data/HighsModelObject.h' does not need to be #included; use a forward declaration instead
- /highs/src/simplex/HDualRow.cpp:15: 'lp_data/HighsModelObject.h' already #included in '- /highs/src/simplex/HDualRow.h'
- /highs/src/simplex/HDualRow.h:20: 'lp_data/HighsModelObject.h' does not need to be #included; use a forward declaration instead
- /highs/src/simplex/HFactor.cpp:30: 'solveMatrixT' not found in expected header '- /highs/src/simplex/HFactor.h' or any other directly #included header
- /highs/src/simplex/HFactor.cpp:56: 'solveHyper' not found in expected header '- /highs/src/simplex/HFactor.h' or any other directly #included header
- /highs/src/simplex/HFactor.h:21: unable to find 'HConfig.h'
- /highs/src/simplex/HMatrix.cpp:15: 'HConfig.h' already #included in '- /highs/src/simplex/HMatrix.h'
- /highs/src/simplex/HMatrix.cpp:15: unable to find 'HConfig.h'
- /highs/src/simplex/HMatrix.h:19: unable to find 'HConfig.h'
- /highs/src/simplex/HPrimal.cpp:17: 'simplex/HSimplex.h' already #included in '- /highs/src/simplex/HPrimal.h'
- /highs/src/simplex/HPrimal.h:17: unable to find 'HConfig.h'
- /highs/src/simplex/HPrimal.h:18: 'lp_data/HighsModelObject.h' does not need to be #included; use a forward declaration instead
- /highs/src/simplex/HPrimal.h:19: 'simplex/HSimplex.h' does not need to be #included
- /highs/src/simplex/HSimplex.cpp:16: 'HConfig.h' already #included in '- /highs/src/simplex/HSimplex.h'
- /highs/src/simplex/HSimplex.cpp:16: unable to find 'HConfig.h'
- /highs/src/simplex/HSimplex.cpp:18: 'lp_data/HighsStatus.h' already #included in '- /highs/src/simplex/HSimplex.h'
- /highs/src/simplex/HSimplex.cpp:1108: static data 'numLargeCo'
- /highs/src/simplex/HSimplex.cpp:1109: static data 'largeCostFlag'
- /highs/src/simplex/HSimplex.cpp:1110: static data 'largeCostScale'
- /highs/src/simplex/HSimplex.h:17: unable to find 'HConfig.h'
- /highs/src/simplex/HSimplex.h:18: 'lp_data/HighsModelObject.h' does not need to be #included; use a forward declaration instead
- /highs/src/simplex/HSimplex.h:19: 'lp_data/HighsOptions.h' does not need to be #included
- /highs/src/simplex/HVector.cpp:19: unable to find 'stdio.h'
- /highs/src/simplex/HighsSimplexInterface.cpp:15: 'HConfig.h' already #included in '- /highs/src/simplex/HighsSimplexInterface.h'
- /highs/src/simplex/HighsSimplexInterface.cpp:15: unable to find 'HConfig.h'
- /highs/src/simplex/HighsSimplexInterface.cpp:20: 'simplex/HSimplex.h' already #included in '- /highs/src/simplex/HighsSimplexInterface.h'
- /highs/src/simplex/HighsSimplexInterface.h:20: unable to find 'HConfig.h'
- /highs/src/simplex/HighsSimplexInterface.h:21: 'lp_data/HighsModelObject.h' does not need to be #included; use a forward declaration instead
- /highs/src/simplex/HighsSimplexInterface.h:22: 'simplex/HSimplex.h' does not need to be #included
- /highs/src/simplex/HighsSimplexInterface.h:23: 'simplex/HVector.h' does not need to be #included
- /highs/src/test/KktChStep.cpp:16: 'lp_data/HConst.h' already #included in '- /highs/src/test/KktChStep.h'
- /highs/src/test/KktCheck.cpp:19: 'lp_data/HConst.h' already #included in '- /highs/src/test/KktCheck.h'
- /highs/src/util/HighsUtils.cpp:21: 'HConfig.h' already #included in '- /highs/src/util/HighsUtils.h'
- /highs/src/util/HighsUtils.cpp:21: unable to find 'HConfig.h'
- /highs/src/util/HighsUtils.h:20: unable to find 'HConfig.h'

**Comment by svigerske** [comment]
Regarding GAMS.cpp, the one for gevprint and gevlog should be gone now. The other "not found in any header" I'll fix some later time as I was thinking to do these functions differently anyway.
Unless someone says this is really important. :)

**Comment by feldmeier** [comment]
No, this is not a priority - thanks for your updates to the GAMS interface!

**Comment by jajhall** [comment]
We should probably do this again sometime, but this output is too out-of-date to be useful
