### ISSUE TITLE
Another bug in the free format read

### ISSUE THREAD

**Issue by jajhall** [ERGO-Code/HiGHS#21]
I've found another bug in the free format read. The (new) pure problems contain a final empty column which appears as (eg - in pure010.mps)

    OBJECTIVE_CONSTANT    Obj                           17385349161.3756

This leads to failure in

    for (int i=0; i<nCols_in; i++) {
        if (Astart[i] > Astart[i+1]) {
            std::cout<<"Error filling in matrix data\n";
            return 1;
        }
    }

because the final three entries of Astart are 539040, 0 and 539041

If I delete the OBJECTIVE_CONSTANT line from the MPS file then the model loads fine - and I'll do this to perform my experiements.

Still, like the "multiple N-row" bug, it should be fixed at some point [although it's less inconvenient]

**Comment by galabovaa** [comment]
pure010 is a special case. Warning added.
