### ISSUE TITLE
Release tags and versions

### ISSUE THREAD

**Issue by matbesancon** [ERGO-Code/HiGHS#212]
To make versionning of HiGHS easier, it would be great to start tagging versions and adding corresponding github releases.
Not sure what the best tool is for this in C++, if any. Conan possibly

**Comment by jajhall** [comment]
Indeed, it's pretty much time that we started doing this. I want to be a bit more confident about all the model modification methods before formally announcing HiGHS as being "formally released". Thanks for the tip on Conan!

**Comment by matbesancon** [comment]
Using [semver](https://semver.org/), the releases with notation v0.x.y are exactly done for that (pre-releases without officially stable API)

**Comment by galabovaa** [comment]
Official release coming up soon.
