### ISSUE TITLE
Remove or adapt architecture-specific code

### ISSUE THREAD

**Issue by matbesancon** [ERGO-Code/HiGHS#215]
Trying to cross-compile HiGHS for several configurations (architecture, OS, libc and compiler) in https://github.com/matbesancon/HiGHSBuilder

Several issues occurred, I'll post them in detail soon. The most obvious one is the header x86intrin.h, which is directly blocking. The functions used from there should be wrapped with a preprocessing directive conditioned on the target.

**Comment by matbesancon** [comment]
Trying to build Windows x86 with gcc4, there is an error due to a comparison between pointer and int:

```
In file included from /workspace/srcdir/HiGHS/check/TestIO.cpp:5:0:
/workspace/srcdir/HiGHS/external/catch.hpp: In instantiation of 'bool Catch::compareNotEqual(const LhsT&, RhsT&&) [with LhsT = char*; RhsT = const long long int&]':
/workspace/srcdir/HiGHS/external/catch.hpp:1560:50:   required from 'const Catch::BinaryExpr<LhsT, const RhsT&> Catch::ExprLhs<LhsT>::operator!=(const RhsT&) [with RhsT = long long int; LhsT = char* const&]'
/workspace/srcdir/HiGHS/check/TestIO.cpp:57:5:   required from here
/workspace/srcdir/HiGHS/external/catch.hpp:1534:96: error: ISO C++ forbids comparison between pointer and integer [-fpermissive]
     auto compareNotEqual( LhsT const& lhs, RhsT&& rhs ) -> bool { return static_cast<bool>(lhs != rhs); }
                                                                                                ^
make[2]: *** [check/CMakeFiles/unit_tests.dir/build.make:106: check/CMakeFiles/unit_tests.dir/TestIO.cpp.obj] Error 1
make[1]: *** [CMakeFiles/Makefile2:248: check/CMakeFiles/unit_tests.dir/all] Error 2
make: *** [Makefile:163: all] Error 2
ERROR: LoadError: Build for highs on x86_64-w64-mingw32-gcc4 did not complete successfully
```

**Comment by matbesancon** [comment]
All the code that depends on `x86intrin.h` blocks other architectures to be used

**Comment by matbesancon** [comment]
When replacing libc with musl:

```
In file included from /opt/x86_64-linux-musl/lib/gcc/x86_64-linux-musl/4.8.5/include/xmmintrin.h:38:0,
                 from /opt/x86_64-linux-musl/lib/gcc/x86_64-linux-musl/4.8.5/include/x86intrin.h:34,
                 from /workspace/srcdir/HiGHS/src/simplex/HTimerPre.h:25,
                 from /workspace/srcdir/HiGHS/src/presolve/Presolve.h:26,
                 from /workspace/srcdir/HiGHS/src/lp_data/HighsOptions.h:23,
                 from /workspace/srcdir/HiGHS/src/io/Filereader.h:19,
                 from /workspace/srcdir/HiGHS/src/io/Filereader.cpp:10:
/opt/x86_64-linux-musl/lib/gcc/x86_64-linux-musl/4.8.5/include/mm_malloc.h:34:64: error: declaration of 'int posix_memalign(void**, size_t, size_t) throw ()' has a different exception specifier
 extern "C" int posix_memalign (void **, size_t, size_t) throw ();
```

**Comment by feldmeier** [comment]
Thanks for those - I will take a look and see how we can make the code architecture-independent. 
Are those issues blocking you from using Highs on your platform, or was this just a test?

**Comment by matbesancon** [comment]
>  Are those issues blocking you from using Highs on your platform, or was this just a test?

Not me directly, but I was using [BinaryBuilder](https://github.com/JuliaPackaging/BinaryProvider.jl) to directly build the library for different platforms and architectures. For the moment, Linux x86 with libc and gcc is fine, so it's usable for me, just means the [HiGHS.jl](https://github.com/matbesancon/HiGHS.jl) wrapper is usable for this configuration only.

**Comment by jajhall** [comment]
Now that x86intrin.h has been eliminated from HiGHS, I guess that this issue can be closed. @matbesancon : please confirm and close.

**Comment by matbesancon** [comment]
seems good yes, I will try to re-run the full cross-compilation to see if some things still pop out

**Comment by matbesancon** [comment]
So I managed to get all working but windows and powerpc. Sorry I kind of created a duplicate in https://github.com/ERGO-Code/HiGHS/issues/311

**Comment by jajhall** [comment]
Thanks @galabovaa is on the case, regarding Windows!

**Comment by matbesancon** [comment]
Cool, regarding powerpc, this is an error on my side in the cross-compilation (the linking part), should be fixed soon

**Comment by odow** [comment]
Thanks to @galabovaa, we successfully built HiGHS on every platform supported by Julia: https://github.com/JuliaPackaging/Yggdrasil/pull/2467. I guess that means this issue can be closed.

There was one warning: https://github.com/JuliaPackaging/Yggdrasil/pull/2467#issuecomment-769443976

Are you explicitly using AVX2 instructions somewhere?

**Comment by odow** [comment]
I think this can be closed. We're successfully building HiGHS on every platform from the latest commits.
