### ISSUE TITLE
Expose a get function for objective sense

### ISSUE THREAD

**Issue by matbesancon** [ERGO-Code/HiGHS#222]
There is no current way to get the objective sense (minimize or maximize), only to change it.

Also (I can put that in a separate issue if you prefer), it would be good to use the enum type instead of int when taking a sense as argument in a function.

**Comment by matbesancon** [comment]
This is also the case for option, one can set an option value but not get them

**Comment by matbesancon** [comment]
Similarly, it would be nice to have a function to set all coefficients to one similar value (possibly in a mask / set), thus avoiding to pass a full array.

**Comment by jajhall** [comment]
The C interface now has getObjectiveSense to pass back the objective sense. It's done as an int, but the objective sense is now an enum class internally. Just pushed to master

I've seen your comments on passing the enums through the C interface, and some of the subsequent discussion. @galabovaa , @feldmeier and I will discuss this.

**Comment by matbesancon** [comment]
Cool thanks!

**Comment by jajhall** [comment]
"Similarly, it would be nice to have a function to set all coefficients to one similar value (possibly in a mask / set), thus avoiding to pass a full array."

Are you thinking about just bounds, or other data?

**Comment by matbesancon** [comment]
Sorry this issue had slept by, yes for bounds
