### ISSUE TITLE
Install libs in lib64 directory on some systems

### ISSUE THREAD

**Issue by ycollet** [ERGO-Code/HiGHS#234]
On Fedora 64 bits, libs are installed in lib64 directory.
Cmake provides a set of macro to manage this:
```
include(GNUInstallDirs)
```
After that, you can install libs in:
```
set(libdir           "${CMAKE_INSTALL_PREFIX}/${CMAKE_INSTALL_LIBDIR}")
```

**Comment by galabovaa** [comment]
include(GNUInstallDirs) is now added to master. Please open a new issue if you get any further problems.
