### ISSUE TITLE
Presolving maximization problems

### ISSUE THREAD

**Issue by jajhall** [ERGO-Code/HiGHS#272]
Presolve appears to ignore lp.sense_, presolving to empty the following irreducible maximization LP

HighsLp lp;
  int lp_nnz = 4;
  lp.numRow_ = 2;
  lp.numCol_ = 2;
  lp.colCost_.resize(lp.numCol_);
  lp.colLower_.resize(lp.numCol_);
  lp.colUpper_.resize(lp.numCol_);
  lp.Astart_.resize(lp.numCol_+1);
  lp.Aindex_.resize(lp_nnz);
  lp.Avalue_.resize(lp_nnz);
  lp.rowLower_.resize(lp.numRow_);
  lp.rowUpper_.resize(lp.numRow_);
  lp.colCost_[0] = 3;
  lp.colCost_[1] = 2;
  lp.colLower_[0] = 0;
  lp.colLower_[1] = 0;
  lp.colUpper_[0] = HIGHS_CONST_INF;
  lp.colUpper_[1] = HIGHS_CONST_INF;
  lp.rowLower_[0] = -HIGHS_CONST_INF;
  lp.rowLower_[1] = -HIGHS_CONST_INF;
  lp.rowUpper_[0] = 23;
  lp.rowUpper_[1] = 10;
  lp.Astart_[0] = 0;
  lp.Astart_[1] = 2;
  lp.Astart_[2] = 4;
  lp.Aindex_[0] = 0;
  lp.Aindex_[1] = 1;
  lp.Aindex_[2] = 0;
  lp.Aindex_[3] = 1;
  lp.Avalue_[0] = 3;
  lp.Avalue_[1] = 5;
  lp.Avalue_[2] = 6;
  lp.Avalue_[3] = 2;
  lp.sense_ = -1;

**Comment by galabovaa** [comment]
Fixed in master.
