### ISSUE TITLE
Supress output from presolve

### ISSUE THREAD

**Issue by mckib2** [ERGO-Code/HiGHS#275]
It looks like at one point the output was suppressed when building release, is it possible to add this if statement back in?

From `src/presolve/Presolve.cpp` (offending lines [here](https://github.com/ERGO-Code/HiGHS/blob/4598c265262babbba4a7ed0228105aaeea6d59ca/src/presolve/Presolve.cpp#L166)):
> ...
  timer.updateInfo();
  //  if ((std::string)CMAKE_BUILD_TYPE == "debug")      <---- this line
  timer.reportClocks();
  return status;
   ...

Could even do a pound define?

> ...
    #ifdef DEBUG     <-- or whatever the variable is to tell whether it's RELEASE or DEBUG
    timeer.reportClocks()
    #endif
    ...

**Comment by galabovaa** [comment]
I removed the code from master, that was a last minute timing dump which should never have been there. Can you please make sure you no longer get the issue?

**Comment by mckib2** [comment]
Looks good!  There is now no output when `presolve=true` and `solver="simplex"`.  Thanks!
