### ISSUE TITLE
Iteration limit

### ISSUE THREAD

**Issue by mckib2** [ERGO-Code/HiGHS#286]
Setting `simplex_iteration_limit` appears to have no effect.

Also, there does not appear to be an analogue for IPM, e.g., `ipm_iteration_limit`?

**Comment by jajhall** [comment]
Indeed, Setting simplex_iteration_limit has no effect. I held off because I need to decide whether it should be a limit on total iterations for a model - assuming re-solves - or a limit on each individual call. I'll see how the commercial solvers interpret it.

**Comment by jajhall** [comment]
For Xpress:

**LPITERLIMIT**
Description Simplex: The maximum number of iterations that will be performed before the
optimization process terminates. For MIP problems, this is the maximum total number of
iterations over all nodes explored by the Branch and Bound method.

For Gurobi and CPLEX, the definition is opaque, so I'll go with the Xpress definition.

**Comment by mckib2** [comment]
I think total number of iterations including resolves is a reasonable interpretation.

**Comment by mckib2** [comment]
I believe this has been resolved.
