### ISSUE TITLE
Assert HMpsFF.h:815

### ISSUE THREAD

**Issue by jajhall** [ERGO-Code/HiGHS#29]
Reading model pure010 yields assert

highs: /home/jajhall/HiGHS/src/HMpsFF.h:815: MpsParser::parseBounds(boost::iostreams::filtering_istream&)::<lambda(std::__cxx11::string)>: Assertion `mit != colname2idx.end()' failed.

Seems to read the model OK when not compiled with  -DCMAKE_BUILD_TYPE=DEBUG but worth checking

**Comment by galabovaa** [comment]
pure010 is a special case. Warning added.
