### ISSUE TITLE
BUG: IPX+presolve gives error

### ISSUE THREAD

**Issue by mckib2** [ERGO-Code/HiGHS#306]
Based on failing unit test `test_bug_6690` [here](https://github.com/scipy/scipy/blob/master/scipy/optimize/tests/test_linprog.py#L1034)

Output from `./highs --solver ipm --presolve on test6690.mps`:
```
16:59:19 [INFO   ] Presolve reductions: columns 3(-7); rows 1(-5) elements 3(-9)
16:59:19 [INFO   ] Solving the presolved LP
16:59:19 [INFO   ] IPX model has 1 rows, 3 columns and 3 nonzeros
IPX version 1.0
16:59:19 [ERROR  ] Ipx: Invalid input - invalid vector
HiGHS status: Error
```

Output from `./highs --solver ipm --presolve off test6690.mps`:
```
17:00:34 [INFO   ] Ipx: IPM       optimal
17:00:34 [INFO   ] Ipx: Crossover optimal
17:00:34 [INFO   ] HiGHS basic solution: Analysis - Solving LP without presolve or with basis
17:00:34 [INFO   ] HiGHS basic solution: 10 IPM iterations; Objective = -1.191
17:00:34 [INFO   ] Infeasibilities: Pr 0(Max 5.551e-17, Sum 5.551e-17); Du 0(Max 0, Sum 0); Status: Optimal
Postsolve  : 0
Time       : 0.00551
For LP         test6690: Solve original LP 0.00549 ( 99%)

Model   status      : Optimal
Simplex   iterations: 0
IPM       iterations: 10
Objective value     : -1.191000e+00
```

Simplex solves correctly whether or not presolve is on/off.

MPS file:
[test6690.txt](https://github.com/ERGO-Code/HiGHS/files/4463664/test6690.txt)

Resolved by #314

**Comment by jajhall** [comment]
Interesting: [@galabovaa] presolve gives machine precision inconsistency in bounds of 0.4 so that LB>UB (by 5.551e-17).

Added method cleanBounds to remove such minor inconsistencies [less then primal feasibility tolerance] in bounds after presolve and return error if large. 

Will merge https://github.com/ERGO-Code/HiGHS/tree/presolveCleanBounds into master tomorrow, but need to go to bed. You're welcome to merge it into your own master now, of course.

**Comment by mckib2** [comment]
@jajhall Get some rest!  This one gave scipy's linear program solver some grief a little while back, so we were interested to see that it also tripped up HiGHS!

**Comment by mckib2** [comment]
I've tested branch and can confirm the fix.  I'll wait for merge into master to close the issue.

**Comment by jajhall** [comment]
Merged branch into master
