### ISSUE TITLE
Example for measuring time

### ISSUE THREAD

**Issue by matbesancon** [ERGO-Code/HiGHS#321]
I would like to fetch the total solving time (including presolve + simplex), I understand that the way time is measured in the project has changed recently? It could be an interesting addition to the c example

**Comment by jajhall** [comment]
No problem. I've got a clock that measures the time spent in calls to highs.run() and recently added to the Highs class a method to read it. I'll add one to the C interface.

**Comment by jajhall** [comment]
It'll take a few days for this to be in master, but you can get it (as Highs_getHighsRunTime) from https://github.com/ERGO-Code/HiGHS/commits/RunIPXsilently

**Comment by jajhall** [comment]
Although I'm waiting for the branch to be merged into master, the following is now stable and contains getHighsRunTime(), as does the C API
https://github.com/ERGO-Code/HiGHS/tree/master

**Comment by jajhall** [comment]
Fixed by recent merge into master
