### ISSUE TITLE
Silently running IPM

### ISSUE THREAD

**Issue by mckib2** [ERGO-Code/HiGHS#323]
IPM solver appears to have no option to suppress output.

Looking through issues, looks like this was discussed, see https://github.com/ERGO-Code/HiGHS/issues/210#issuecomment-545498693

Is it possible to run silently?

**Comment by jajhall** [comment]
It'll take a few days for this to be in master, but IPX now runs silently if you set the HiGHS output to NULL using
https://github.com/ERGO-Code/HiGHS/commits/RunIPXsilently

**Comment by mckib2** [comment]
I'll wait till merge to master to close out, thanks for looking at this

**Comment by mckib2** [comment]
Any movement on this issue?

**Comment by jajhall** [comment]
Sorry, it's stuck in a branch that I've allowed to grow for too long! I need to close it out so I can get on with other work, so I'll keep you posted.

**Comment by jajhall** [comment]
Fixed by recent merge into master

**Comment by mckib2** [comment]
This appears to be working in latest master
