### ISSUE TITLE
Non-ascii characters in CMakeLists.txt

### ISSUE THREAD

**Issue by mckib2** [ERGO-Code/HiGHS#345]
Probably best to stick with either UTF-8 or ASCII for compatibility.  A non-ASCII character snuck its way into `CMakeLists.txt` recently.

Output from `chardet CMakeLists.txt`:
```
CMakeLists.txt: ISO-8859-1 with confidence 0.73
```

grep for non-ASCII characters `grep --color='auto' -P -n "[\x80-\xFF]" CMakeLists.txt`:
```
286:# # to header-only.
```

Printed raw:
```
...
For methods stick\n# #\xa0to header-only.\n# add_subdirectory(dev_presolve)\n
...
```

This is only a small thing so if it is ignored it's understandable.  We have tooling that scrapes information from `CMakeLists.txt` in order to do the build since we don't have cmake as a dependency in scipy.  This fails with how some versions of Python decode files when non-ascii characters are used.

We will try to be more robust when reading files, but like I mentioned, probably best to checkin/out with UTF-8 or ASCII for consistency.  Please let me know what your decision of file encoding is so I can close out this issue

**Comment by jajhall** [comment]
Character removed now, and I've got a whole-HiGHS grep for non-ASCII characters now!

**Comment by jajhall** [comment]
Any reason not to stick to just ASCII @galabovaa @feldmeier ?

**Comment by mckib2** [comment]
I appreciate you looking at this.  Please continue the conversation, but I will mark as closed as the issue has been resolved.
