### ISSUE TITLE
BUG: invalid message_level does not trigger warning

### ISSUE THREAD

**Issue by mckib2** [ERGO-Code/HiGHS#354]
Invalid `message_level` does not produce warning/error message:

For example, this options file
```
message_level = 3
```

**Comment by mckib2** [comment]
This appears to be due to the fact that integer options are checked for bounds, not discrete values.  This is the only option I'm aware of that has a bit-like convention, so choosing 3, 5, or 6 will fail to be caught.

**Comment by jajhall** [comment]
message_level = 3 _is_ valid. 

message_level is a bit mask. See enum HighsPrintMessageLevel in lp_data/HConst.h

**Comment by mckib2** [comment]
`HConst.h` was the file that me to believe that 3, 5, and 6 are invalid values.

Here's the test I ran:
```
#include <iostream>
enum HighsPrintMessageLevel {
  ML_MIN = 0,
  ML_NONE = ML_MIN,
  ML_VERBOSE = 1,
  ML_DETAILED = 2,
  ML_MINIMAL = 4,
  ML_ALWAYS = ML_VERBOSE | ML_DETAILED | ML_MINIMAL,
  ML_MAX = ML_ALWAYS
};
int main() {
    std::cout << "ML_MIN " << ML_MIN << std::endl;
    std::cout << "ML_NONE " << ML_NONE << std::endl;
    std::cout << "ML_VERBOSE " << ML_VERBOSE << std::endl;
    std::cout << "ML_DETAILED " << ML_DETAILED << std::endl;
    std::cout << "ML_MINIMAL " << ML_MINIMAL << std::endl;
    std::cout << "ML_ALWAYS " << ML_ALWAYS << std::endl;
    std::cout << "ML_MAX " << ML_MAX << std::endl;
    return 0;
}
```

Output:
```
ML_MIN 0                                                                                                                                                       
ML_NONE 0                                                                                                                                                      
ML_VERBOSE 1                                                                                                                                                   
ML_DETAILED 2                                                                                                                                                  
ML_MINIMAL 4                                                                                                                                                   
ML_ALWAYS 7                                                                                                                                                    
ML_MAX 7  
```

It is unclear to me what should be expected from 3 for example

**Comment by jajhall** [comment]
Internally, each message call has a single level. In theory this is the sum of one or more of ML_VERBOSE, ML_DETAILED and ML_MINIMAL but, in practice, it's one of the three or ML_ALWAYS

The default is 4 (ML_MINIMAL)

With message_level = 3 the user gets to see all reporting that's performed when the message level in the reporting call has the 1 or 2 bits set.

I'll raise an issue to clarify the documentation!

**Comment by mckib2** [comment]
Perfect, that was the clarification I needed.  I'll close out this issue
