### ISSUE TITLE
ENH: documentation contrast

### ISSUE THREAD

**Issue by mckib2** [ERGO-Code/HiGHS#382]
On a less technical note, I find it difficult to read some of the documentation on the [HiGHS web page](https://www.maths.ed.ac.uk/hall/HiGHS).  I think it could help to darken the font color a bit as shown below (top paragraph with black color, bottom paragraph with current font color):

![image](https://user-images.githubusercontent.com/28734319/85087921-04b1d800-b19c-11ea-8891-ab3c88c35652.png)

**Comment by jajhall** [comment]
Fixed a long time ago!
