### ISSUE TITLE
BUG: Simplex primal strategy fails on simple problem

### ISSUE THREAD

**Issue by mckib2** [ERGO-Code/HiGHS#395]
Using the option `simplex_strategy = 4` (primal simplex), the following problem based on [this unit test](https://github.com/scipy/scipy/blob/master/scipy/optimize/tests/test_linprog.py#L551) is reported as unbounded (with or without presolve enabled):
```
NAME
ROWS
 N  COST
 L  row0    
 L  row1    
COLUMNS
    col0      COST      1
    col0      row0      -3
    col0      row1      1
    col1      COST      -4
    col1      row0      1
    col1      row1      2
RHS
    RHS_V     row0      6
    RHS_V     row1      4
BOUNDS
 FR BOUND     col0    
 LO BOUND     col1      -3
ENDATA
```

Using `simplex_strategy = 1` reports the correct optimal solution.

**Comment by jajhall** [comment]
The primal simplex solver has got bugs in it. Fixing it is one of my next tasks

**Comment by mckib2** [comment]
The primal solver in current master no longer reports unbounded and agrees with dual simplex on this problem, closing
