### ISSUE TITLE
Objective value differences with several mipli2017 problems

### ISSUE THREAD

**Issue by mingodad** [ERGO-Code/HiGHS#411]
I'm testing HiGHS with miplib2017 problems (only LP) and in several of then there is difference in LP objective value, like in https://miplib.zib.de/instance_details_germanrr.html
```
HiGHS   -> 45980140.0
GLPK    -> 45980135.42
CLP     -> 45980135.42
LPSOLVE -> 45980135.4164
```

**Comment by mingodad** [comment]
In this one https://miplib.zib.de/instance_details_neos-1425699.html the difference is:
```
HiGHS   -> 3175204000.0
GLPK    -> 3175204365.0
CLP     -> 3175204365.0
LPSOLVE -> 3175204364.64
```

**Comment by mingodad** [comment]
In this one https://miplib.zib.de/instance_details_neos-3373491-avoca.html the difference is:
```
HiGHS   -> 21687690000.0
GLPK    -> 21687686010.0
CLP     -> 21687686010.0
LPSOLVE -> 10300904668.5
```

**Comment by mingodad** [comment]
The problem seem to be the format string for the output ins app/RunHighs.cpp:
```
    if (model_status == HighsModelStatus::OPTIMAL) {
      double objective_function_value;
      highs.getHighsInfoValue("objective_function_value",
                              objective_function_value);
      HighsPrintMessage(output, message_level, ML_ALWAYS,
                        "Objective value     : %17.6e\n",
                        objective_function_value);
    }
```

**Comment by jajhall** [comment]
Thanks for this. I couldn't believe that GLPK and LPSOLVE - which are terribly solvers - were more accurate!

**Comment by jajhall** [comment]
I've increased the number of digits printed in app/RunHighs.cpp

I've not used %f, as this would lead to an unreasonable suggestion of accuracy, but %17.10f, reflecting the default optimality tolerance
