### ISSUE TITLE
Dereference of uninitialized pointer inside OsiHiGHSSolverInterface

### ISSUE THREAD

**Issue by tosttost** [ERGO-Code/HiGHS#423]
In OsiHiGHSSolverInterface.cpp line 65 "this->highs->" is used but it is only created in line 69.

I fixed that locally by reordering the lines. Related issue: it might be a good idea to document the state of the Osi Interface - I tried to replace Clp with HiGHS and shot myself in the foot due to methods with dummy implementations, i.e. applyCuts(), that do nothing (except from logging).
If those would would signal some kind of error, I could try to implement the few methods I need myself but with the current state I'll have to read the whole file and check which functions are actually called from my code...

**Comment by jajhall** [comment]
Thanks for opening the issue. Sorry you're having a bad time with the OSI interface, because we'd like people to use it to replace Clp with HiGHS - since that's our ultimate goal! Since we last revised the OSI interface a lot of the missing features of HiGHS have been added.

**Comment by tosttost** [comment]
The great thing about free software is that I'm able to fix 'easy' issues locally :)
I got it mostly working now and "hacked highs" is about as fast as clp - it turned out that I only needed to fix the ctor and call addRow from applyRowCut. I'm currently digging into an issue if >1 cut is separated at each round of my cutting plane algorithm (might by an issue in my code).

Some nitpicking:
* the amount of logging is excessive to the extend I have to pipe stdout into /dev/null or a file. For each function call at least 1 line is printed. Something like OsiClpSolverInterface::setLogLevel() would be great - I "fixed" that by lobotomizing HighsIO.cpp but there is probably a better way.
* Some way to disable presolving when doing "resolve" would be great - at least in my case that proved essential to match the speed of Clp.

**Comment by jajhall** [comment]
> The great thing about free software is that I'm able to fix 'easy' issues locally :)
> I got it mostly working now and "hacked highs" is about as fast as clp - it turned out that I only needed to fix the ctor and call addRow from applyRowCut. I'm currently digging into an issue if >1 cut is separated at each round of my cutting plane algorithm (might by an issue in my code).

That's the great thing about people who know how to code: they don't need fancy interfaces!
 
> Some nitpicking:
> 
>     * the amount of logging is excessive to the extend I have to pipe stdout into /dev/null or a file. For each function call at least 1 line is printed. Something like OsiClpSolverInterface::setLogLevel() would be great - I "fixed" that by lobotomizing HighsIO.cpp but there is probably a better way.

All you need to do is call
setHighsLogfile()
setHighsOutput()
and that switches off all HiGHS printing, by setting the logfile and output channels to NULL

>     * Some way to disable presolving when doing "resolve" would be great - at least in my case that proved essential to match the speed of Clp.

Calling 

setHighsOptionValue("presolve", "off")

before resolve will do this. [Running presolve prevents HiGHS from starting from an advanced basis]

Good to hear that HiGHS is as about as fast as Clp for your purposes. Our aim is that it becomes faster than Clp.

Out of curiosity, why are you looking at HiGHS as an alternative to Clp?

**Comment by tosttost** [comment]
> Out of curiosity, why are you looking at HiGHS as an alternative to Clp?

At the moment it is mostly toying around and with Osi and a pure lp it is pretty simple to swap solvers. The whole program is mostly for educational purpose.
In fact replacing SoPlex within SCIP looks much more promising than replacing Clp within CBC - I have not dared to compile SCIP with Clp due to the "sometimes returns wrong results" warning...

**Comment by jajhall** [comment]
Indeed, I've never tried to compile SCIP with Clp. I've written an interface so that SCIP can be run with HiGHS. Although it passes 94% of the SCIP unit tests, it's not official yet. 

Note also that we are also in the process of writing a MIP solver for HiGHS and I am confident that it will, ultimately, out-perform Cbc (but probably not SCIP).

Thanks
