### ISSUE TITLE
Iterations reported for infeasible problem with presolve enabled

### ISSUE THREAD

**Issue by mckib2** [ERGO-Code/HiGHS#425]
@jajhall @mdhaber
Both dual simplex and IPX report non-zero iteration counts when solving the following problem with presolve enabled (based on [this scipy unit test](https://github.com/scipy/scipy/blob/5bd7a6a8477badd6bdc718c4b38837d08e0413c7/scipy/optimize/tests/test_linprog.py#L730)):
```
c = [1, 1, 1, 2]
A_eq = [
    [1, 0, 0, 0],
    [0, 2, 0, 0],
    [1, 0, 0, 0],
    [1, 1, 1, 1]]
b_eq = [1, 2, 2, 4]
```
which corresponds to the following MPS file:
[test_singleton_row_eq_1.mps.txt](https://github.com/ERGO-Code/HiGHS/files/5611708/test_singleton_row_eq_1.mps.txt)

Dual simplex reports 1 iteration while IPX reports 4.  The following commands reproduce the behavior:
```
./highs --solver simplex --presolve on test_singleton_row_eq_1.mps
./highs --solver ipm --presolve on test_singleton_row_eq_1.mps
```

It could be that iterations are now required even when presolve finds the problem infeasible?  If so, we can update our testing policy accordingly.

**Comment by jajhall** [comment]
Interesting one. I see why it's clearly infeasible, but presolve fails to identify it and reduces the LP to a 1-row 2-column LP that has an optimal solution. This is found after 1 simplex or 4 IPM iterations. Given the original LP and the "optimal" basis deduced by postsolve, the dual simplex solver immediately identifies dual unboundedness and, hence, primal infeasibility.

I'll ask Ivet to look at why presolve doesn't identify infeasibility.

**Comment by mckib2** [comment]
Looking at the history of Presolve.cpp, appears to have broken between commits bb91898703f2e1358f582bdf63803d2c11441e63 and f5f4d432e70ec38f0c927e44f5ae8a3dcf70803c, I'll see if I can narrow it down any further

**Comment by mckib2** [comment]
@galabovaa #427 did not fix the problem shown with this MPS.  The iterations are still reported as 1 and 4 for simplex and IPX, respectively.

The new check `rowLower[row] - rowUpper[row] > tol` is `0 > 1e-07` for this problem and so does not find the infeasibility as hoped.

**Comment by galabovaa** [comment]
Sorry about that, @mckib2! The issue was elsewhere, the check needed to be made after the row bound values are updated, further down in the same method. 

I merged the updated fix in master, would you please double check that the example passes now?

**Comment by mckib2** [comment]
Yep, that was the fix!  Thanks for looking into that and getting a fix in so quick
