### ISSUE TITLE
Compiling with VS 2019 in Windows 10

### ISSUE THREAD

**Issue by sartorg** [ERGO-Code/HiGHS#436]
Using Visual Studio 2019 16.8.3 on Windows 10, with cmake 3.19.2, and of course it complains about the fortran compiler, which VS does not provide (as far as I know).
I am running this from `cmd`, not the command prompt inside Visual Studio. I am surprised it is able to pick up the VS compilers, considering that my path contains `MinGW/bin`, but it does not contain `cl`. 

> C:\Users\giorgios\work\projects\HiGHS>cd build
> 
> C:\Users\giorgios\work\projects\HiGHS\build>cmake ..
> -- Building for: Visual Studio 16 2019
> -- Selecting Windows SDK version 10.0.18362.0 to target Windows 10.0.18363.
> -- The CXX compiler identification is MSVC 19.28.29335.0
> -- The C compiler identification is MSVC 19.28.29335.0
> -- Detecting CXX compiler ABI info
> -- Detecting CXX compiler ABI info - done
> -- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Professional/VC/Tools/MSVC/14.28.29333/bin/Hostx64/x64/cl.exe - skipped
> -- Detecting CXX compile features
> -- Detecting CXX compile features - done
> -- Detecting C compiler ABI info
> -- Detecting C compiler ABI info - done
> -- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Professional/VC/Tools/MSVC/14.28.29333/bin/Hostx64/x64/cl.exe - skipped
> -- Detecting C compile features
> -- Detecting C compile features - done
> -- Could NOT find OpenMP_C: Found unsuitable version "2.0", but required is at least "3.0" (found -openmp)
> -- Could NOT find OpenMP_CXX: Found unsuitable version "2.0", but required is at least "3.0" (found -openmp)
> -- Could NOT find OpenMP (missing: OpenMP_C_FOUND OpenMP_CXX_FOUND) (Required is at least version "3.0")
> -- Could NOT find PkgConfig (missing: PKG_CONFIG_EXECUTABLE)
> -- Git hash: cd2c986d
> -- Compilation date: 2020-12-28
> -- Looking for a Fortran compiler
> -- Looking for a Fortran compiler - NOTFOUND
> -- Looking for a CSharp compiler
> -- Looking for a CSharp compiler - C:/Program Files (x86)/Microsoft Visual Studio/2019/Professional/MSBuild/Current/Bin/Roslyn/csc.exe
> -- The CSharp compiler identification is Microsoft unknown 9999
> -- The CSharp compiler version is 3.8.0
> -- Check for working C# compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Professional/MSBuild/Current/Bin/Roslyn/csc.exe
> -- Check for working C# compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Professional/MSBuild/Current/Bin/Roslyn/csc.exe - works
> -- Build shared libraries: ON
> -- Build type:
> -- Performing Test flag_supported
> -- Performing Test flag_supported - Success
> -- Performing Test flag_supported
> -- Performing Test flag_supported - Failed
> -- Performing Test flag_supported
> -- Performing Test flag_supported - Failed
> -- Performing Test flag_supported
> -- Performing Test flag_supported - Failed
> -- CSharp supported
> -- Configuring done
> -- Generating done
> -- Build files have been written to: C:/Users/giorgios/work/projects/HiGHS/build

Am I missing something? I am not an expert of cmake, so it is not clear to how to force the usage of the MinGW binaries.
What is the suggested solution for compiling in Windows?

**Comment by mckib2** [comment]
Unless you need the Fortran interface, having a Fortran compiler is not necessary to build HiGHS.

CMake is "smart" enough to know it's running on Windows and to find the Visual Studio build tools like `cl` and `link`.  `gfortran` should be compatible with this tool chain.

A few questions:
- Are you sure that MinGW is on your PATH?
- Are you using MSYS, MSYS2, or have you only installed MinGW?
- Are you using MinGW or the MinGW64 bit fork?

The easiest way I've found to install MinGW64 and `gfortran` is through chocolately:
```
choco install -y mingw
```

If you're using MSYS, you might try using the MSYS CMake generator:
```
cmake -G"MSYS Makefiles"
```

**Comment by galabovaa** [comment]
Try using the CMake option -DFAST_BUILD=ON 

It switches Fortran off and will be the default build in the release. Only some of the features may be affected but it works for basic functionality already.
