### ISSUE TITLE
Option for no logging

### ISSUE THREAD

**Issue by bhalonen** [ERGO-Code/HiGHS#446]
As far as I can tell, there is no option for turning logging off entirely. This would be nice, especially if you are calling the solver over and over again.

**Comment by bhalonen** [comment]
trying to benchmark HiGHS against clp, but my use case has many, many smaller solves, and it is hard to tell if I'm just measuring io time.

**Comment by odow** [comment]
Potential duplicate of https://github.com/ERGO-Code/HiGHS/issues/358

**Comment by jajhall** [comment]
Now part of https://github.com/jump-dev/HiGHS.jl/pull/22
