### ISSUE TITLE
set time_limit or ipm_iteration_limit

### ISSUE THREAD

**Issue by kyler1990** [ERGO-Code/HiGHS#447]
hello, 
 i set time_limit or ipm_iteration_limit with the solver = ipm, and i get solution = 0 for all the variable when time limit exceeded
 or iteration limit exceeded。 How can i get the intermediate result.

Thank you!

**Comment by jajhall** [comment]
With the default solver (dual simplex) there's not a lot to return that's useful - a dual feasible solution at best. However, with IPM and (now) primal simplex, HiGHS will - in due course - return a point that may be primal feasible (near-feasible? for IPM).

**Comment by jajhall** [comment]
Now part of #449
