### ISSUE TITLE
Headerfiles missing from make install

### ISSUE THREAD

**Issue by feldmeier** [ERGO-Code/HiGHS#455]
util/HighsCDouble.h
util/HighsHash.h
presolve/HAggregator.h

are missing (and potentially a few more) from the non-fastbuild CMakeLists.txt and are not installed. This leads to errors when using some classes (e.g. HFactor) from HiGHS in a different project to which HiGHS is linked as a library

**Comment by galabovaa** [comment]
@lgottwald would you maybe please add these, and, if you have other new headers, to CMakeLists?

**Comment by lgottwald** [comment]
I now added all the headers for the latest changes that will soon be merged. Changing that now in the master would create conflicts
