### ISSUE TITLE
BUG: incorrect primal rays

### ISSUE THREAD

**Issue by odow** [ERGO-Code/HiGHS#464]
While working on https://github.com/jump-dev/HiGHS.jl/pull/38, I found a few bugs in `getPrimalRay`:
```Julia
using HiGHS

"""
    unbounded_bug()

The model is:
    min -x - y
         x - y == 0

which has a primal ray: [d, d], for all d > 0.
"""
function unbounded_bug()
    highs = Highs_create()
    Highs_addCol(highs, -1.0, -Inf, Inf, 0, Cint[], Cdouble[])
    Highs_addCol(highs, -1.0, -Inf, Inf, 0, Cint[], Cdouble[])
    Highs_addRow(highs, 0.0, 0.0, 2, Cint[0, 1], Cdouble[1.0, -1.0])
    Highs_setHighsStringOptionValue(highs, "presolve", "off")
    Highs_run(highs)
    has_ray = Ref{Cint}(-1)
    ray_value = fill(NaN, 2)
    Highs_getPrimalRay(highs, has_ray, ray_value)
    Highs_destroy(highs)
    @show ray_value
    @assert has_ray[] == 1
    @assert ray_value[1] ≈ ray_value[2]
    @assert ray_value[1] > 0  # Fails. ray = [0.0, 0.0].
    return
end
unbounded_bug()

"""
    unbounded_bug2()

The model is:
    min -x - y
         x - y == 0
         x,  y >= 0

which has a primal ray: [d, d], for all d > 0.
"""
function unbounded_bug2()
    highs = Highs_create()
    Highs_addCol(highs, -1.0, 0.0, Inf, 0, Cint[], Cdouble[])
    Highs_addCol(highs, -1.0, 0.0, Inf, 0, Cint[], Cdouble[])
    Highs_addRow(highs, 0.0, 0.0, 2, Cint[0, 1], Cdouble[1.0, -1.0])
    Highs_setHighsStringOptionValue(highs, "presolve", "off")
    Highs_run(highs)
    has_ray = Ref{Cint}(-1)
    ray_value = fill(NaN, 2)
    Highs_getPrimalRay(highs, has_ray, ray_value)
    Highs_destroy(highs)
    @show ray_value
    @assert has_ray[] == 1
    @assert ray_value[1] ≈ ray_value[2]  # Fails. ray = [-1.0, 0.0].
    @assert ray_value[1] > 0
    return
end
unbounded_bug2()
```

**Comment by jajhall** [comment]
Thanks. I wasn't confident that getPrimalRay was right. That's why HiGHS writes
WARNING: Method getPrimalRay is still under development and behaviour may be unpredictable
But this will help!

**Comment by jajhall** [comment]
Fixed in ekk-master. Will propagate to master in due course

**Comment by odow** [comment]
Thanks! One follow up request (although I can open an issue): rays are only available from the simplex solver. If HiGHS detects unboundedness or infeasibility during presolve, should the default be to then try and re-solve with presolve disabled to the rays are generated? We could code this into the JuMP wrapper, but it feels like a hack.

**Comment by jajhall** [comment]
If no ray is known for an LP that has been found to be infeasible/unbounded - either because it's been identified during presolve or by the interior point solver - then I can modify getDualRay/getPrimalRay to call the simplex solver without presolve to generate the appropriate ray. Clearly there will be quite an overhead in the call, which is why I wouldn't identify the ray by default when the initial Highs::run() is called.
