### ISSUE TITLE
MPS file read failure

### ISSUE THREAD

**Issue by jajhall** [ERGO-Code/HiGHS#467]
Strange. HiGHS (master) will no longer read the Format MIP problems because the name line is just
NAME
[milp-s-01.mps.txt](https://github.com/ERGO-Code/HiGHS/files/5997115/milp-s-01.mps.txt)
Gurobi and Clp read them OK

**Comment by mckib2** [comment]
I do believe I caused this one, I'll have a fix PR shortly
