### ISSUE TITLE
Preparing for first release: sign of the row_dual values in HiGHS

### ISSUE THREAD

**Issue by jajhall** [ERGO-Code/HiGHS#470]
Note (@mckib2 and @odow) that the sign of the row_dual values in HiGHS is under discussion. There was a good reason for the negation, but I've forgotten it. I'll see what Xpress/Gurobi give and ensure that HiGHS is consistent with both - if possible! If the sign is flipped, it will be done before the first formal release of HiGHS, and documented in the release notes. Some method names in the C++ Highs class (and other language interfaces) will change too at this stage. Although it changes the API, we don't want to stick with method names we don't like or methods that are superfluous - or remain back-compatible with pre-release HiGHS. Again, all will be well documented in the release notes, and the work required in modifying calls to HiGHS will be small.

**Comment by mckib2** [comment]
FYI, SciPy lags behind master anyways, so this should be no trouble and gives us plenty of time to incorporate and test these sorts of changes.  If I recall correctly, the Julia packages use the C API while we rely on the C++ API

**Comment by odow** [comment]
Gurobi returns the negative of your current row duals. The column duals are fine. I don't have an opinion on whether this should change, it just needs to be well documented. 

Feel free to break anything you like in pre-release. Better to have a tidy public API for the long-term.

**Comment by jajhall** [comment]
Thanks. I consider the HiGHS row duals to be "wrong". I think that HiGHS is reflecting my old solver, which is reflecting OSL - the old IBM code. All to satisfy a long-term customer. 

I'll definitely switch the sign now!

**Comment by loehndorf** [comment]
I also tripped over this detail. XPRESS and CLP invert the sign of the duals when the sense is is set to maximize.

**Comment by jajhall** [comment]
> I also tripped over this detail. XPRESS and CLP invert the sign of the duals when the sense is is set to maximize.

So (sign-wise) they have the same dual feasibility condition whether maximizing or minimizing. I guess this comes from flipping the sign of the costs when maximizing, using a minimization LP solver and then not flipping the duals back. I'd say that they are wrong, as the duals are a uniquely-defined function of the (original) costs in the LP. 

This is why we will be flipping the sign of the row duals in our first formal release (as commented on earlier).

What's also important is that the dual signs are documented, and thanks for raising the issue that there may be differences in dual signs between solvers when maximizing.

**Comment by jajhall** [comment]
Documented
