### ISSUE TITLE
constants are not exported in the C API

### ISSUE THREAD

**Issue by lovasoa** [ERGO-Code/HiGHS#478]
It would be nice to have access to the various constants used as status codes in the C API.

Currently, one has to hardcode the constants values in code such as in  https://github.com/ERGO-Code/HiGHS/blob/master/examples/call_highs_from_c.c#L226

It would be great to be able to write 

```c
if (modelstatus == OPTIMAL) { ... }
```

with `OPTIMAL` a constant available in `highs_c_api.h`

**Comment by jajhall** [comment]
Sure, and this is something that we'll do for the first proper release. Unfortunately OPTIMAL is part of an enum class in the C++, and these don't export (readily) to C

Nice to have the feedback, though! Hope you're happy with HiGHS otherwise.

**Comment by lovasoa** [comment]
> OPTIMAL is part of an enum class in the C++, and these don't export (readily) to C

Yes, I meant manually exporting the constant values of the c++ enum. I did that in my rust binding: https://github.com/rust-or/highs-sys/blob/v0.0.5/src/lib.rs#L9-L27

> Hope you're happy with HiGHS otherwise.

Yes, I like working with it !

**Comment by jajhall** [comment]
It's true that this is something that we could do in the first formal release

**Comment by lovasoa** [comment]
@jajhall Why closing this issue now, then ? Maybe we can leave it open until this is actually done ?

**Comment by jajhall** [comment]
This issue has been addressed to the fullest reasonable extent
