### ISSUE TITLE
Typo in Fortran Interface

### ISSUE THREAD

**Issue by ogmundur** [ERGO-Code/HiGHS#482]
There is a typo in the Fortran interface. The function "Highs_setOptionValue" should be bound to the C routine 'Highs_setHighsOptionValue'  (not 'Highs_setOptionValue').

**Comment by odow** [comment]
You can make a pull request by clicking the pencil icon in the top-right of https://github.com/ERGO-Code/HiGHS/blob/master/src/interfaces/highs_lp_solver.f90

**Comment by ogmundur** [comment]
Created a pull request
