### ISSUE TITLE
TEST: optimality of scaled and unscaled models

### ISSUE THREAD

**Issue by mckib2** [ERGO-Code/HiGHS#494]
A quick scan did not reveal the case of mismatched `scaled_model_status` and `model_status` is being tested, i.e. that the correct statuses are returned and feasibility tolerances recommended.  The HiGHS runner [does check for this](https://github.com/ERGO-Code/HiGHS/blob/7f4f0a58c415fa6cd678395d109155a3f5a7c670/app/RunHighs.cpp#L141) case and prints infeasibilities when it occurs.

We recently encountered [this issue](https://github.com/scipy/scipy/issues/13610) and found that the LP formulation of least absolute deviation (LAD) regression problems reliably recreates these sorts of models.  I will attach one with random costs and constraints here if it is of interest.

[model_mismatch.mps.txt](https://github.com/ERGO-Code/HiGHS/files/6094446/model_mismatch.mps.txt)

When I run with this dual simplex, it recommends re-runing with different tolerances which, when re-run, do indeed solve the unscaled model to optimality:
```
INFO   : Possibly re-solve with feasibility tolerances of 5e-08 primal and 1e-07 dual
```

Please close if this is already under test or if it's not an interesting thing to test.

**Comment by mckib2** [comment]
This no longer produces the model mismatch we observed in an earlier version of the dual simplex solver.  Is HiGHS now checking for this condition or did the solver just get good enough to solve this particular example without scaling issues?

**Comment by jajhall** [comment]
After solving the scaled LP, if there are infeasibilities in the unscaled LP, HiGHS now performs simplex iterations on the unscaled LP (using scaled numerical linear algebra) to remove the infeasibilities. Hence the issue has disappeared! 🙂

**Comment by mckib2** [comment]
Fantastic, we can remove these checks from our end then and close this issue
