### ISSUE TITLE
Restore gas11 (and etamacro?) to instance tests

### ISSUE THREAD

**Issue by jajhall** [ERGO-Code/HiGHS#499]
gas11 is an unbounded LP, but when presolve recognises unbounded the LP could be infeasible, in which case the model status is HighsModelStatus::PRIMAL_INFEASIBLE_OR_UNBOUNDED. However, without presolve, the simplex solver distinguishes these two cases when dual simplex identifies dual infeasible. In due course it (like Gurobi) won't do this, and just return HighsModelStatus::PRIMAL_INFEASIBLE_OR_UNBOUNDED. However instance tests need the same status with/without presolve, so gas11 is currently removed from them.

The objective obtained for etamacro isn't the same with/without presolve

- With presolve it's -7.5571523114e+02 with Dual infeasibility:  1.362e-06 (2)
- Without presolve it's -7.5571523130e+02 Dual infeasibility:  1.362e-06 (1)

maybe this will disappear when more is done to avoid infeasibilities in the unscaled LP but, for now, etamacro is removed from the instance tests

**Comment by lgottwald** [comment]
For gas11: Maybe we could add an option to determine the feasibility in case the result infeasible or unbounded is not sufficient like gurobi does. Then we could request HiGHS to return a definite status for this test. Alternatively we can adjust regular expressions for success so that both status codes are accepted.

**Comment by jajhall** [comment]
Distinguishing LPs that are both primal and dual infeasible from those that are merely (say) primal unbounded is very messy. Once dual simplex identifies dual infeasiblilty, primal simplex has to be run to determine whether the LP is primal infeasible or primal unbounded, "remembering" that it has previously been identified as dual infeasible. 
I'd rather just do as Gurobi. This also means that HiGHS doesn't have to refer to a dual status, and it's more likely that HiGHS with/without presolve gives the same status code. 
Problems that are just primal infeasible will have the status "infeasible", whether or not presolve is used, and that's the important case. 
If users want to distinguish in the case where "infeasible or unbounded" is returned, we can document the suggestion that they call run() with presolve off and primal simplex as the solver. 
Gurobi states gas11 as being an "Infeasible or unbounded model", by the way
