### ISSUE TITLE
Support for external presolver

### ISSUE THREAD

**Issue by goghino** [ERGO-Code/HiGHS#509]
There is an `EXT_PRESOLVE_DIR` option in the cmake, which should specify path to the external presolving library. I am trying to use [PaPILO](https://github.com/lgottwald/PaPILO), i.e. I set the `EXT_PRESOLVE_DIR` variable to point to PaPILO base directory (note: not the install dir, but the dir with src/ external/). But I don't see any difference when running the model with or without using EXT_PRESOLVE_DIR option. When I grep for PaPILO in my build dir all I see are some additional include paths (`C_INCLUDES = -I[...]/PaPILO/src -I[...]/PaPILO/external`), but the library itself is not actually used?

**Comment by jajhall** [comment]
Thanks. It sounds as if this is just for a developer's experiment.

**Comment by galabovaa** [comment]
Sorry about that, it is left from a long time ago. Sadly, at the moment we don't support it.

**Comment by jajhall** [comment]
The HiGHS presolve is probably comparable in performance with PaPILO now, anyway.
