### ISSUE TITLE
fopen called when writting solution but not fclose

### ISSUE THREAD

**Issue by lequant40** [ERGO-Code/HiGHS#512]
Hello !

Issue discovered in https://github.com/lovasoa/highs-js/issues/5.

It seems that when calling method `Highs_writeSolutionPretty` (https://github.com/ERGO-Code/HiGHS/blob/master/src/interfaces/highs_c_api.cpp#L112), the method `writeSolution `is then called (https://github.com/ERGO-Code/HiGHS/blob/master/src/lp_data/Highs.cpp#L2098), which is doing an `fopen` (https://github.com/ERGO-Code/HiGHS/blob/master/src/lp_data/Highs.cpp#L2184), but no corresponding `fclose `is ever done in this flow.

This leads to a leak of file descriptors in the calling process (Python, ...), as seen in the above issue.

Would it be possible to fix this ?

_(Note: running HiGHS through the command line is not impacted, only the call through DLL APIs)_

Cheers,

Roman

**Comment by jajhall** [comment]
Sure. Easily done! I'll let you know when I've done so

**Comment by jajhall** [comment]
fclose now called in writeSolution/Info/Options on master - so long as file isn't stdout (which is OK to pass to fclose on Linux, but not Windows!). Logging file is never closed - as it's impossible for HiGHS to know when logging has finished. However, there's only one per Highs instance

**Comment by feldmeier** [comment]
Logging file could be closed in the destructor of the Highs instance (Highs::~Highs()), since logging definitely ends when the corresponding Highs object is being deleted

**Comment by jajhall** [comment]
Indeed: I'll add that
