### ISSUE TITLE
C interface documentation for QP Hessian

### ISSUE THREAD

**Issue by matbesancon** [ERGO-Code/HiGHS#566]
In c_api.h:
L292 in `Highs_passModel`
```
    const HighsInt* qstart,  //!< array of length [numcol] with Hessian start
                             //!< indices - or NULL if model is linear
```

L93: Highs_qpCall:
```
    const HighsInt* qstart,  //!< array of length [numcol+1] with Hessian column
                             //!< start indices
```

is it normal to have a difference in array lengths here?

**Comment by jajhall** [comment]
Sorry Mathieu (@matbesancon), things have been busy recently. I'm making some other QP mods today, so will look at this.

**Comment by matbesancon** [comment]
no problem, there is nothing blocked by this on my end

**Comment by jajhall** [comment]
Internally we use the (ncol+1)st entry for both loops and as a record of the number of nonzeros, so this has crept into the documentation. As I'm sure you realise, at the level of the C PI, we use ncol entries in start arrays, and have the number of nonzeros passed separately.

I've updated the documentation

**Comment by matbesancon** [comment]
perfect thank you!
