### ISSUE TITLE
HIGHS could not recognize Free MPS files

### ISSUE THREAD

**Issue by WTFHCN** [ERGO-Code/HiGHS#571]
I ran into a problem that HIGHS could not recognize Free MPS files. For example:
```
* Source:     Pyomo MPS Writer
* Format:     Free MPS
*
NAME unknown
OBJSENSE
 MAX
ROWS
 N  x3
 L  c_u_x4_
 L  c_u_x5_
 L  c_u_x6_
COLUMNS
     x1 x3 40
     x1 c_u_x4_ 1
     x1 c_u_x5_ 1
     x1 c_u_x6_ 2
     x2 x3 30
     x2 c_u_x5_ 1
     x2 c_u_x6_ 1
RHS
     RHS c_u_x4_ 40
     RHS c_u_x5_ 80
     RHS c_u_x6_ 100
BOUNDS
 LO BOUND x1 -1
 UP BOUND x1 1
 LO BOUND x2 0
ENDATA

```

**Comment by jajhall** [comment]
Interesting, I'll find out why

**Comment by WTFHCN** [comment]
https://github.com/Pyomo/pyomo/issues/2115 I also asked this question in the Pyomo community

**Comment by jajhall** [comment]
So, I see what happens when you try to load this file into HiGHS. Note that it's not a standard MPS file. Gurobi and Soplex read it, but not Clp, so it's not just HiGHS!

I'll let you know when the HiGHS MPS reader can handle it

**Comment by jajhall** [comment]
This issue will be cleared when #573 is approved and merged
