### ISSUE TITLE
HiGHS not featured in current (11.09.21) Mittelmann benchmarks

### ISSUE THREAD

**Issue by sschnug** [ERGO-Code/HiGHS#576]
Just to let you know:

- The current iteration of benchmarks is not featuring HiGHS:
  - http://plato.asu.edu/ftp/lpsimp.html
    - (page says 11.09.21; accessed by me on 12.09.21)
- The current Readme.md leads to above link with:
  - "The performance of HiGHS relative to some commercial and open-source simplex solvers may be assessed via the Mittelmann benchmarks on http://plato.asu.edu/ftp/lpsimp.html"
    - Might be puzzling for people following the link

I'm not sure if one of you is in touch with Prof. Mittelmann, nor do i know why HiGHS is not part of the current evaluation (i think it was before as the Readme indicates).

What strikes me odd howewer, is the addition of software without any info / (valid) link at all (the Huawei code) -> i guess some people are "in touch" ;-)

Greetings,
 
Sascha

**Comment by jajhall** [comment]
Thanks for this. I know that we were dropped earlier in the summer, but the HiGHS version that Hans had was a couple of years old. After massive improvements to HiGHS in the past two years, we're about to produce a pre-release version (without documentation) that I'll ask Hans to benchmark. We will appear higher in the simplex rankings, and also have a decent interior point ranking and a very impressive MIP ranking. 

Interested to see the Huawei entry: "simplex" but no crossover!

**Comment by jajhall** [comment]
I've been in touch with Hans, and HiGHS will soon be returning the benchmarks

**Comment by odow** [comment]
The results are great @jajhall!
