### ISSUE TITLE
\W4 causing ifort to fail

### ISSUE THREAD

**Issue by jajhall** [ERGO-Code/HiGHS#579]
Here's a message from a user:

I downloaded the HiGHS software from github.  I am compiling the software using Visual Studio 2017 and Intel Fortran 2020 on Windows 10, 64-bit.  I used CMAKE version 3.21.1 to build the VS project.  I built the "ALL_BUILD" solution at the top of the solution explorer and was left with the following errors,

![image](https://user-images.githubusercontent.com/22636003/133999719-0cacec3f-992d-439f-b455-e40e25c4ecb0.png)

I tried to build INSTALL afterwards just to see what would happen and I got the same error.  You are building a command line to be run by the Fortran compiler (ifort for me) and are passing the option, /W4 .  It appears that Intel Fortran does not understand what the "4" is about?

I've replied that /W4 "Specifies how the compiler generates warnings for a given compilation." and is designed for C++ compilers, but appears to be passed for all compilers. I guess that gfortran ignores /W4

We could do with a proper fix for this but my suggestion to the user is that he comments out (or deletes) line 280 of CMakeLists.txt where /W4 is added to the definitions.

**Comment by galabovaa** [comment]
this line has now been removed, as W4 is default for MSVC.
