### ISSUE TITLE
OsiInterface building fails

### ISSUE THREAD

**Issue by felixlen** [ERGO-Code/HiGHS#580]
Currently building the OSI interface fails because `lp_` cannot be found in `highs`:
```
src/interfaces/OsiHiGHSSolverInterface.cpp:340:23: error: no member named 'lp_' in 'Highs'
  return this->highs->lp_.num_col_;
```
and because in l. 554 and 582 of the same file the return type of the functions `addRow` and `addCol` is no longer `bool` but `HighsStatus`:
```
bool success = this->highs->addRow(rowlb, rowub, vec.getNumElements(),
                                     vec.getIndices(), vec.getElements());
```

If I replace every occurrence of `highs->lp_` with `highs->model_.lp_` and change the return type in l. 554 and 582 to `HighsStatus` and the subsequent `assert` and `if (success)` to a comparison with `HighsStatus::kOk`, I am able to compile HiGHS again, however run into a segfault in the unit test of the OSI interface.

From https://github.com/ERGO-Code/HiGHS/issues/525 I understand that the OSI interface is currently not maintained and will only be restored later. However, it is built as soon as the OSI library is found (`src/CMakeLists.txt:369`), so that building HiGHS fails for every user having OSI installed.

I suggest considering to just deactivate building the OSI interface for the time it is unmaintained to improve the experience for users having the OSI library installed on their system.

**Comment by jajhall** [comment]
Yes, I perfectly understand, and had not considered this. I'm sure that it's putting off some users from using HiGHS.

@galabovaa Is this easy to do?

**Comment by jajhall** [comment]
> Yes, I perfectly understand, and had not considered this. I'm sure that it's putting off some users from using HiGHS.
> 
> @galabovaa Is it easy to deactivate building the OSI interface for now?

Do we only have to comment out the following line in CMakeLists.txt @galabovaa ?

pkg_check_modules(OSI osi)

**Comment by jajhall** [comment]
#704 should mean that OsiInterface now builds. The OSI interface still needs updating since some of the unit tests fail. This is covered by #525
