### ISSUE TITLE
Questions about licensing of src/ipm/basiclu and src/imp/ipx

### ISSUE THREAD

**Issue by tosttost** [ERGO-Code/HiGHS#584]
Hello,

I'm planning to use HiGHS within an environment that is very pedantic when it comes to licensing.
I know that HiGHS is still in development, but it looks promising enough to use it as an experimental alternative to the aging Cbc/Clp.

* According to LICENSE, HiGHS is released under MIT license. 
* Within the extern folder one can find other license files - not a problem, I can collect them and claim them to be some dependency of HiGHS
* within the folder "src/ipm" one can find what seems to be a more or less a copy of https://github.com/ERGO-Code/ipx and https://github.com/ERGO-Code/basiclu which both use a custom license that allows to choose between MIT and GPL but with the required to add a specific sentence to the documentation of the containing application. 
E.g.  HiGHS/src/ipm/ipx/src/basiclu_kernel.cc  contains the notice "// Copyright (c) 2018 ERGO-Code. See license.txt for license." but there is no license.txt within the folder.

This raises the question

Have the copies of basiclu and ipx contained within this repository been relicenced to vanilla MIT or does the custom license still apply and simply got lost when copying the code?

vanilla MIT is easy, we list all third party software together with their licenses within our application anyway. The custom license would be difficult as it requires more or less that the 3rd party list is plain text and not a table with library name, author/copyright holder, URL and a button to show the full license text...

**Comment by jajhall** [comment]
The pure MIT license status of IPX/basiclu within HiGHS is now clarified
