### ISSUE TITLE
undocumented options

### ISSUE THREAD

**Issue by lovasoa** [ERGO-Code/HiGHS#585]
Hello,
  I was looking in parallel at the documentation for Highs options on https://www.maths.ed.ac.uk/hall/HiGHS/HighsOptions.html
  and at the code on https://github.com/ERGO-Code/HiGHS/blob/master/src/lp_data/HighsOptions.h

  It looks like several options are not documented. I am especially interested in logging-related options, such as `output_flag`, because the Highs C library seems to write to files and to the standard output by default, which is a little bit unexpected.

**Comment by jajhall** [comment]
https://www.maths.ed.ac.uk/hall/HiGHS/HighsOptions.html
is now up-to-date
