### ISSUE TITLE
The Highs C library systematically tries to create a Highs.log file

### ISSUE THREAD

**Issue by lovasoa** [ERGO-Code/HiGHS#586]
The highs C library seems to always create a `Highs.log` file.

When explicitly setting the `log_file` option to the empty string, the `Highs.log` file remains empty, but it is always created.

Is there an easy way to prevent the usage of the library from having any side effect ? When building a larger software on top of libraries, one generally wants to control input/output centrally rather than having each library writing to stdout and creating its own files.

**Comment by mckib2** [comment]
@jajhall Just ran into this issue on the SciPy side while getting back up to speed and creating a MIP wrapper.  Even empty, this Highs.log file will most likely block a merge into SciPy master until patched

**Comment by mckib2** [comment]
Took a stab at this in #635, please do say if there is any more complexity than that to avoid creation of log files

**Comment by jajhall** [comment]
> Yes, `Highs.log` is empty if `log_file` is set to a non-default value. The problem is that `Highs.log` is always opened, even if `log_file` is set to a different file name or to the empty string.
> 
> In my opinion, the default value for `log_file` in the library should be the empty string, and no file should be created. In the highs **application**, the default value for `log_file` could be `"Highs.log"`.
> 
> I think the problem is here: https://github.com/ERGO-Code/HiGHS/blob/06d6ca2/src/lp_data/HighsOptions.h#L824 Just instantiating a HighsOptions object creates a `Highs.log` file.

Indeed, I realise that I've mis-interpreted the circumstances in which Gurobi creates Gurobi.log, so HiGHS (too) won't create this just because an instance of the Highs class has been created.

**Comment by mckib2** [comment]
This has indeed been fixed by #644, thanks @jajhall !

**Comment by NPC** [comment]
This was not done in time to be included in v1.1.1 yet, right? Do you guys plan another release soon? (I can't for the live of me build current version of the library, cmake and all, so I'm depending on pre-built binaries)

**Comment by jajhall** [comment]
Yes, your voice is one of several in recent days calling for a new version. We are clearing up some final issues relating to the development cycle that we've just finished, and then we'll release v1.2. Please bear with us: we're a team of 2-3, with one trying to write up her PhD, and I'm teaching this semester. After the end of February we will have more time, and might even create the first official release with documentation!

**Comment by lovasoa** [comment]
@jajhall, this may be worth saying again : thank you very much to the three of you for your amazing work on HiGHS :heart: Your commitment to this project helps a ton of people all around the globe.

**Comment by NPC** [comment]
@jajhall Thank you for a quick response, and for your efforts on this project, and for (hopefully :)) soon future release, and, especially, improved documentation. From my investigations, using several large sample problems in our field, HiGHS is the fastest free solver out there, and I really hope it will be developed and maintained for years to come.

**Comment by jajhall** [comment]
@NPC Thanks. What sort of problems are you solving? LP, MIP? 

The future looks good for HiGHS, since the School of Maths is funding two positions to keep the team together for at least the next three years - and I'm permanent staff. If we can get enough consultancy/support funding then we'll expand the team.

**Comment by NPC** [comment]
@jajhall we're dealing LP, and the solver is called from a deployable IIS web application written in C# (so, Windows). So I'm still trying to figure out the binaries, the dependencies, and how to ensure correct behaviour in a customer environment, which we don't control (this is why writing an empty Highs.log file in the same folder as the DLL is a problem, the app should not write there). But I already got the solver working on my local PC, a good milestone :) I assume I'll be asking more silly questions in the future, but also if I figure out something worth sharing — I will do.

Wishing you guys well, and I hope your project is a continued success!

**Comment by jajhall** [comment]
@NPC We've created v1.2
