### ISSUE TITLE
Windows *.lib file for HiGHS.

### ISSUE THREAD

**Issue by jajhall** [ERGO-Code/HiGHS#590]
I have downloaded your Windows binary files.

I have interfaced all commercial- and community-based LP, QP, MILP, etc. solvers to our modeling software and I would like to do the same for HiGHS.

All of the other solvers provided the *.lib file for their solvers but I do not see this file extension for HiGHS.

Would it be possible to get this file type somehow?

**Comment by odow** [comment]
This Windows release:
https://github.com/JuliaBinaryWrappers/HiGHS_jll.jl/releases/download/HiGHS-v0.3.3%2B0/HiGHS.v0.3.3.x86_64-w64-mingw32-cxx11.tar.gz
has `bin/libhighs.dll`. Is that not sufficient?

**Comment by jkiviluo** [comment]
I just experienced a similar issue. When I try to execute highs from the command prompt, it cannot proceed because its missing `libgcc_s_sjlj-1.dll` and `libstdc++-6.dll`. I'm sure these can be acquired from e.g. mingw-w64-gcc, but it would be nice if the binary just worked out of the box.

**Comment by jajhall** [comment]
> I just experienced a similar issue. When I try to execute highs from the command prompt on Windows10 after just downloading the HiGHS binary (x86_64-w64-mingw32-cxx11.tar.gz), it cannot proceed because its missing `libgcc_s_sjlj-1.dll` and `libstdc++-6.dll`. I'm sure these can be acquired from e.g. mingw-w64-gcc, but it would be nice if the binary just worked out of the box.

Noted, and we will get around to it at some point.

**Comment by odow** [comment]
Oops. I should update the instructions. (I don't have a windows machine so I can't test.)

You can find the missing DLLs here:
https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/tag/CompilerSupportLibraries-v0.5.1%2B0

You probably want to download this one
https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v0.5.1%2B0/CompilerSupportLibraries.v0.5.1.x86_64-w64-mingw32-libgfortran5.tar.gz

**Comment by jkiviluo** [comment]
Thanks! Got it working standalone. I am using it to run a MathProg model.

I had made an additional mishap by taking the i686 instead of the x86_64 version of HiGHS. Also, in this working version, the libgcc_s_seh-1.dll was required (at least in my case when running with x86_64). So, a combination of:

https://github.com/JuliaBinaryWrappers/HiGHS_jll.jl/releases/download/HiGHS-v1.1.0%2B0/HiGHS.v1.1.0.x86_64-w64-mingw32-cxx11.tar.gz

https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v0.5.1%2B0/CompilerSupportLibraries.v0.5.1.x86_64-w64-mingw32-libgfortran5.tar.gz

did the trick for me.

**Comment by odow** [comment]
For future reference, the i686 is for 32-bit installations of Windows. People almost certainly want the x86_64 version.

And yes, you probably don't need all the libraries in the CompilerSupportLibraries_jll, just whatever ones are missing from your system.

**Comment by fgenoese** [comment]
In general, would you consider building and releasing a static binary? 
FYI: AMPL has made static binaries available for both CBC and Ipopt [here](https://ampl.com/dl/open/cbc/), making it very easy to integrate these solvers with other software.

**Comment by jajhall** [comment]
So, the original user has got back to me, and observed that

>All of the other community-based and commercial-based LP/MILP/NLP solvers have *.lib files and I have standardized on this approach when I link using Intel Fortran i.e., the code is statically linked to *.lib files at compile time.

So, the outstanding issue is how to create a *.lib file to allow static linking. HiGHS does not apparently create such, and it sounds as if it should.

**Comment by lgottwald** [comment]
We should probably test if it works on all platforms though and add such a build to CI

**Comment by odow** [comment]
Is there any reason not to build both the static and shared libraries? Then we could ship both in HiGHS_jll.

**Comment by jajhall** [comment]
The only reason is if the static build doesn't work properly. I wouldn't know how to test it.
