### ISSUE TITLE
Some questions about preprocessing

### ISSUE THREAD

**Issue by zrjer** [ERGO-Code/HiGHS#606]
Hello Professor.
I have a question, what is the difference between HPresolve.cpp and Presolve.cpp, why did you replace Presolve with HPresolve, does HPresove perform more efficiently?
Thank you!

**Comment by jajhall** [comment]
Presolve hasn't been replaced by HPresolve. HPresolve.cpp and Presolve.cpp are two source files required by the HiGHS presolve. There's no "difference" to comment on

**Comment by zrjer** [comment]
But the comment (line 381) of the presolve(HighsInt print) function in presolve.cpp says:
 // This is the original presolve framework, now superseded by
  //
  // HPresolve::Result HPresolve::presolve(HighsPostsolveStack&
  // postSolveStack)
I wonder how to interpret it?

**Comment by jajhall** [comment]
Some of what was in Presolve.h/cpp has been superseded by code in HPresolve.h/cpp, but some of Presolve.h/cpp appears to be necessary.

What are you trying to do?

**Comment by zrjer** [comment]
I am using Highs to solve a practical problem and need to know exactly what pre-processing methods are used. Thank you for your reply.

**Comment by jajhall** [comment]
It would be very hard for a user to identify this by inspecting the code. I'll ask the presolve developer to list them for you.

Might I ask the area in which you are working and whether HiGHS is handling your problems OK. "Success stories" are good to know when it comes to justifying financial support for HiGHS and, within reason, we can offer advice tuned to a users' problem class.
