### ISSUE TITLE
src/lp_data/Highs.cpp:2476: HighsStatus Highs::returnFromRun(HighsStatus): Assertion `return_status == run_return_status' failed.

### ISSUE THREAD

**Issue by tosttost** [ERGO-Code/HiGHS#612]
If the attached model is solved with 
mip_max_nodes = 1
using a debug build of the highs executable the assert in Highs.cpp line 2476 fails. Same happens with some time limits (e.g. "1" on my machine) but as time limits are not deterministic it is harder to reproduce.

The model solves fine with release builds of HiGHS.

[model.mps.zip](https://github.com/ERGO-Code/HiGHS/files/7531701/model.mps.zip)

**Comment by jajhall** [comment]
Sorry: fix pushed to master
