### ISSUE TITLE
C# wrapper API is not correctly calling highs.dll

### ISSUE THREAD

**Issue by malagbek** [ERGO-Code/HiGHS#621]
Method Highs_passLp of wrapper class HighsLpSolver uses invalid signature for dll call. Correct function in C api has signature

HighsInt Highs_passLp(void* highs, const HighsInt numcol, const HighsInt numrow,
                      const HighsInt numnz, const HighsInt a_format,
                      const HighsInt sense, const double offset,
                      const double* colcost, const double* collower,
                      const double* colupper, const double* rowlower,
                      const double* rowupper, const HighsInt* astart,
                      const HighsInt* aindex, const double* avalue)

whereas C# assumes that it expects
int Highs_passLp(void* highs, int numcol, int numrow, int numnz, double[] colcost,
   double[] collower, double[] colupper, double[] rowlower, double[] rowupper, int[] astart, int[] aindex, double[] avalue);

Arguments a_format, sense and offset are missing, therefore calling Highs_passLp from .net causes access violation. To fix the issue one would probably introduce enum HighsMatrixFormat and adapt c# signature.

**Comment by jajhall** [comment]
Thanks. Changes have been made in the C API and not propagated to the C# API

**Comment by jajhall** [comment]
I've had a try, but need to get the C# API author to help

**Comment by jajhall** [comment]
The rest of the c# interface will be updated in due course.
