### ISSUE TITLE
Support for constraint Linear Operator

### ISSUE THREAD

**Issue by mckib2** [ERGO-Code/HiGHS#623]
The `HighsLP.a_matrix_` is `HighsSparseMatrix`.  The question we have in https://github.com/scipy/scipy/issues/15185 is if HiGHS would allow the specification of an abstract linear operator instead of explicit sparse matrix.  The advantage here would be in efficiencies for large, structured matrices.

**Comment by jajhall** [comment]
I've left my comment in https://github.com/scipy/scipy/issues/15185

**Comment by mckib2** [comment]
Thanks @jajhall !
