### ISSUE TITLE
BUG: primal solver dies when solving simple unbounded LPs

### ISSUE THREAD

**Issue by mckib2** [ERGO-Code/HiGHS#630]
When built in debug, we run into assert statements of the form `assert(1 == 0);` for simple unbounded LPs.

The two instances I see are:
- https://github.com/ERGO-Code/HiGHS/blob/2da8f7d4d35965d4c88a1b5a69ee772ebd1e9208/src/simplex/HEkkPrimal.cpp#L2146
- https://github.com/ERGO-Code/HiGHS/blob/2da8f7d4d35965d4c88a1b5a69ee772ebd1e9208/src/simplex/HEkkPrimal.cpp#L2161

It appears to me that these were a developer's rough-n-dirty break-points and can probably be safely removed.  I will make a PR, please do say if this is not the case.

**Comment by jajhall** [comment]
Yes, these are in to trap the first use of untested code. One of them was triggered by experiments I was doing last night, and will soon be removed from master. The code protected by the other one is almost certainly correct, so I should remove this, too.

**Comment by jajhall** [comment]
Fixed by https://github.com/ERGO-Code/HiGHS/commit/ab302f1c1dd7a81a5abc50fc86f852afc115424f
