### ISSUE TITLE
Missing objective sense definition on the C API

### ISSUE THREAD

**Issue by mingodad** [ERGO-Code/HiGHS#632]
Trying to use the `interfaces/highs_c_api.h` I noticed that there is no definition for the valid values for `HighsInt sense`, looking through the C++ headers I found this `enum class ObjSense { kMinimize = 1, kMaximize = -1 };` ideally the `C` interface also should have an equivalent definition, otherwise using `magic numbers` can have umpleasent consequences if for some reason the valid values change in future versions of HIGHS.

**Comment by jajhall** [comment]
Sure, we'll add these definitions to the documentation, even though the relevant values of HighsInt sense are not going to change.

**Comment by jajhall** [comment]
I've added comments on values to be taken by sense, a_format and q_format in highs_c_api.h

**Comment by mingodad** [comment]
Thanks for the effort !
But I think that would be better to have a constant defined on `highs_c_api.h` something like shown bellow to not rely magic numbers as much as possible also improving readability and search ability. 
```
#define OBJ_SENSE_MIN 1
#define OBJ_SENSE_MAX -1
// or
enum ObjSenseValues {
   ObjMinimize =1,
  ObjMaximize = -1
};
```

**Comment by jajhall** [comment]
Sure. I've noted this. As HiGHS matures and we develop the documentation, I'm sure this will come.
