### ISSUE TITLE
MIP Highs::run() returns status -1 for optimal solution

### ISSUE THREAD

**Issue by mckib2** [ERGO-Code/HiGHS#633]
When non-zero integral constraints are given the `Highs::run()` function returns a `HighsStatus` of `-1` for this simple problem taken from MATLAB's intlinprog documentation:

![image](https://user-images.githubusercontent.com/28734319/146629878-7079cb12-751a-4eb4-9e10-c94716ce558d.png)

If useful, I can provide an MPS file describing this problem, but I'm hoping it will be a simple fix to set the status correctly.  Printed to the console is the following:
```
Presolving model
2 rows, 3 cols, 6 nonzeros
0 rows, 1 cols, 0 nonzeros
0 rows, 0 cols, 0 nonzeros
Presolve: Optimal

Solving report
  Status            Optimal
  Primal bound      -12
  Dual bound        -12
  Solution status   feasible
                    -12 (objective)
                    0 (bound viol.)
                    0 (int. viol.)
                    0 (row viol.)
  Timing            0.00 (total)
                    0.00 (presolve)
                    0.00 (postsolve)
  Nodes             0
  LP iterations     0 (total)
                    0 (strong br.)
                    0 (separation)
                    0 (heuristics)
```

The console output leads me to believe this problem was actually solved, but the status says otherwise.

_EDIT: as discovered in investigations below, the incorrect status is reported when `highs_debug_level >= HighsDebugLevel_kHighsDebugLevelCheap`_

**Comment by mckib2** [comment]
With presolve off, the following output is achieved will with status -1 reported:
```
resolve is switched off

Solving MIP model with:
   2 rows
   3 cols (1 binary, 0 integer, 0 implied int., 2 continuous)
   6 nonzeros

( 0.0s) Starting symmetry detection
( 0.0s) No symmetry present

Solving root node LP relaxation

Presolving model
2 rows, 3 cols, 6 nonzeros
2 rows, 3 cols, 6 nonzeros
Presolve : Reductions: rows 2(-0); columns 3(-0); elements 6(-0)
Solving the presolved LP
Using EKK dual simplex solver - serial
  Iteration        Objective     Infeasibilities num(sum)
          0    -2.1200077156e+01 Pr: 2(5.65) 0s
          1    -1.2000000000e+01 Pr: 0(0) 0s
Solving the original LP from the solution after postsolve
Model   status      : Optimal
Simplex   iterations: 1
Objective value     : -1.2000000000e+01
HiGHS run time      :          0.00

        Nodes      |    B&B Tree     |            Objective Bounds              |  Dynamic Constraints |       Work      
     Proc. InQueue |  Leaves   Expl. | BestBound       BestSol              Gap |   Cuts   InLp Confl. | LpIters     Time

 T       0       0         0   0.00%   -inf            -12             9999.00%        0      0      0         1     0.0s

Solving report
  Status            Optimal
  Primal bound      -12
  Dual bound        -12
  Solution status   feasible
                    -12 (objective)
                    0 (bound viol.)
                    0 (int. viol.)
                    0 (row viol.)
  Timing            0.00 (total)
                    0.00 (presolve)
                    0.00 (postsolve)
  Nodes             1
  LP iterations     1 (total)
                    0 (strong br.)
                    0 (separation)
                    0 (heuristics)

```

**Comment by jajhall** [comment]
Very odd. I've created the an MPS file for this problem (using current master), and got the same output, but the return code from run() is 0 with, and without, presolve.

What's the GitHash of the HiGHS version that you're using?

**Comment by mckib2** [comment]
I just tried against latest master: ab302f1c1dd7a81a5abc50fc86f852afc115424f

Same result, `highs.run()` reports -1 (`kError`).  If I ignore the error (comment out the check), then the correct solution is reported, but all iteration counts are also -1, i.e. never populated.

Maybe you can help me identify an error in my strategy.  I'm using the C++ API to do the following:
- create a `HighsLp` object and populate the following fields:
    - `num_col_`, `num_row_`
    - `a_matrix_.num_col_`,  `a_matrix_.num_row_`, `a_matrix_.format_`, `a_matrix_.start_`, `a_matrix_.index_`, `a_matrix_.value_`
    - `col_cost_`, `col_lower_`, `col_upper_`
    - `row_lower_`, `row_upper_`
    - `integrality_` (left empty for pure LPs)
- create a `Highs` object and call `setOptionValue` on it a bunch of times
- pass the HighsLp to the Highs object by calling `highs.passModel(lp)` and checking the returned status (reports `kOk`)
- solve by calling `highs.run()` and checking status (this is where `kError` is reported)

The HighsLp status is returned as `kOk`, so I assumed that I constructed the LP correctly -- please let me know if there's something else to do that perhaps the MIP solver is expecting that I have omitted.

**Comment by mckib2** [comment]
Also it occurs to me that I haven't thought about how to get a suitable MIP iteration count -- should this be the number of nodes the branch-and-bound algorithm has evaluated or is there another way it is reported?

**Comment by jajhall** [comment]
The number of nodes is obtained as 
int64_t mip_node_count 
from HighsInfo. The only other MIP data that can be obtained is 
  double mip_dual_bound;
  double mip_gap;

**Comment by jajhall** [comment]
> I just tried against latest master: [ab302f1](https://github.com/ERGO-Code/HiGHS/commit/ab302f1c1dd7a81a5abc50fc86f852afc115424f)

Me, too. I've added a unit test with this MIP and tried to reproduce exactly what you're doing, but it runs fine

> integrality_ (left empty for pure LPs)

Presumably you're setting (the equivalent of) 

  lp.integrality_ = {HighsVarType::kContinuous, HighsVarType::kContinuous, HighsVarType::kInteger};

> Same result, `highs.run()` reports -1 (`kError`). If I ignore the error (comment out the check), then the correct solution is reported, but all iteration counts are also -1, i.e. never populated.

These iteration counts (simplex, ipm, qp and crossover) are not known when solving a MIP, so -1 is returned

What about the following?

-     info.primal_solution_status
-     info.dual_solution_status
-     info.basis_validity
-     info.objective_function_value
-     info.mip_dual_bound
-     info.mip_gap

Could you also run with the following options settings

- log_dev_level = 2
- output_flag = true (ie don't set it false)


> 
>     * create a `Highs` object and call `setOptionValue` on it a bunch of times

What options are you setting?
 
>     * pass the HighsLp to the Highs object by calling `highs.passModel(lp)` and checking the returned status (reports `kOk`)
> 
>     * solve by calling `highs.run()` and checking status (this is where `kError` is reported)
> 
> 
> The HighsLp status is returned as `kOk`, so I assumed that I constructed the LP/MIP correctly -- please let me know if there's something else to do that perhaps the MIP solver is expecting that I have omitted.

**Comment by mckib2** [comment]
> > I just tried against latest master: [ab302f1](https://github.com/ERGO-Code/HiGHS/commit/ab302f1c1dd7a81a5abc50fc86f852afc115424f)
> 
> Me, too. I've added a unit test with this MIP and tried to reproduce exactly what you're doing, but it runs fine
> 
> > integrality_ (left empty for pure LPs)
> 
> Presumably you're setting (the equivalent of)
> 
> lp.integrality_ = {HighsVarType::kContinuous, HighsVarType::kContinuous, HighsVarType::kInteger};
> 

Correct, I'm passing integers `{0, 0, 1}` then casting to `HighsVarType`.

> > Same result, `highs.run()` reports -1 (`kError`). If I ignore the error (comment out the check), then the correct solution is reported, but all iteration counts are also -1, i.e. never populated.
> 
> These iteration counts (simplex, ipm, qp and crossover) are not known when solving a MIP, so -1 is returned
> 
> What about the following?
> 
>     * info.primal_solution_status
> 
>     * info.dual_solution_status
> 
>     * info.basis_validity
> 
>     * info.objective_function_value
> 
>     * info.mip_dual_bound
> 
>     * info.mip_gap
> 

info.primal_solution_status 2
info.dual_solution_status 0
info.basis_validity 0
info.objective_function_value -12.0
info.mip_dual_bound -12.0
info.mip_gap 0.0


> 
> Could you also run with the following options settings
> 
>     * log_dev_level = 2
> 
>     * output_flag = true (ie don't set it false)
> 
> 

[Highs.log](https://github.com/ERGO-Code/HiGHS/files/7741786/Highs.log)

The log file matches the console output for me.

> > ```
> > * create a `Highs` object and call `setOptionValue` on it a bunch of times
> > ```
> 
> What options are you setting?


        presolve: true
        sense: kMinimize
        time_limit: max double on platform
        highs_debug_level: kHighsDebugLevelMin
        dual_feasibility_tolerance: 1e-7
        ipm_optimality_tolerance: 1e-8
        log_to_console: true
        output_flag: true
        primal_feasibility_tolerance: 1e-7
        simplex_strategy: kSimplexStrategyDual
        simplex_crash_strategy: kSimplexCrashStrategyOff
        ipm_iteration_limit: max integer on platform
        simplex_iteration_limit: max integer on platform
        log_dev_level: 2

**Comment by mckib2** [comment]
Here are some of the customized compiler flags if it matters:

    -DIPX_ON=ON -UOPENMP -UEXT_PRESOLVE -USCIP_DEV -UHiGHSDEV -UOSI_FOUND

**Comment by jajhall** [comment]
I've replicated all this, and set your CMake flags, but no sign of an error return

What output do you get (with the following)?

- log_to_console: true
- output_flag: true
- log_dev_level: 2

What compiler are you using?

I need to stop now as it's after midnight...

**Comment by mckib2** [comment]
I can't seem to find the root cause of this yet either.  I'm going to start over from first-principles again and see if I can get a minimum viable call working

**Comment by mckib2** [comment]
I did do a little more digging on this, and the issue seems to occur during the course of running `debugHighsSolution`, specifically when `debugCompareHighsInfoInfeasibility` is called and attempts to compare two `HighsInfo` objects, one with `num_primal_infeasibility == -1` and the other with `num_primal_infeasibility == 0`.  The `debugCompareHighsInfoInteger` function sees these values are different and sets a `HighsDebugStatus::kLogicalError` which is never recovered from and eventually returns `kError` as I see.

The question is, why is the first of the two `HighsInfo` objects reporting a -1 instead of 0?  Is there an initialization function I need to call on something?

**Comment by mckib2** [comment]
I think I got it!  I incorrectly reported my `highs_debug_level` option above as `kHighsDebugLevelMin` when it was actually `kHighsDebugLevelCheap`.  This means the debug checks are not skipped [here](https://github.com/ERGO-Code/HiGHS/blob/003154cbf464f09e1b32b3be06637e2566d7c634/src/lp_data/HighsSolutionDebug.cpp#L101).  Switching to `kHighsDebugLevelNone` reports optimality the same as your [most recent test](https://github.com/ERGO-Code/HiGHS/blob/003154cbf464f09e1b32b3be06637e2566d7c634/check/TestMipSolver.cpp#L106) pushed to master

**Comment by jajhall** [comment]
That'll be it. One of the tasks of that debug flag is to check that info values have been set correctly. I changed the interpretation of infeasibility info returned by the MIP solver relatively recently and clearly haven't run with this debug flag set since. 🤭
