### ISSUE TITLE
Simple unboundedness no longer detected in presolve

### ISSUE THREAD

**Issue by mckib2** [ERGO-Code/HiGHS#648]
The following simple problem's unboundedness used to be detected in presolve but is no longer using current master.  We believe this may be a regression in the presolve.

[test_zero_column_2.mps.txt](https://github.com/ERGO-Code/HiGHS/files/7775284/test_zero_column_2.mps.txt)

And reproduced here since it's small:
```
* Problem:    test_zero_column_2
* Class:      LP
* Rows:       4
* Columns:    4
* Non-zeros:  12
* Format:     Free MPS
*
NAME test_zero_column_2
ROWS
 N R0000000
 L R0000001
 L R0000002
 E R0000003
 E R0000004
COLUMNS
 c0 R0000000 0.5488135039 R0000004 0.9636627605
 c0 R0000003 0.4236547993 R0000002 0.7781567509
 c0 R0000001 0.0710360582
 c1 R0000000 -1
 c2 R0000000 0.6027633761 R0000004 0.7917250381
 c2 R0000003 0.4375872113 R0000002 0.9786183422
 c2 R0000001 0.0202183974
 c3 R0000000 0.544883183 R0000004 0.5288949198
 c3 R0000003 0.8917730008 R0000002 0.7991585642
 c3 R0000001 0.8326198455
RHS
 RHS1 R0000001 0.4614793623 R0000002 0.7805291763
 RHS1 R0000003 0.5680445611 R0000004 0.9255966383
BOUNDS
 FR BND1 c0
 FR BND1 c1
 FR BND1 c2
 FR BND1 c3
ENDATA
```

Example HiGHS invocation:
```
./highs --solver simplex --presolve on test_zero_column_2.mps
```

CC @mdhaber

**Comment by jajhall** [comment]
I'm puzzled by this, as 

1. master identifies unboundedness OK for me
2. I don't see the reference to it in [scipy/scipy#15217](https://github.com/scipy/scipy/pull/15217)

**Comment by mckib2** [comment]
I should clarify: we see non-zero simplex_iteration count where we expected to see this problem identified in the presolve as unbounded.  The corresponding test in scipy is [here](https://github.com/scipy/scipy/blob/a11ff1ea8fff42f1d2d95f2cc77b408200865c14/scipy/optimize/tests/test_linprog.py#L736)

**Comment by jajhall** [comment]
I'll explain in the morning!

**Comment by jajhall** [comment]
> I should clarify: we see non-zero simplex_iteration count where we expected to see this problem identified in the presolve as unbounded (i.e., iteration count == 0). The corresponding test in scipy is [here](https://github.com/scipy/scipy/blob/a11ff1ea8fff42f1d2d95f2cc77b408200865c14/scipy/optimize/tests/test_linprog.py#L736)

Presolve identifies the LP as dual infeasible. Previously HiGHS interpreted this as implying primal unboundedness, and returned this model status without performing any simplex iterations. Although problems that are dual infeasible are _usually_ primal unbounded, they can be primal infeasible. Thus, mathematically, all that should be deduced is the model status `kUnboundedOrInfeasible`, and this is what commercial solvers do.

However, in HiGHS, unless the option `allow_unbounded_or_infeasible` is changed to `true`, from its default value of `false`, the primal simplex solver will be used to identify whether the LP is primal unbounded or primal infeasible. Hence, to allow the correct mathematical status to be identified, simplex iterations are required.

**Comment by mckib2** [comment]
Thanks @jajhall, this is good info!

**Comment by mckib2** [comment]
> However, in HiGHS, unless the option allow_unbounded_or_infeasible is changed to true, from its default value of false, the primal simplex solver will be used to identify whether the LP is primal unbounded or primal infeasible. Hence, to allow the correct mathematical status to be identified, simplex iterations are required.

Will this be done in a future HiGHS commit?

**Comment by jajhall** [comment]
It is done now - that's why you get the additional simplex iterations quoted.
