### ISSUE TITLE
MIP solution contains non-integer values

### ISSUE THREAD

**Issue by mckib2** [ERGO-Code/HiGHS#649]
Primal solution values returned by the MIP solver are often very close to integral (on my machine and the examples I tried, usually within 1e-15).  The question that comes up for us is: should the MIP solver do the rounding to obtain truly integral solution variables or should the consumer of the MIP solver expect that the answer might only be really close to integral?  For SciPy, we will probably want to round the answers when an integral constraint is given.

I only open this issue to ask the question -- I am fine either way (upstream rounding vs downstream rounding).  I notice that when writing solutions to file the tolerance is set at [1e-13](https://github.com/ERGO-Code/HiGHS/blob/8e0f2a523281fe6c6eca29236fcdb89552d1ed7c/src/lp_data/HighsModelUtils.cpp#L213).  So I suppose a related question would be if the almost-integral solution values are ever interesting or needed, i.e. is there a reason not to round the answers?

This is probably a frequent enough situation that you already have plenty of examples, but here's one just in case:
[test_mip1.mps.txt](https://github.com/ERGO-Code/HiGHS/files/7775381/test_mip1.mps.txt)

**Comment by mdhaber** [comment]
@jajhall I'm rethinking this because I'm remembering that it may not be natural for LP algorithms to strictly satisfy bound constraints. If bound constraints are only satisfied within some tolerance, then users should not expect integer constraints to be exactly satisfied either, and so we shouldn't round.

**Comment by jajhall** [comment]
No rounding of solution values of integer variables should take place. Like small primal and dual infeasibilities, the differences are artefacts of the solution process and should be available so users.
