### ISSUE TITLE
truncation warnings

### ISSUE THREAD

**Issue by FlorianSchwendinger** [ERGO-Code/HiGHS#659]
I currently write a **R** interface to the **highs** solver.

Doing that I face the following warnings.
```
highs/mip/HighsMipSolverData.cpp:773:45: warning: ‘%ld’ directive output may be truncated writing between 1 and 17 bytes into a region of size 16 [-Wformat-truncation=]
highs/mip/HighsMipSolverData.cpp:798:46: warning: ‘%.12g’ directive output may be truncated writing between 1 and 19 bytes into a region of size 16 [-Wformat-truncation=]
highs/mip/HighsMipSolverData.cpp:805:46: warning: ‘%.13g’ directive output may be truncated writing between 1 and 20 bytes into a region of size 16 [-Wformat-truncation=]
highs/mip/HighsMipSolverData.cpp:795:46: warning: ‘%.11g’ directive output may be truncated writing between 1 and 18 bytes into a region of size 16 [-Wformat-truncation=]
highs/mip/HighsMipSolverData.cpp:792:51: warning: ‘__builtin___snprintf_chk’ output may be truncated before the last format character [-Wformat-truncation=]
```

Changing `highs/mip/HighsMipSolverData.cpp:773:45: ` from
```
  case 8:
    std::snprintf(printString.data(), 16, "%" PRId64 "k", val / 1000);
```
to 
```
  case 8:
    std::snprintf(printString.data(), 16, "%" PRId64 "k", (int64_t)(val / 1000.0));
```
or
```
  case 8:
    std::snprintf(printString.data(), 16, "%" PRId64 "k", (int64_t)std::ceil(val / 1000));
```
removes the warning. The same applies to `highs/mip/HighsMipSolverData.cpp:798:46`.

The other warnings come from `static std::array<char, 16> convertToPrintString(double val)`
and if I understood the resources I found correctly this warning is a bug in gcc.
For 
```
std::snprintf(printString.data(), 16, "%.9g", val);
```
there is no warning but for 
```
std::snprintf(printString.data(), 16, "%.10g", val);
```
and the others there is. An easy fix is to replace with (for case 4)
```
std::snprintf(printString.data(), 16, "%i.%" PRId64, int(val), int64_t(1e11 * val));
```

**Comment by jajhall** [comment]
Thanks. This is for MIP solver output, written by @lgottwald so I'll leave it to her to take any action.

**Comment by lgottwald** [comment]
I disabled that warning. This is a false positive and truncation does not occur. The case distinction ensures that the formatted output always fits.
I don't see how the fixes are correct when I want to print a double number and not an integer.

**Comment by lgottwald** [comment]
Also the warnings, even if they were correct, would never be a safety issue. The worst that could happen is that output looks ugly, but the output looks exactly as I want it to look regarding the number formatting.

**Comment by jajhall** [comment]
Thanks. I hadn't realised that the suggested changes would affect the carefully-formatted output. 
So @FlorianSchwendinger this isn't an issue
