### ISSUE TITLE
Should termination on `mip_gap_limit` yield status `kOptimal`?

### ISSUE THREAD

**Issue by DillonJ** [ERGO-Code/HiGHS#665]
I have tested mip_gap_limit - I made some comments in https://github.com/ERGO-Code/HiGHS/issues/660

I am using HiGHS.jl and upon termination on `mip_gap_limit`, I am getting the below unknown status code. 

```julia
julia> termination_status(m)
OTHER_ERROR::TerminationStatusCode = 24
```
I see from here that it is set to `kObjectiveTarget` which perhaps isn't recognised by HiGHS.jl? As @odow points out here https://github.com/ERGO-Code/HiGHS/issues/660#issuecomment-1008197413, "I think most solvers regard "optimal" to mean "optimal given the tolerances specified by the user".

Should HiGHS be returning `kOptimal` instead?

https://github.com/ERGO-Code/HiGHS/blob/a71be5211e00c6b38ddd88da663208db4d2a4dbd/src/mip/HighsMipSolverData.cpp#L1310-L1314

**Comment by odow** [comment]
HiGHS.jl does support `kObjectiveTarget`: https://github.com/jump-dev/HiGHS.jl/blob/221489acddce5cf224379d5f5900fcc2b23fc643/src/MOI_wrapper.jl#L1601-L1602

But there might be other changes between v1.1.1 and the current `master` that we haven't addressed. Caveat emptor when using any custom binaries.

**Comment by lgottwald** [comment]
I think the status should in this case not be optimal. Termination on a gap limit is very different as there are nodes in the queue that are left to process.

With a relative gap limit of 5% the primal bound that would allow termination on status optimal can be vastly different depending on how the termination occurs. It might happen that the optimal solution is found quickly and the dual bound is quickly proven to be within 5% of that primal bound, but it could also happen that the solver starts with a considerably worse solution, then pushes the dual bound to optimality and then finds a primal solution that is 5% worse than the optimal dual bound. So with that gap limit HiGHS can with changing the random seed or permuting the instance terminate with primal bounds that vary considerably on the same instance and would then claim them all as optimal. E.g. when the optimal solution value of an instance is 10 then HiGHS could terminate with a dual bound of 10 and a primal bound of 10.52 or alternatively terminate with primal bound of 10 and dual bound of 9.5.

It would be counter intuitive to claim both primal solutions as optimal as optimality is defined to have proven no better solution exists and is an intrinsic property of the instance. Permuting the instance should not alter the primal value claimed as optimal. Just as in LP, where the optimality is proven without needing any tolerance on the gap but by having a pair of primal/dual feasible solutions (within tolerances) in MIP the same is true, even though the dual feasible solutions of all leaves of the branch-and-bound tree are part of the proof. Proving optimality of a MIP does not need a tolerance for the gap at all and only the LP relaxation needs a tolerance.

**Comment by lgottwald** [comment]
But maybe I am wrong an that is really what users expect, I will see if all other solvers are consistent in this.

**Comment by odow** [comment]
I think users _do_ expect that the solver will report OPTIMAL (and I think it's what most (all) other solvers do?). 

Of course, you can decide not to do this in C++, and we can work-around it in the Julia wrapper, so I'm not too bothered about what choice you make. Either are defensible.

**Comment by odow** [comment]
Per Gurobi https://www.gurobi.com/documentation/9.5/refman/mipgap2.html#parameter:MIPGap

> The MIP solver will terminate (with an optimal result) when the gap between the lower and upper objective bound is less than MIPGap times the absolute value of the incumbent objective value.
