### ISSUE TITLE
Windows linking issue

### ISSUE THREAD

**Issue by jajhall** [ERGO-Code/HiGHS#680]
A user has contacted me with the following issue

> I have downloaded the file HiGHS.v1.1.1x86_64_w64_mingw32_cxx11.tar.gz and ‘unzipped’ the files to my C:\HiGHS directory.
> However, on trying to execute highs.exe I was the informed that the following files could not be found viz:

> libgcc_s_seh-1.dll
> libgomp-1.dll
> libstdc++-6.dll
> libwinpthread-1.dll libstdc++-6.dll

> I downloaded copies of each of these files from the internet and placed them in the c:\HiGHS directory, but when I now attempt to run highs.exe I get the message
> highs.exe Application Error
> The application was unable to start correctly (0xc000007b).
> Click OK to close the application.

I'd ask @galabovaa, but she's busy working on her thesis until the end of February

Perhaps the solution is obvious to one of our other users

**Comment by NPC** [comment]
@jajhall I'm not (yet) experienced with HiGHS, but I got the support libraries [here](https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v0.5.1%2B0/CompilerSupportLibraries.v0.5.1.x86_64-w64-mingw32-libgfortran5.tar.gz), and now it works for me.

**Comment by jajhall** [comment]
> @jajhall I'm not (yet) experienced with HiGHS, but I got the support libraries [here](https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v0.5.1%2B0/CompilerSupportLibraries.v0.5.1.x86_64-w64-mingw32-libgfortran5.tar.gz), and now it works for me.

Thank you so much @NPC

**Comment by jajhall** [comment]
Thanks @NPC, the user is now liking HiGHS OK!
