### ISSUE TITLE
Parse error for lp file

### ISSUE THREAD

**Issue by gregy4** [ERGO-Code/HiGHS#701]
HiGHS (version 1.1.0) has problem with reading of some lp files. So far I identified problem with length of objective function. Attached example works in case last element is removed (+1 w80) so it seems there's some limit in the solver parser. I used binary version of the solver on windows 10.

[test.zip](https://github.com/ERGO-Code/HiGHS/files/7966336/test.zip)

Best regards,
Jan

**Comment by jajhall** [comment]
Yes, HiGHS used to require .lp files to satisfy the 255-character line length limit [http://lpsolve.sourceforge.net/5.0/CPLEX-format.htm](url). 
This is not the case in the development version of HiGHS - which, unlike v1.1, will also read MIP problems from .lp files.

We will be releasing v1.2 in the next few weeks so, until then, I suggest that you use the master branch.
