### ISSUE TITLE
Use with quadwild

### ISSUE THREAD

**Issue by fire** [ERGO-Code/HiGHS#702]
Hi,

Since I couldn't find a discussion forum, I am looking to use HiGHS with quadwild.

The author says quadwild requires "integer variables with quadratic energy term and linear constraints".

Can HiGHS do that?

https://github.com/nicopietroni/quadwild/issues/2

@nicopietroni

**Comment by jajhall** [comment]
Guessing that "quadratic energy term" is in the objective function, you are looking to solve mixed-integer quadratic programming (MIQP) problems. HiGHS cannot solve MIQPs, although it is something we are looking to add, but not in the next 12 months.

Cbc itself cannot solve MIQP problems, but the following discussion may help you

https://github.com/coin-or/SONNET/issues/3
