### ISSUE TITLE
Creating Windows *.lib file for static linking

### ISSUE THREAD

**Issue by jajhall** [ERGO-Code/HiGHS#703]
A user has observed that 

> All of the other community-based and commercial-based LP/MILP/NLP solvers have *.lib files and I have standardized on this approach when I link using Intel Fortran i.e., the code is statically linked to *.lib files at compile time.

HiGHS does not apparently create such a *.lib file, and it sounds as if it should.

**Comment by odow** [comment]
For future readers: duplicate of https://github.com/ERGO-Code/HiGHS/issues/590.

**Comment by jajhall** [comment]
Indeed, I spotted this earlier and transferred my comment. But I should have added the redirection. :-)
