### ISSUE TITLE
log indentation

### ISSUE THREAD

**Issue by svigerske** [ERGO-Code/HiGHS#708]
I'm setting log callbacks and get output like this

```

Presolving model
         5 rows, 6 cols, 12 nonzeros
         5 rows, 6 cols, 12 nonzeros
         Presolve : Reductions: rows 5(-0); columns 6(-0); elements 12(-0)
         Solving the presolved LP
         Using EKK dual simplex solver - serial
           Iteration        Objective     Infeasibilities num(sum)
                   0     0.0000000000e+00 Pr: 3(900) 0s
                   3     1.5367500000e+02 Pr: 0(0) 0s
         Solving the original LP from the solution after postsolve
         Model   status      : Optimal
         Simplex   iterations: 3
         Objective value     :  1.5367500000e+02
         HiGHS run time      :          0.00
```

The indentation on all but the 2nd line is because there is no `if (prefix)` in the `else` in `highsLogUser()`:

https://github.com/ERGO-Code/HiGHS/blob/e0b27f8d89d2277f419841448273fec27563b038/src/io/HighsIO.cpp#L127-L128

There is no indentation on the 2nd line because the log message starts with a `\n`:

https://github.com/ERGO-Code/HiGHS/blob/e0b27f8d89d2277f419841448273fec27563b038/src/presolve/HPresolve.cpp#L3896-L3897

If you want to automatically indent log messages, you may want to avoid putting linebreak characters into it.

**Comment by jajhall** [comment]
Thanks. The logging callbacks feature hasn't been touched since it was written in Minneapolis 3 years ago. Back then we had the idea that each logging line would begin with a statement of the severity of the logging line. However, this just creates noise, since most are INFO. We've also removed the distinction between logging lines and general output. Hence the spaces that you observe should disappear. This will be done in due course.

**Comment by NPC** [comment]
@jajhall @svigerske I'll raise a separate ticket if needed, but (I hope) a quick question — are these message callbacks documented anywhere? Can they be assigned from C# API? I don't see it there, and don't understand the source code well enough to see how they are used.

**Comment by jajhall** [comment]
We will be working on other callbacks soon (user-termination, and adding MIP cuts) so I started looking at the logging callback. It needs to be changed - the second argument is useless - and then it will be documented, and maybe someone will identify how to use them from C#

**Comment by svigerske** [comment]
I just call `HiGHS::setLogCallback()` with a function and callback data. The function is called with a string and the callback data and then prints the string.

https://github.com/coin-or/GAMSlinks/blob/2486803854290125969f46604acb7400adb0db75/src/highs/GamsHighs.cpp#L37-L59

I have no idea what of this is accessible via C#.

**Comment by NPC** [comment]
@svigerske thanks for the helpful example! This method is not exposed in the C# interface, so I'll wait for updates from @jajhall and the upcoming review.

I tried adding a `setLogCallback` wrapper to `highs_csharp_api.cs`, following examples of other methods, but I get this error:  
```
System.EntryPointNotFoundException: Unable to find an entry point named 'Highs_setLogCallback' in DLL 'libhighs'
```

So, looks like the DLL doesn't make it accessible either.
