### ISSUE TITLE
task not trivially copyable

### ISSUE THREAD

**Issue by svigerske** [ERGO-Code/HiGHS#720]
For HiGHS 1.2, compiling with Intel Compilers 2021.2.0.20210228 on Windows fails for me with
```
\path\to\HiGHS\src\parallel/HighsTask.h(94): error: static assertion failed with "given task type must be trivially copyable
"
      static_assert(IS_TRIVIALLY_COPYABLE(F),
      ^
          detected during:
            instantiation of "void HighsTask::setTaskData(F &&) [with F=lambda []()->void]" at line 282 of "\path\to\HiGHS\src\parallel/HighsSplitDeque.h"
            instantiation of "void HighsSplitDeque::push(F &&) [with F=lambda []()->void]" at line 39 of "\path\to\HiGHS\src\parallel/HighsParallel.h"
            instantiation of "void highs::parallel::spawn(HighsSplitDeque *, F &&) [with F=lambda []()->void]" at line 81 of "\path\to\HiGHS\src\parallel/HighsParallel.h"
            instantiation of "void highs::parallel::TaskGroup::spawn(F &&) const [with F=lambda []()->void]" at line 85 of "\path\to\HiGHS\src\mip\HighsMipSolverData.cpp"

compilation aborted for \path\to\HiGHS\src\mip\HighsMipSolverData.cpp (code 2)
```
Is there some workaround?

**Comment by lgottwald** [comment]
Probably the static assert can be commented out. Likely the Intel compiler does simply not set the property of being trivially copyavle for the compiler generated type, but in reality nothing prevents it from being copied with memcpy.
Would recommend to check whether the unit tests for parallelism pass with several invocations.

**Comment by svigerske** [comment]
Thanks. After taking the assert out, two invocations of `nmake tests` pass.  I hope that included tests for parallelism.

**Comment by lgottwald** [comment]
Assuming it does the ctest of cmake then yes it does. It will invoke unit_test which contains a parallel Fibonacci Evaluation and matrix multiplication and will use some parallel invocations for the instance tests.
It is unfortunate that there is no compiler guaranteed way but the current solution is closest to what I could get to standard compliant and does not violate strict aliasing rules.

**Comment by lgottwald** [comment]
And when the static assert passes it is guaranteed which it does for most compilers.

**Comment by svigerske** [comment]
There were 148 tests, starting with
```
        Start   1: capi_unit_tests
  1/148 Test   #1: capi_unit_tests ..................   Passed    0.04 sec
        Start   2: unit-test-build
  2/148 Test   #2: unit-test-build ..................   Passed    3.89 sec
        Start   3: unit_tests_all
  3/148 Test   #3: unit_tests_all ...................   Passed   78.86 sec
```

You might want to add some `#ifdef __INTEL_COMPILER` (`&& Windows`?)  to the definition of `IS_TRIVIALLY_COPYABLE` some day.

**Comment by lgottwald** [comment]
Yes, I'll see that I get this fixed and maybe add a warning instead

**Comment by mckib2** [comment]
@mdhaber I believe this is the issue you encountered that was also resolved by simply commenting out the `static_assert`

**Comment by h-vetinari** [comment]
It's a pity that this was reverted IMO. VS2019 (with default toolset vc142) can construct the types correctly, and the older VS2017 is EOL.
