### ISSUE TITLE
C API: lpDimMpsRead and lpDataMpsRead

### ISSUE THREAD

**Issue by odow** [ERGO-Code/HiGHS#723]
What are these functions doing? (I remember asking you about this at some point.)

https://github.com/ERGO-Code/HiGHS/blob/500cdf47a6330252db4156148f90d99cc8d22cf7/src/interfaces/highs_c_api.cpp#L171-L211

They hard-code `ml.mps` as the filename, which seems non-obvious? Can the be deprecated? It looks like they were added for a special purpose which might not exist anymore?

**Comment by jajhall** [comment]
Handy if your reviews can count formally - even if I can force a PR as admin

**Comment by odow** [comment]
Sure. Although I'm not sure I'll be much help for some of the nitty-gritty PRs :)
