### ISSUE TITLE
Unspecific "error loading file"

### ISSUE THREAD

**Issue by Bouncner** [ERGO-Code/HiGHS#728]
I am using PuLP to formulate an ILP problem, which works fine with gurobi. When using HiGHS, I get the pretty unspecific error (I am using the direct call that PuLP does to ensure that it's not a PuLP error):
```
$ highs --model_file /var/folders/pf/p_4b5xx54_n00pf2phf_1x980000gn/T/76a17ff536d847a3a5934991380c93d0-pulp.mps
Running HiGHS 1.2.0 [date: 2022-02-11, git hash: f11b7936]
Copyright (c) 2022 ERGO-Code under MIT licence terms
Number of BV entries in BOUNDS section is 178160
WARNING: LP matrix packed vector contains 52683 |values| in [1.79769e+308, 1.79769e+308] greater than 1e+15
Error loading file
```

Is there a way to better debug this error?

PS: I can share the `.mps` file any time, if that helps.

**Comment by odow** [comment]
>  I can share the .mps file any time, if that helps

Yes, please.

What are all the `Inf` values? PuLP probably shouldn't write out bounds if they are effectively infinite.

Also, did you compile HiGHS directly or use one of the precompiled binaries?

**Comment by Bouncner** [comment]
I compiled it manually on MacOS 12.2. To be honest, I do not know where the infinity values come from. I have never really digged into any solver files before and was happy that Gurobi (and SCIP) "just worked".

Here is the file: [76a17ff536d847a3a5934991380c93d0-pulp.mps.bz2](https://www.dropbox.com/s/ll88cu2ml93vmw2/76a17ff536d847a3a5934991380c93d0-pulp.mps.bz2?dl=0)

**Comment by odow** [comment]
You should take a look at your formulation. Lots of your variables have infinite coefficients in the constraint matrix:
```
    c_(1,_101,_6,_4)  _C70500    1.797693134862e+308
```
I don't have a Gurobi license at the moment, but what does Gurobi report? Shouldn't it also complain?

**Comment by Bouncner** [comment]
I have found the infinities and I use them quite often and it worked fine so far (it's basically simulating a constraint by adding immense costs).

But I need to dig a little bit deeper. Thanks for hinting. I'll do some more debugging and close it for now.

**Comment by Bouncner** [comment]
Sorry, since I think the error is not that helpful, I'll reopen.

Moreover, the error code is 1, which should be a warning but not an error (https://github.com/ERGO-Code/HiGHS/issues/527#issuecomment-946575028). But the last message states an error.

**Comment by jajhall** [comment]
Interesting. I agree that the HiGHS return should be error, not warning. I also wonder how Gurobi interprets values that are unreasonable use as coefficient matrix entries. I'll have a look.

**Comment by jajhall** [comment]
So, using the LP min -x s.t. 1e300*x >= b, 0<= x <= 1, for a range of (positive) values of b, Gurobi gives Optimal objective  0.000000000e+00, so it looks as if Gurobi interprets 1e300*0 to be any positive number you want! 

For me, it's much better to refuse to accept constraint matrix coefficients with absolute value greater than a tolerance

**Comment by jajhall** [comment]
Although "WARNING" is incorrect in the log message, readModel(filename) returns the correct value `HighsStatus::kError`, which is cast to -1 in the C API, so there's an interpretation error somewhere outside HiGHS

HiGHS retains the large values(s) so, if the error code is ignored, run() has excess values in the matrix, and what happens is anyone's guess. I'll modify run() so that it returns an error if it's given a matrix with excess values.

**Comment by Bouncner** [comment]
> Although "WARNING" is incorrect in the log message, readModel(filename) returns the correct value `HighsStatus::kError`, which is cast to -1 in the C API, so there's an interpretation error somewhere outside HiGHS

I don't know if we are talking about the same thing, but I meant the return code of calling highs. Even though it's outputting an error, it's returning 1.
```
$ highs /var/folders/pf/p_4b5xx54_n00pf2phf_1x980000gn/T/12fa4c5bd7e2440d83d4035d9cf67913-pulp.mps
Running HiGHS 1.2.0 [date: 2022-02-11, git hash: f11b7936]
Copyright (c) 2022 ERGO-Code under MIT licence terms
Number of BV entries in BOUNDS section is 178160
WARNING: LP matrix packed vector contains 52683 |values| in [1.79769e+308, 1.79769e+308] greater than 1e+15
Error loading file
$ echo $?
1
```

**Comment by jajhall** [comment]
Ah, I see what you mean now. When you said that this is what happened when running HiGHS via PuLP, is hadn't realised that PuLP is just running the HiGHS executable. Indeed, as you see in app/RunHighs.cpp, an error return from a Highs method results in the executable returning 1. I've never given this value much thought but, as you say, it should be -1.

**Comment by Bouncner** [comment]
This might be of interest for you.

I checked my current LP model. I changed the model some time ago and since I have only used Gurobi, I haven't realized that some changes made it infeasible for Cbc and Co. (might be the same for HiGHS).

I think (not too sure) the reason are the extremely large values that are added. These values are the default values for a matrix that contains costs (`np.finfo(np.float64).max` which is `1.7976931348623157e+308`). These costs are only of a "real value" when the item is actually supported. In this case, we overwrite the large default value with the actual cost.
These costs are all added multiplied with the current (binary) configuration. Now the probably important part is, that there is further constraint that says that the binary variable activating these costs can never be 1. So these extremely high values are never actually occuring, ensured by constraints to the problem.
I don't know how Gurobi does it, but I assume that Gurobi is able to neglect these extreme values since I finds out that the costs are never going to be actually used.

I fixed my model to no longer add these costs when they cannot occur anyways and HiGHS seems to work just fine now.

**Comment by jajhall** [comment]
Thanks @Bouncner It's possible that Gurobi's presolve identifies that the binaries associated with these extreme values are 0, so removes them (and the extreme values) from the matrix. HiGHS doesn't get that far, throwing out the model before presolve. 

However, if the extreme values aren't removed, they may be "active" before the MIP solver has identified that the binaries would be zero. All sorts of horrible behaviour could ensue!

I can see how the extreme values have crept into your model, but I'd rather not allow HiGHS to use such values anywhere.
