### ISSUE TITLE
Wrong enum values in C# interface

### ISSUE THREAD

**Issue by tosttost** [ERGO-Code/HiGHS#738]
HighsStatus.h:
```
enum class HighsStatus { kError = -1, kOk = 0, kWarning = 1 };
```
highs_csharp_api.cs:
```
public enum HighsStatus
{
   kOk,
   kWarning,
   kError
}
```
which defaults to 0, 1, 2.
Maybe other enums need explicit definition of the corresponding integer values as well.

**Comment by jajhall** [comment]
I've fixed this now (in master), and looked through the other enums. 
HighsMatrixFormat wasn't strictly wrong, but referred to a format kNone that is no longer used.
