### ISSUE TITLE
Experiment: new release binaries

### ISSUE THREAD

**Issue by odow** [ERGO-Code/HiGHS#746]
We're experimenting with a new way of distributing binaries compiled for Julia. Here are three generic binaries for x86_64 machines:

**v1.2.2**

 * [highs_linux.tar.gz](https://github.com/ERGO-Code/HiGHS/files/8551106/highs_linux.tar.gz)
 * [highs_macOS.tar.gz](https://github.com/ERGO-Code/HiGHS/files/8551112/highs_macOS.tar.gz)
 * [highs_windows.tar.gz](https://github.com/ERGO-Code/HiGHS/files/8551113/highs_windows.tar.gz)

**v1.2.0**

 * [highs_linux.tar.gz](https://github.com/ERGO-Code/HiGHS/files/8104846/highs_linux.tar.gz)
 * [highs_windows.tar.gz](https://github.com/ERGO-Code/HiGHS/files/8104847/highs_windows.tar.gz)
 * [highs_macOS.tar.gz](https://github.com/ERGO-Code/HiGHS/files/8104848/highs_macOS.tar.gz)

If people, particularly on Windows machines, can try out these releases that'd be very helpful.

Everything is dynamically linked, but the tarball contains all of the linked files, so it should be relocatable with no issues. People using the executable can download the release, extract the contents, and then point their software to `/bin/highs`.

This should let people download and extract the binary without having to recompile: https://github.com/JuliaPackaging/Yggdrasil/pull/4456#issuecomment-1046218509
And we can host the releases on the HiGHS repository so we don't have people digging through weirdly named HiGHS_jll releases.

_As a reminder to myself, here's the code to construct releases_
```Julia
import JLLPrefixes
import Tar

for (name, platform) in Dict(
    "windows" => Base.BinaryPlatforms.Platform("x86_64", "windows"),
    "macOS" => Base.BinaryPlatforms.Platform("x86_64", "macOS"),
    "linux" => Base.BinaryPlatforms.Platform("x86_64", "linux"),
)
    prefix = JLLPrefixes.expanduser("/tmp/$name")
    artifact_paths = JLLPrefixes.collect_artifact_paths(
        ["HiGHS_jll"];
        platform = platform,
    )
    JLLPrefixes.copy_artifact_paths(prefix, artifact_paths)
    tarball = "highs_$(name).tar.gz"
    Tar.create(prefix, pipeline(`gzip -9`, tarball))
end
```

**Comment by NPC** [comment]
@odow thanks for putting these together, this is way better than chasing various files all over the place. In the long run, it'd be good to include the version number in the archive file name.

I tested this on Win10, calling from C#, and get the following error:  
```
System.AccessViolationException
  HResult=0x80004003
  Message=Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
  Source=<Cannot evaluate the exception source>
  StackTrace:
<Cannot evaluate the exception stack trace>
```

It crashes in `run()` method of `highs_csharp_interfaces.cs`, which calls `HighsLpSolver.Highs_run(this.highs)`.

This is not an issue with this specific distribution method, though. I receive the same error if I try to call the dll from Julia pre-builds (file 'HiGHS.v1.2.1.x86_64-w64-mingw32-cxx11.tar.gz', same error for v1.2.0 or 1.2.1). It worked with v1.1.1 from the pre-builds. Solving my MPS from the highs.exe works fine, so it seems to be something in the wrapper, or the way I'm calling it, or the way it was built this time. 

I'll keep investigating, but perhaps you'll have ideas too.

**Comment by NPC** [comment]
Update: Without the parallel flag the problem is solved correctly, so it has to do something with that (could this still be a build issue?). This is how I was setting it:
```csharp
solver.setStringOptionValue("parallel", "on");
```

**Comment by NPC** [comment]
@odow hello, do you plan to release binaries for 1.2.2?

**Comment by odow** [comment]
> do you plan to release binaries for 1.2.2

I hadn't noticed this new tag. Builds are running now: https://github.com/JuliaPackaging/Yggdrasil/pull/4808

**Comment by NPC** [comment]
@odow I see it, thank you!

**Comment by odow** [comment]
I've updated the links in the top post.
