### ISSUE TITLE
C API: missing Highs_getLongInfoValue

### ISSUE THREAD

**Issue by odow** [ERGO-Code/HiGHS#747]
The C API is missing a function to query `record_int64` info values:

https://github.com/ERGO-Code/HiGHS/blob/17237a320d5c32a95c18e1e8cf2ef4a365e9e889/src/lp_data/HighsInfo.h#L251-L254

x-ref: https://github.com/jump-dev/HiGHS.jl/issues/86

**Comment by jajhall** [comment]
I've looked at this, but it seems to have C++ implications that are beyond me @lgottwald
