### ISSUE TITLE
communicate include paths 

### ISSUE THREAD

**Issue by mattmilten** [ERGO-Code/HiGHS#75]
The modularized directory structure in `src/` is not exported (e.g. in `highs-config.cmake`), so external projects like SCIP will get include errors.

There are two solutions: Either modify the `#include` statements in the code to reflect the new structure or export all subdirectories so they can be added via `-I` when linking to HiGHS.

I very much prefer the first option.

**Comment by galabovaa** [comment]
We have modified the include statements in the code. Also changed the cmake installation code to reflect the header hierarchy. I tried calling HiGHS from a source file elsewhere and compiling with 
-I highs_install_path/include -L highs_install_path/lib 

works fine. Does that fix what is exported in highs-config.cmake?

**Comment by mattmilten** [comment]
It all looks fine to me, now. If you were using CMake to link to HiGHS, a simple `find_package(HiGHS)` and the correct path in `HIGHS_DIR` should've been enough.
