### ISSUE TITLE
Fail on (numerically challenging) binary expansion problems

### ISSUE THREAD

**Issue by joaquimg** [ERGO-Code/HiGHS#765]
I have been trying to use HiGHS as the testing solver and readme solver in https://github.com/joaquimg/QuadraticToBinary.jl (current is Cbc).

This package generates binary expansions to solver QCQP as a MIP. Because of binary expansion, the problem does have numerical issues.

I gathered a few examples to showcase some fail of HiGHS. All of them come from binary expansions of the qp:
```
     minimize 2 x^2 + y^2 + xy + x + y + 1
        s.t.  x, y >= 0
              x + y = 1
```

They are named: `moiqp3qtbX.mps`, where `X` is a proxy on the precision, so higher `X` more terms in the binary expansion and less numerical stability, `X` varies from 3 to 8.

HiGHS seems to do well for `X=3`, `X=4` and `X=5`.
HiGHS seems to return wrong results for `X=6` (root node solution seems off) and `X=7` (this stops at presolve).
HiGHS returns Infeasible for `X=8`

Here are the files:
https://gist.github.com/joaquimg/56abb500c315d3d1251ddc939dd5529b

I tested those mps files on Xpress, which returns reasonable results for all, but prints that `X=8` might be numerically unstable (result precisely matches the QP solution though).

I have been using https://github.com/jump-dev/HiGHS.jl 1.0.0 and other instances seem fine (cc @odow)

**Comment by jajhall** [comment]
Thanks, We'll have a look at these

**Comment by lgottwald** [comment]
I had a look and the matrix values are simply too small for default feasibility tolerances starting from the X=6. From then they still solve fine when setting tightened feasibility tolerances by setting:
```
mip_feasibility_tolerance = 1e-9
primal_feasibility_tolerance = 1e-9
```
I need to have a closer look if I can be more careful in presolve to avoid these issues, but many things can happen with a default tolerance of 1e-6 and constraints like this:
```
x56 -5.960464477539063e-8 * x1 <= 0
```
Or bounds like this:
```
LO bounds    x3        0
UP bounds    x3        5.960464477539063e-8 
```

The variable x3 with above bounds is allowed to take values v with -1e-6 <= v <= 1.06e-6 in default feasibility tolerance. This changes the meaning of the column considerably as the range increases on the order of 1e2.
Is it possible to scale above columns differently when they need to have such small bound values?

**Comment by jajhall** [comment]
These do seem to be extreme problems. Other than possible interest for @lgottwald in the context of presolve, you're better off waiting until it is possible for the critical parts of HiGHS to be run in quad precision, something that is probably already implemented in Xpress.

**Comment by joaquimg** [comment]
Thanks! and I agree these problems are extreme.

For completeness... I ran the example `X=6` again with

mip_feasibility_tolerance = 1e-9
primal_feasibility_tolerance = 1e-9

and got:

```
Presolving model
191 rows, 100 cols, 461 nonzeros
164 rows, 91 cols, 416 nonzeros

Solving MIP model with:
   164 rows
   91 cols (34 binary, 0 integer, 0 implied int., 57 continuous)
   416 nonzeros

( 0.0s) Starting symmetry detection
( 0.0s) No symmetry present

Solving root node LP relaxation

        Nodes      |    B&B Tree     |            Objective Bounds              |  Dynamic Constraints |       Work
     Proc. InQueue |  Leaves   Expl. | BestBound       BestSol              Gap |   Cuts   InLp Confl. | LpIters     Time

 R       0       0         0   0.00%   2               3.13327127        36.17%        0      0      0        11     0.0s

Solving report
  Status            Optimal
  Primal bound      3.13327127023
  Dual bound        3.13327127023
  Gap               0% (tolerance: 0.01%)
  Solution status   feasible
                    3.13327127023 (objective)
                    0 (bound viol.)
                    0 (int. viol.)
                    0 (row viol.)
  Timing            0.04 (total)
                    0.01 (presolve)
                    0.00 (postsolve)
  Nodes             1
  LP iterations     114 (total)
                    0 (strong br.)
                    103 (separation)
                    0 (heuristics)
```

Compared  to default:

```
Presolving model
191 rows, 100 cols, 461 nonzeros
164 rows, 91 cols, 416 nonzeros

Solving MIP model with:
   164 rows
   91 cols (34 binary, 0 integer, 0 implied int., 57 continuous)
   416 nonzeros

( 0.0s) Starting symmetry detection
( 0.0s) No symmetry present

Solving root node LP relaxation

        Nodes      |    B&B Tree     |            Objective Bounds              |  Dynamic Constraints |       Work
     Proc. InQueue |  Leaves   Expl. | BestBound       BestSol              Gap |   Cuts   InLp Confl. | LpIters     Time

 R       0       0         0   0.00%   2               3.099384271       35.47%        0      0      0        36     0.0s

23.5% inactive integer columns, restarting
Model after restart has 119 rows, 66 cols (26 bin., 0 int., 0 impl., 40 cont.), and 301 nonzeros

         0       0         0   0.00%   2.944037761     3.099384271        5.01%        0      0      2       923     0.2s

Solving report
  Status            Optimal
  Primal bound      3.09938427067
  Dual bound        3.09938427067
  Gap               0% (tolerance: 0.01%)
  Solution status   feasible
                    3.09938427067 (objective)
                    0 (bound viol.)
                    0 (int. viol.)
                    0 (row viol.)
  Timing            0.21 (total)
                    0.02 (presolve)
                    0.00 (postsolve)
  Nodes             1
  LP iterations     1039 (total)
                    0 (strong br.)
                    228 (separation)
                    765 (heuristics)
```

The objective should be closer to `2.875` (which is the actual solution of the QP)

**Comment by lgottwald** [comment]
Interesting. I get objectives close to 2.875 on all 8 problems when I set:
```
mip_feasibility_tolerance = 1e-9
primal_feasibility_tolerance = 1e-9
```
On HiGHS 1.2.1. Which version are you using?

**Comment by joaquimg** [comment]
From my julia log, it seems to be 1.2.0. On windows.

**Comment by odow** [comment]
@joaquimg it's on `HiGHS#master`. I need to make a new release.

**Comment by odow** [comment]
Nice! I think this can be closed then. I already made a new release of HiGHS.jl.

**Comment by jajhall** [comment]
> Nice! I think this can be closed then. I already made a new release of HiGHS.jl.

A new release corresponding to what HiGHS Githash?

**Comment by odow** [comment]
> A new release corresponding to what HiGHS Githash?

Not release of HiGHS the solver, a release of HiGHS.jl the Julia package. Sorry for the confusion.

**Comment by jajhall** [comment]
What happened to that segfault you found a few days ago?

**Comment by odow** [comment]
I haven't had time to take another look yet.

**Comment by joaquimg** [comment]
Just closing the loop,
https://github.com/joaquimg/QuadraticToBinary.jl was updated to have HiGHS and testing solver and the one used in the usage example.
Thanks all fo the help.
