### ISSUE TITLE
Add HiGHS version number to the log

### ISSUE THREAD

**Issue by NPC** [ERGO-Code/HiGHS#784]
Hello again,

Hopefully a minor thing, it would be useful to have the library version number included in the library log output. If I run highs.exe it prints `Running HiGHS 1.2.0` at the top, but this information is missing if the library is called from, in my case, C#, where the first line in the log is “Presolving model”.

**Comment by jajhall** [comment]
I see what you mean: it would be printed before the first write of logging information.

**Comment by jajhall** [comment]
closed by #798
