### ISSUE TITLE
read compressed MPS/LP files

### ISSUE THREAD

**Issue by svigerske** [ERGO-Code/HiGHS#786]
It would be nice if HiGHS could read compressed input files.
I guess something like `zless prob.mps.gz | highs /dev/stdin` would already work (?).
But allowing `highs prob.mps.gz` may also be nice.

The header-only library from https://github.com/tmaklin/bxzstr, which makes several popular compression libraries available as C++ I/O  streams, looks promising. I could try to prepare a pull-request which adds this lib in `extern/`, adds checks to `CMakeLists.txt`, and uses it in the file readers, if that is of interest. bxzstr is under [Mozilla Public License](https://www.mozilla.org/en-US/MPL/2.0/FAQ/).

**Comment by jajhall** [comment]
We've considered this, but I don't want to do things that make HiGHS complicated license-wise. In particular, we don't want to compromise our MIT status. 

However, I see that  `https://github.com/tmaklin/bxzstr` "is a fork of the zstr library by Matei David, and the core functionality of this library remains largely the same.", and `https://github.com/mateidavid/zstr` is MIT. So, if you can build on `zstr` - or are sure that using `bxzstr` is OK - please go ahead.

**Comment by svigerske** [comment]
I preferred `bxzstr` because it seemed to support more compressions formats than `zstr`, i.e., bzlib and lzma in addition to zlib, and the MPL FAQ that I linked above, in particular Q7, seemed to require only that one include a link to the bxzstr code repo.   
But for my purposes, the zlib part is actually sufficient.

**Comment by jajhall** [comment]
Thanks. It sounds OK to me to use bxzstr, then

**Comment by mdhaber** [comment]
@jajhall would you like us to check on this? HiGHS is an important dependency of SciPy now, and MPL is a copyleft license, so I would rather be safe than sorry. 

Would the source code of `bxzstr` be distributed with HiGHS or just binaries?

**Comment by svigerske** [comment]
I was just going start working on this. But I'll just be going with `zstr` for now. Even though `bxzstr` may be ok, the "we don't want to compromise our MIT status" argument above is convincing.

**Comment by sschnug** [comment]
The file [extern/zstr/zstr_make_unique_polyfill.h](https://github.com/ERGO-Code/HiGHS/blob/eec5ec9bb1419ba0e097e5cf920f06ebda631be8/extern/zstr/zstr_make_unique_polyfill.h) in the current pull-request looks like it's GPL licensed, despite the source being MIT licensed in aggregate.

Not my area of expertise, but this worries me a bit.

If bigger projects embedding HiGHS would use tools like [scancode-toolkit](https://github.com/nexB/scancode-toolkit), this file will appear in it's analysis results and potentially induce some headache.

**Comment by svigerske** [comment]
Yeah, thanks for looking so closely. This seems to add an implementation of `std::make_unique` in case the compiler is set to C++11. With C++ >= 14 this isn't necessary, since it is part of the language then. Since HiGHS seems to set `-std=gnu++11`, I cannot just delete this. But I should find some way to get rid of this.

**Comment by jajhall** [comment]
Thanks for taking such a cautious approach to this issue, @sschnug and @svigerske 

Are you happy that the MIT compliance issue is settled @mdhaber ?

**Comment by lgottwald** [comment]
To add to the  discussion regarding the MPL license: The MPL is not a strict copyleft license and it is very clearly applying only to those source files that are MPL licensed. Any code of HiGHS would never be affected by the copyleft because it resides in different files. Only changes to the MPL licensed files must be published under MPL again, i.e. we cannot change the license of the compression library to MIT but it would never affect the MIT license of HiGHS code.

Having a fully MIT licensed alternative available makes license things a bit simpler to explain though, so I would also prefer it in this case.
