### ISSUE TITLE
brew install highs

### ISSUE THREAD

**Issue by ankane** [ERGO-Code/HiGHS#794]
Hi, thanks for this project! Just wanted to share that it's now available on Homebrew, so Mac users can install it with:

```sh
brew install highs
```

Homebrew precompiles libraries, so installation is pretty much instant 🎉 

Ref: https://github.com/Homebrew/homebrew-core/pull/98503

**Comment by jajhall** [comment]
Thanks. This will be very interesting for @galabovaa 

Ivet, could you check this out and add some appropriate words to README.md

**Comment by jajhall** [comment]
Thanks. @galabovaa has looked at this, and it runs fine on her Mac.

However, she observes that it has many unnecessary dependencies like CoinUtils, OSI and suite sparse, and is currently running quite a few others. 

Please remove these, as HiGHS has no external dependencies.

**Comment by feldmeier** [comment]
I can't comment on the dependencies (knowing too little about brew/Macs), but I can confirm Highs seems to work fine after being installed via brew

**Comment by ankane** [comment]
I submitted a PR to remove the optional dependencies. They were originally added since `CMakeLists.txt` checks for them.
