### ISSUE TITLE
Ruby interface

### ISSUE THREAD

**Issue by ankane** [ERGO-Code/HiGHS#795]
Hi, also wanted to share there are now [Ruby bindings](https://github.com/ankane/highs-ruby) for HiGHS 🎉 

It's fairly low-level right now, but should provide a good starting point for Ruby users. If you have any feedback, let me know or feel free to create an issue on the project. Thanks!

**Comment by jajhall** [comment]
I've not heard of Ruby, but I'm the old man without the computer science background. I'll ask @galabovaa to look into it.
