### ISSUE TITLE
Quadratic Problem to .lp file bug?

### ISSUE THREAD

**Issue by Downsite** [ERGO-Code/HiGHS#807]
Hi,

Testing my implementation of the QP in thhe C++ API, I tried to solve the problem
```
variables
 x within [-2,2];
 y within [-2,2];

minimize:
x*y+x*x;

constraints:
x>=-1;
```
when I write the Hessian correctly(?) as the triangular and sparse version of [2 1;1 0]
the output written by the file writer is incorrect (the returned solution is correct).

```
\ File written by Highs .lp filereader
min
 obj: +0 x1 +0 x2 + [ +2 x0 * x0 +1 x0 * x1 +0 x1 * x1  ]/2 
st
 con1lo: +1 x1 >= -1
bounds
 -2 <= x1 <= +2
 -2 <= x2 <= +2
bin
gen
semi
end
```

**Comment by feldmeier** [comment]
Thanks - this will be fixed in #828, it make take a bit to be merged thoguh
