### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by gregy4** [ERGO-Code/HiGHS#827]
The solver compiled from master branch produce currently segmentation fault on debian 11 when running attached lp file. Latest stable version 1.2.2, compiled and executed on same system works fine.

Compressed lp file [test5.zip](https://github.com/ERGO-Code/HiGHS/files/8572099/test5.zip)

Following command is executed
    bin/highs test5.lp

Output:
------------------------------------------------------------------------
Running HiGHS 1.2.2 [date: 2022-04-27, git hash: 574d56df]
Copyright (c) 2022 ERGO-Code under MIT licence terms
MIP  test5 has 151834 rows; 11845 cols; 314017 nonzeros; 11845 integer variables
Presolving model
81847 rows, 11716 cols, 174141 nonzeros
16236 rows, 11716 cols, 70820 nonzeros
16236 rows, 11716 cols, 70820 nonzeros
Objective function is integral with scale 1

Solving MIP model with:
   16236 rows
   11716 cols (11716 binary, 0 integer, 0 implied int., 0 continuous)
   70820 nonzeros

        Nodes      |    B&B Tree     |            Objective Bounds              |  Dynamic Constraints |       Work
     Proc. InQueue |  Leaves   Expl. | BestBound       BestSol              Gap |   Cuts   InLp Confl. | LpIters     Time

         0       0         0   0.00%   2               inf                  inf        0      0      0         0     0.5s
 R       0       0         0   0.00%   117             128                8.59%        0      0      0      4332     0.8s
 C       0       0         0   0.00%   117             127                7.87%      683      6      0      4350     1.4s
 T       0       0         0   0.00%   117             117                0.00%      683      6      0      4350     1.4s
Segmentation fault

**Comment by matteodefelice** [comment]
Same here on my Ubuntu machine (WSL in Windows 11). The problem was solved with version 1.2.1 but with the latest release (1.2.2 [date: 2022-04-27, git hash: 574d56df]) I get segmentation fault.

**Comment by matteodefelice** [comment]
Update from another machine, this time with CentOS 7: solved with 1.2.2/d60095a but segfault with 1.2.2/574d56d

```
(base) [felicma@ux-jrcpttwks093 HiGHS]$ highs test5.lp
Running HiGHS 1.2.2 [date: 2022-04-21, git hash: d60095a]
Copyright (c) 2022 ERGO-Code under MIT licence terms
Hessian has dimension 11845 but no nonzeros, so is ignored
MIP  test5 has 151834 rows; 11845 cols; 314017 nonzeros; 11845 integer variables
Presolving model
81847 rows, 11716 cols, 174141 nonzeros
16236 rows, 11716 cols, 70820 nonzeros
16236 rows, 11716 cols, 70820 nonzeros
Objective function is integral with scale 1

Solving MIP model with:
   16236 rows
   11716 cols (11716 binary, 0 integer, 0 implied int., 0 continuous)
   70820 nonzeros

( 0.6s) Starting symmetry detection
( 4.0s) Found 389 generators

        Nodes      |    B&B Tree     |            Objective Bounds                                                                                            |  Dynamic Constraints |       Work
     Proc. InQueue |  Leaves   Expl. | BestBound       BestSol              Gap                                                                               |   Cuts   InLp Confl. | LpIters     Time

         0       0         0   0.00%   2               inf                  inf                                                                                      0      0      0         0     4.0s
 R       0       0         0   0.00%   117             128                8.59%                                                                                      0      0      0      4332     4.4s
 C       0       0         0   0.00%   117             127                7.87%                                                                                    683      6      0      4350     5.3s
 T       0       0         0   0.00%   117             117                0.00%                                                                                    683      6      0      4350     5.3s

Solving report
  Status            Optimal
  Primal bound      117
  Dual bound        117
  Gap               0% (tolerance: 0.01%)
  Solution status   feasible
                    117 (objective)
                    0 (bound viol.)
                    0 (int. viol.)
                    0 (row viol.)
  Timing            5.35 (total)
                    0.55 (presolve)
                    0.00 (postsolve)
  Nodes             1
  LP iterations     4350 (total)
                    0 (strong br.)
                    18 (separation)
                    0 (heuristics)
```

and then the second:
```
Running HiGHS 1.2.2 [date: 2022-04-28, git hash: 574d56d]
Copyright (c) 2022 ERGO-Code under MIT licence terms
MIP  test5 has 151834 rows; 11845 cols; 314017 nonzeros; 11845 integer variables
Presolving model
81847 rows, 11716 cols, 174141 nonzeros
16236 rows, 11716 cols, 70820 nonzeros
16236 rows, 11716 cols, 70820 nonzeros
Objective function is integral with scale 1

Solving MIP model with:
   16236 rows
   11716 cols (11716 binary, 0 integer, 0 implied int., 0 continuous)
   70820 nonzeros

        Nodes      |    B&B Tree     |            Objective Bounds              |  Dynamic Constraints |       Work
     Proc. InQueue |  Leaves   Expl. | BestBound       BestSol              Gap |   Cuts   InLp Confl. | LpIters     Time

         0       0         0   0.00%   2               inf                  inf        0      0      0         0     0.6s
 R       0       0         0   0.00%   117             128                8.59%        0      0      0      4332     1.0s
 C       0       0         0   0.00%   117             127                7.87%      683      6      0      4350     3.0s
 T       0       0         0   0.00%   117             117                0.00%      683      6      0      4350     3.0s
Segmentation fault (core dumped)
```

**Comment by jajhall** [comment]
Thanks. This fails in `findPosition`, on line 982 of `HighsHash.h` 

Please would you have a look at this @lgottwald

**Comment by lgottwald** [comment]
Should now be fixed in master

**Comment by jajhall** [comment]
> Should now be fixed in master

Yes, I've checked this independently
