### ISSUE TITLE
Final objective value depends on solver

### ISSUE THREAD

**Issue by fuglede** [ERGO-Code/HiGHS#838]
When running [this example](https://github.com/ERGO-Code/HiGHS/files/8614036/example.txt) (rename to `example.lp`) through

```
$ highs example.lp
```
I get the correct result (an optimal value of 612):
```
Solving report
  Status            Optimal
  Primal bound      612
  Dual bound        612
  Gap               0% (tolerance: 0.01%)
  Solution status   feasible
                    612 (objective)
```
but if I run it through `highs --solver ipm example.lp` or `highs --solver simplex example.lp`, in both cases I get a model status of "Optimal" but objective values of 617.33 which is wrong.

Should I expect this behavior?

**Comment by fuglede** [comment]
I suppose the answer is as simple as "in both of those cases, the integrality constraints on the variables are ignored and the problem is just treated as an LP"? Caught me by surprise.

**Comment by jajhall** [comment]
Thanks, but (general) MIP problems cannot be solved using simplex or interior point alone, so we felt that it was unnecessary to document this. For a MIP, the --solver option is there to allow the LP relaxation to be solved - as is important for LP benchmarking when the model file corresponds to a MIP.

I've updated `README.md`

**Comment by fuglede** [comment]
Thanks, the addition to `README.md` is helpful.
