### ISSUE TITLE
Trying to load an LP file without a newline at the end of the file leads to out-of-memory errors

### ISSUE THREAD

**Issue by arcondello** [ERGO-Code/HiGHS#840]
I built the solver from the current [master](https://github.com/ERGO-Code/HiGHS/tree/d1d9839b83800ac04eb4a0bb50d64e2c3efed63c). When I used `highs pass.lp` on [pass.lp](https://gist.github.com/arcondello/3f4a71bd5742952b5ede0546edb1e423) it works fine, but running `highs fail.lp` on [fail.lp](https://gist.github.com/arcondello/a37cb4f4eb6292fb1e8f3f1ee1d4e0e3) results in running out of memory. The difference between the two is the newline at the end of the file.

Reverting to [v1.2.1](https://github.com/ERGO-Code/HiGHS/releases/tag/v1.2.1) resolves the issue

**Comment by jajhall** [comment]
Strange. Please would you look at this @feldmeier
