### ISSUE TITLE
CLang 14 warming

### ISSUE THREAD

**Issue by mingodad** [ERGO-Code/HiGHS#864]
While building HiGHS with clang-14 on Ubuntu 18.04 64 bits I'm getting this warning:
```
[ 13%] Building CXX object src/CMakeFiles/libhighs.dir/qpsolver/scaling.cpp.o
In file included from /home/mingo/dev/lp/HiGHS/src/qpsolver/quass.cpp:13:
In file included from /home/mingo/dev/lp/HiGHS/src/qpsolver/feasibility.hpp:7:
/home/mingo/dev/lp/HiGHS/src/qpsolver/feasibility_quass.hpp:31:13: warning: empty parentheses interpreted as a function declaration [-Wvexing-parse]
 Basis basis();
            ^~
/home/mingo/dev/lp/HiGHS/src/qpsolver/feasibility_quass.hpp:31:13: note: replace parentheses with an initializer to declare a variable
 Basis basis();
            ^~
            {}
```

**Comment by jajhall** [comment]
Thanks. This warning has been reported before. Can it be fixed easily @feldmeier ?

**Comment by mmuetzel** [comment]
An easy fix might be to remove the empty parenthesis if this should construct an object of the class `Basis`. Otherwise, it will be interpreted as a function declaration. If it *is* indeed a function declaration, it might be enough to declare it as `Basis basis(void);` to silence the warning.
