### ISSUE TITLE
Gathering cost and row names from .lp file

### ISSUE THREAD

**Issue by jajhall** [ERGO-Code/HiGHS#868]
The LP file reader accumulates variable names - since it has to use them, but not cost or row names. I'm working on a solution output format for glpsol - to help wean users off glpk! - that reports the cost row and constraints using names that currently only works when the model's read from MPS.

Could the cost row and constraint names be gathered and written into the HighsModel instance, please

This will also allow us to generate MPS from .lp with the same names

**Comment by feldmeier** [comment]
by "cost row", do you mean the name of the objective expression? where would I store that ideally?

**Comment by jajhall** [comment]
Yes, the name of the objective expression

In the mathprog-sol branch, I've created objective_name_ as a data member of the HighsLp class.

**Comment by feldmeier** [comment]
Right, once the two branches meet I can easily add that. For now I've added reading the constraint names as part of #873. Note that constraint names are not mandatory in .lp files. its even allowed to have some constraints with names and some without in the same file.

**Comment by jajhall** [comment]
Sure, constraint names are not mandatory, and there may be gaps, but there are situations where they are all present because the .lp file is generated using a modelling language, and the names are needed to write out a solution file.

I'll let you know when you can merge the mathprog-sol branch into this branch or, more likely, merge master after I've merged mathprog-sol into master.
