### ISSUE TITLE
Docs: Add a changelog to track changes between versions.

### ISSUE THREAD

**Issue by EwoutH** [ERGO-Code/HiGHS#893]
A changelog would be useful to keep track and read upon changes between releases.

Many formats are possible, some examples:
 - https://keepachangelog.com/en/1.0.0/
 - https://github.com/pandas-dev/pandas/blob/main/doc/source/whatsnew/v1.4.0.rst
 - https://github.com/scipy/scipy/blob/main/doc/release/1.8.0-notes.rst
 - https://github.com/jupyterlab/jupyterlab/blob/3.4.x/CHANGELOG.md

**Comment by jajhall** [comment]
We're doing this now
