### ISSUE TITLE
MIP solution callback

### ISSUE THREAD

**Issue by jajhall** [ERGO-Code/HiGHS#896]
A user has asked for a callback whenever an integer feasible solution is identified by the MIP solver. This doesn't strike me as being a difficult thing to introduce. What do you think @lgottwald ?

**Comment by odow** [comment]
I would caution against adding specific callback functions. It's a lot easier to deal with a generic callback infrastructure with codes to indicate which callback is being run. (There's a reason CPLEX deprecated their legacy callback stuff in favor of a new generic callback.)
