### ISSUE TITLE
make it possible to interrupt HiGHS

### ISSUE THREAD

**Issue by svigerske** [ERGO-Code/HiGHS#903]
I would like to have a way to interrupt a running HiGHS solve, maybe via a callback or a flag that I can set.
Preferable the incumbent, if any and solving MIP, or current LP solution, if solving LP, would be available afterwards.

**Comment by jajhall** [comment]
Sure. We need some general callback mechanism - rather than specific callbacks for different cases. Mainly relates to @lgottwald
