### ISSUE TITLE
HiGHS fails to solve simple compressed sensing problems

### ISSUE THREAD

**Issue by mckib2** [ERGO-Code/HiGHS#912]
Consider a simple toy example of compressed sensing with a 5-sparse 200 sample signal `x[n]`:

![image](https://user-images.githubusercontent.com/28734319/178364358-af25a296-9af7-4381-bc8d-fd0ad28540b0.png)

A normalized Gaussian sensing matrix `A` is used to compress `x[n]` into a 100 sample signal `b[n]`: `Ax = b`

Without getting into details (and stealing the latex from [this SO answer](https://math.stackexchange.com/a/1640470)), to reconstruct `x[n]` the LP is:

![image](https://user-images.githubusercontent.com/28734319/178365163-77ce3ed0-ba79-43a1-9043-8582b82fe494.png)

When solved with SciPy's legacy Python interior point and revised simplex implementations, we get the solution we expected with an appropriately close reconstruction of `x[n]` ($ \hat{x} $):

![image](https://user-images.githubusercontent.com/28734319/178365410-66119f4a-dfe5-48e1-b182-881177f42a5f.png)

But using either of the HIGHS LP solvers (IPM or dual simplex), the solutions are not very good, e.g., with dual simplex:

![image](https://user-images.githubusercontent.com/28734319/178365642-5d93d943-93da-4187-b228-22e8d8f28da2.png)

An MPS with the example problem is here: [cs.mps.txt](https://github.com/ERGO-Code/HiGHS/files/9087807/cs.mps.txt)

I've tried solving with/without presolve, changing the tolerances very tight and very loose, but nothing I do seems to get the solutions any better.  The constraint violation appears to be small, but the solution still seems way off compared where we would expect it to be.

**Comment by mckib2** [comment]
Follow-up: when `x[n] >= 0` with col bounds all `>=0`, it is solved correctly.  Investigating where the bounds issue might be happening (if that is indeed the issue)

**Comment by mckib2** [comment]
> The optimal objective value is also zero, not ||x||_1

This is expected -- we want to drive the values of `t` to zero

I have to squint at these MPS files to figure out what they're saying -- it could be that the translation from the problem definition in Python to MPS is incorrect.  Let me re-evaluate how the Python gets transformed into the form HiGHS needs and if that is indeed correct, I'll take a look at why the MPS doesn't match the problem.

For completeness, here's the Python:

```python
import numpy as np
from scipy.optimize import linprog

N = 200  # signal length
n = 50  # number of measurements
k = 5  # number of non-zero elements

# generate a random measurement matrix (normal), normalize columns; satisfies RIP
#np.random.seed(2)
A = np.random.randn(n, N)
A /= np.sqrt(np.sum(A**2, axis=0))

# sparse integer-valued signal, x
x = np.sign(np.random.rand(k) - 0.5)
x = np.append(x, np.zeros(N - k))
np.random.shuffle(x)
x *= np.random.randint(low=5, high=10, size=x.shape)

# simulate measurement according to A
b = A @ x

# reconstruct with LP solver
A_ub = np.ones((2*N, 2*N))
A_ub[N:, :] *= -1
A_ub[:N, N:] *= -1
b_ub = np.zeros(2*N)
A_eq = np.concatenate((A, np.zeros((n, N))), axis=1)
b_eq = b
bnds = [(-np.inf, np.inf)]*N + [(0, np.inf)]*N
c = [0]*N + [1]*N
res = linprog(c=c, A_ub=A_ub, b_ub=b_ub, A_eq=A_eq, b_eq=b_eq, bounds=bnds, method="highs-ds")
x_hat = res.x[:N]
```

**Comment by mckib2** [comment]
Ah -- I think I see what you're saying now.  `t` are added to achieve the sum of the absolute values of `x` as noted, but will not be zero as we have the additional constraint that `A x = b`, so `x` (and by extension `t`) must not be all zero.  Do I understand correctly?

**Comment by jajhall** [comment]
Yes

**Comment by jajhall** [comment]
I've stripped out the incorrect rows from the model, and replaced them with the correct structure. HiGHS gives 

> Using EKK dual simplex solver - serial
>   Iteration        Objective     Infeasibilities num(sum)
>           0     0.0000000000e+00 Pr: 100(47.8638); Du: 0(3.98296e-09) 0s
>         232     2.8999999978e+01 Pr: 0(0) 0s
> Model   status      : Optimal
> Simplex   iterations: 232
> Objective value     :  2.8999999978e+01
> HiGHS run time      :          0.10

Printing out the solution values bigger than 1e-6 in absolute value gives

> Variable  12 has value          -8 in [       -inf,         inf] and dual           0
> Variable  73 has value          -6 in [       -inf,         inf] and dual           0
> Variable 104 has value           5 in [       -inf,         inf] and dual           0
> Variable 152 has value           5 in [       -inf,         inf] and dual           0
> Variable 161 has value          -5 in [       -inf,         inf] and dual           0

The MPS file is 
[Uploading cs.mps.txt…]()

**Comment by jajhall** [comment]
No problem. It was interesting, and gave me an exercise in model building with HiGHS

**Comment by mckib2** [comment]
Quick follow up: SciPy/HiGHS works fine here, it was indeed all in coding up the model.  I fixed the Python snippet above to have the correct constraints as Julian fixed in the MPS file.  It's actually more surprising the legacy SciPy solvers worked at all.  Thanks again for your help!
