### ISSUE TITLE
LP file has incorrect variable indexing for the objective function QP part 

### ISSUE THREAD

**Issue by jeffreydeankelly2** [ERGO-Code/HiGHS#933]
I noticed that when the LP file is written for a QP problem, the quadratic portion of the objective function has the wrong "xnnn" references.

Although HiGHS solves the QP problem solver correctly, the LP file changes the variable references in the 1/2 * x' * Q * x part i.e., x1 becomes x0 and so on - see below:

\ File written by Highs .lp filereader
max
 obj: +1 x1 +0 x2 +0 x3 +0 x4 +0 x5 +0 x6 +0 x7 + [ +0 x0 * x0 +0 x1 * x1 +0 x2 * x2 +0 x3 * x3 -6 x4 * x4 -2 x5 * x5 -4 x6 * x6  ]/2 
st
 con1: +1 x2 -1 x5 = +1
 con2: +1 x3 -1 x7 = +2
 con3: +1 x4 -1 x6 = +3
 con4: +1 x2 +1 x3 +1 x4 = +5.5
 con5: +1 x1 = -0
bounds
 -0 <= x1 <= -0
 +0 <= x2 <= +5.5
 +0 <= x3 <= +5.5
 +0 <= x4 <= +5.5
 -1 <= x5 <= +4.5
 -3 <= x6 <= +2.5
 -2 <= x7 <= +3.5
end

**Comment by jajhall** [comment]
Well spotted. Should be a simple fix
