### ISSUE TITLE
Objective value in integer LP is larger by 1 than the highest value 

### ISSUE THREAD

**Issue by dario-marvin** [ERGO-Code/HiGHS#948]
The attached integer LP is engineered so that only one of its variables can be selected.
HiGHS correctly recognizes x(2,2,3,0) as the variable maximizing the objective function, however the returned objective value is 844431.480222595, while the value of variable x(2,2,3,0) in the objective function is 844430.480222595.

I am unable to understand why the objective value is larger by 1 than the highest value in the objective function.

[LP.lp.txt](https://github.com/ERGO-Code/HiGHS/files/9469040/LP.lp.txt)

**Comment by odow** [comment]
I can reproduce:
```
(base) oscar@Oscars-MBP Downloads % gurobi_cl LP.lp 

Set parameter LogFile to value "gurobi.log"
Using license file /Users/oscar/gurobi.lic

Gurobi Optimizer version 9.5.1 build v9.5.1rc2 (mac64[x86])
Copyright (c) 2022, Gurobi Optimization, LLC

Read LP format model from file LP.lp
Reading time = 0.00 seconds
: 1 rows, 35 columns, 35 nonzeros
Thread count: 4 physical cores, 8 logical processors, using up to 8 threads
Optimize a model with 1 rows, 35 columns and 35 nonzeros
Model fingerprint: 0x6765e056
Variable types: 0 continuous, 35 integer (35 binary)
Coefficient statistics:
  Matrix range     [1e+00, 1e+00]
  Objective range  [3e+03, 6e+06]
  Bounds range     [1e+00, 1e+00]
  RHS range        [1e+00, 1e+00]
Found heuristic solution: objective 331531.70298
Presolve removed 1 rows and 35 columns
Presolve time: 0.00s
Presolve: All rows and columns removed

Explored 0 nodes (0 simplex iterations) in 0.00 seconds (0.00 work units)
Thread count was 1 (of 8 available processors)

Solution count 2: 844430 331532 

Optimal solution found (tolerance 1.00e-04)
Best objective 8.444304802226e+05, best bound 8.444304802226e+05, gap 0.0000%
```

```
julia> using HiGHS_jll

julia> HiGHS_jll.highs() do exe
       run(`$exe LP.lp`)
       end
Running HiGHS 1.2.1 [date: , git hash: ]
Copyright (c) 2022 ERGO-Code under MIT licence terms
Hessian has dimension 35 but no nonzeros, so is ignored
MIP  LP has 1 rows; 35 cols; 35 nonzeros; 35 integer variables
Presolving model
1 rows, 15 cols, 15 nonzeros
1 rows, 4 cols, 4 nonzeros
1 rows, 2 cols, 2 nonzeros
0 rows, 1 cols, 0 nonzeros
0 rows, 0 cols, 0 nonzeros
Presolve: Optimal

Solving report
  Status            Optimal
  Primal bound      844431.480223
  Dual bound        844431.480223
  Gap               0% (tolerance: 0.01%)
  Solution status   feasible
                    844431.480223 (objective)
                    0 (bound viol.)
                    0 (int. viol.)
                    0 (row viol.)
  Timing            0.00 (total)
                    0.00 (presolve)
                    0.00 (postsolve)
  Nodes             0
  LP iterations     0 (total)
                    0 (strong br.)
                    0 (separation)
                    0 (heuristics)
```

**Comment by jajhall** [comment]
Interesting. I'll look at this when I return from holiday

**Comment by jajhall** [comment]
This is because the .lp file reader interprets `+ -2506.113808724971 x(0,0,5,0)` as `+1 -2506.113808724971 x(0,0,5,0)`, and assigns a spurious offset of 1 in the objective. It's worse in master when all 20 of the spurious +1 offsets are accumulated, and gives objective `844450.480223`!

**Comment by jajhall** [comment]
This bug and others are exposed by the simpler model 
[offset.lp.txt](https://github.com/ERGO-Code/HiGHS/files/9537223/offset.lp.txt)
and emphasised by the printing added to https://github.com/ERGO-Code/HiGHS/tree/fix-948

@svigerske : You've done much more than I have with the .lp file reader - particularly at the `token` level. Do you have time to look at this?

**Comment by svigerske** [comment]
Yes, if it isn't urgent.

**Comment by jajhall** [comment]
Thanks. I'll suppress the use of the `offset` that will fix this issue, and push to master, then there's no rush. I think that it just needs "+ +", "+ -", and "- -" interpreting properly.
