### ISSUE TITLE
Fix interpretation of ("+ +1.23"?), "+ -1.23" and "- -1.23" in .lp file reader

### ISSUE THREAD

**Issue by jajhall** [ERGO-Code/HiGHS#950]
This bug and others are exposed by the simpler model 
[offset.lp.txt](https://github.com/ERGO-Code/HiGHS/files/9537223/offset.lp.txt)
and emphasised by the printing added to https://github.com/ERGO-Code/HiGHS/tree/fix-948

@svigerske : You've done much more than I have with the .lp file reader - particularly at the `token` level. Do you have time to look at this?

_Originally posted by @jajhall in https://github.com/ERGO-Code/HiGHS/issues/948#issuecomment-1242206152_

**Comment by jajhall** [comment]
So, @svigerske , having merged (and then deleted) [/fix-948](https://github.com/ERGO-Code/HiGHS/tree/fix-948) into master, you're free to look at this issue in another branch.

**Comment by svigerske** [comment]
So what should actually happen in the LP reader with this input?

One could be strict and reject consecutive signs as an error. I doubt that the given example is valid .lp syntax.

It would also be easy to handle two consecutive signs in the way it was probably expected here, but do one want to allow arbitrary many signs, e.g., `+ - + - + - + [ x^2 ]` ?

**Comment by jajhall** [comment]
It's true that I'd not checked whether Gurobi would read the example. Is "valid .lp syntax." defined to this level of detail?

The issue came up because someone had the substring "+ -1.2345 x1" where, I guess, he'd written the "+" for a new term, then the coefficient value, and then the variable name. This is reasonable, since the "+" is needed in the case where the coefficient is positive (unless the coefficient is written out with an explicit "+") and was read OK by Gurobi. 

I'd say that three or more consecutive signs is an error
