### ISSUE TITLE
Remove the use of HConfig.h 

### ISSUE THREAD

**Issue by SanPen** [ERGO-Code/HiGHS#957]
Hi, 

I have been more or less successfully including the Highs code into another C++ code base to ensure even compilation conditions.

In doing so, I've found that `HConfig.h` being generated by Cmake is problematic. I'd like to suggest removing `HConfig.h` and declare those variables directly.

An example of how to achieve that is to create a cmake file, i.e. `version_info.cmake` and include it from `CmakeLists.txt`

```
# default values
SET(VERSION_MAJOR 1)
SET(VERSION_MINOR 0)
SET(VERSION_PATCH 0)
SET(VERSION_REVISION 0)
SET(COMPANY_NAME "MyCompany")
SET(COMPANY_COPYRIGHT "Copyright (C) MyCompany 2022")

# ----------------------------------------------------------------------------------------------------------------------
# automatic read of the version data
# ----------------------------------------------------------------------------------------------------------------------
file(READ "version.txt" ver)

string(REGEX MATCH "VERSION_MAJOR ([0-9]*)" _ ${ver})
set(VERSION_MAJOR ${CMAKE_MATCH_1})

string(REGEX MATCH "VERSION_MINOR ([0-9]*)" _ ${ver})
set(VERSION_MINOR ${CMAKE_MATCH_1})

string(REGEX MATCH "VERSION_PATCH ([0-9]*)" _ ${ver})
set(VERSION_PATCH ${CMAKE_MATCH_1})

string(REGEX MATCH "VERSION_REVISION ([0-9]*)" _ ${ver})
set(VERSION_REVISION ${CMAKE_MATCH_1})

message("version: ${VERSION_MAJOR}.${VERSION_MINOR}.${VERSION_PATCH}a${VERSION_REVISION}")

# this is not to be changed
add_definitions(-DSOFTWARE_VERSION="${VERSION_MAJOR}.${VERSION_MINOR}.${VERSION_PATCH}.${VERSION_REVISION}")
add_definitions(-DCOMPANY_COPYRIGHT_STR="${COMPANY_COPYRIGHT}")
```

This would read from a simple text file (`version.txt`) with all the defined info:

```
VERSION_MAJOR 1
VERSION_MINOR 0
VERSION_PATCH 0
VERSION_REVISION 0
```

best regards,
Santiago

**Comment by jajhall** [comment]
We've discussed this, and `HConfig.h` does a lot more than define the version number. It would require quite a tricky refactoring to eliminate `HConfig.h`, so we'll keep it for now.

**Comment by SanPen** [comment]
Hi, 

Just to provide a little bit of extra feedback; 

I was manually including HiGHS into my project as if it was part of the project and I got it working by removing the `HConfig.h` dependencies.

Since the last time, I thought about including it in the canonical CMAKE-based way described [here](https://ergo-code.github.io/HiGHS/man/link.html). In doing so, I've found that the compiler complaints about the absence of `HConfig.h` 

The code I use to include it is:
 ```
set(HIGHS_DIR ${CMAKE_CURRENT_LIST_DIR}/src/third_party/HiGHS-master)
include_directories(${HIGHS_DIR}/src)
find_package(HIGHS REQUIRED)
find_package(Threads)
```

Best regards,
Santiago

**Comment by SanPen** [comment]
Hi, 

Following the instructions to [include Highs](https://ergo-code.github.io/HiGHS/man/link.html), I get:

```
HighsInt.h:29:10: fatal error: HConfig.h: File or directory does not exist
   29 | #include "HConfig.h"
```
This is empirical proof of why including a file not included on the source is a bad idea.

What would be a valid way to fix this?

**Comment by jajhall** [comment]
This file defines values specific to the build, so it's natural for it not to be in the source.

All you've demonstrated I'd not to mess with a software build

No-one else has made your observations, and we won't be changing our use of HConfig.h

**Comment by galabovaa** [comment]
@SanPen We will not be removing HConfig.h, but we would like to help you with the include. 

When you run make install, if you check in the include/ folder of the installation folder, do you see HConfig.h? 

include_directories(..) is generally better replaced with target_include_directoies(..), for more recent versions of CMake. 

However, if you run CMake with 

**cmake -DHIGHS_DIR=path_to_highs_install/lib/cmake/highs ..**

or try 

**cmake -DHIGHS_DIR=path_to_highs_install/lib/ ..**

or 

**cmake -DHIGHS_DIR=path_to_highs_install/ ..**

there is no need for include_directories or target_include_directories. 

Apologies, we are refactoring the CMake build system and that may cause such issues at the moment. Perhaps you need the latter path from the lines above for -DHIGHS_DIR. Please give it a go and if possible let us know the structure of the installation dir, and make sure you use -DFAST_BUILD=ON.

If you are able to share your project with us, it may be easier for us to help you with the linking.
