### ISSUE TITLE
Incorrect Termination Status

### ISSUE THREAD

**Issue by kofgokhan** [ERGO-Code/HiGHS#966]
I posted a thread on JuMP forums about the incorrect solution status. Seen a similar issue with HiGHS before. Any ideas?

https://discourse.julialang.org/t/constraints-not-being-satisfied-while-using-vector-elements-as-rhs/88294

**Comment by odow** [comment]
This was likely the same as https://github.com/ERGO-Code/HiGHS/issues/902. It's fixed in the latest `master`, but we're just waiting on a new release of HiGHS to update HiGHS.jl.
